import {AppShell} from "@/app/components/app-shell";
import {createEvaluationBattery} from "@/app/actions/evaluate";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
export const dynamic="force-dynamic";
export default async function EvaluationBatteries(){const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return null;const [batteries,levels,programmes]=await Promise.all([
prisma.testBattery.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},include:{_count:{select:{evaluationItems:true}}},orderBy:{name:"asc"}}),
prisma.rulesetLevel.findMany({where:{status:"ACTIVE",program:{status:"ACTIVE",organisationAssignments:{some:{organisationId:c.organisation.id}}}},include:{program:true},orderBy:[{program:{name:"asc"}},{orderIndex:"asc"}]}),
prisma.coachingProgramme.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},include:{stages:{where:{status:"ACTIVE"},orderBy:{orderIndex:"asc"}}},orderBy:{name:"asc"}})
]);return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><a href="/evaluate" className="workspace-back">← Evaluate</a><div className="workspace-hero"><div><p className="workspace-kicker">Evaluate</p><h1>Evaluation batteries</h1><p className="workspace-meta">Reusable assessment definitions. A ruleset or programme-derived battery is evaluation context only and does not assign a gymnast.</p></div></div><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_380px]"><section><div className="section-heading"><h2>Available batteries</h2><span>{batteries.filter(b=>b._count.evaluationItems>0).length}</span></div><div className="mt-3 grid gap-2">{batteries.filter(b=>b._count.evaluationItems>0).map(b=><a key={b.id} href={"/evaluate/batteries/"+b.id} className="workspace-row"><div><strong>{b.name}</strong><span>{b.description??b.classification.toLowerCase()}</span></div><em>{b._count.evaluationItems} items</em></a>)}{!batteries.some(b=>b._count.evaluationItems>0)&&<div className="empty-state">No evaluation batteries yet.</div>}</div></section><aside><form action={createEvaluationBattery} className="workspace-form-card"><h2>Create battery</h2><p className="mt-1 text-sm text-[var(--muted)]">Start custom, or copy the current skill requirements from a programme stage or enabled ruleset level.</p><div className="workspace-form-grid mt-3"><input name="name" required placeholder="Battery name"/><textarea name="description" placeholder="Purpose / notes"/><select name="sourceType" defaultValue="CUSTOM"><option value="CUSTOM">Custom battery</option><option value="RULESET_LEVEL">Ruleset level</option><option value="PROGRAMME_STAGE">Programme stage</option></select><select name="sourceId"><option value="">No source / choose source…</option><optgroup label="Ruleset levels">{levels.map(l=><option key={l.id} value={l.id}>{l.program.name} · {l.name}</option>)}</optgroup><optgroup label="Programme stages">{programmes.flatMap(p=>p.stages.map(s=><option key={s.id} value={s.id}>{p.name} · {s.name}</option>))}</optgroup></select></div><button className="workspace-button workspace-button-primary mt-3">Create battery</button></form></aside></div></section></AppShell>}