import {notFound} from "next/navigation";
import {AppShell} from "@/app/components/app-shell";
import {OverviewWidgets,type OverviewWidget} from "@/app/components/overview-widgets";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {groupScopeWhere} from "@/app/lib/coaching-scope";
import {assignGroupProgramme,clearGroupProgramme} from "@/app/actions/programmes";
import {createGroupScheduleSlot,deleteGroupScheduleSlot,updateGroupScheduleSlot} from "@/app/actions/planning";
import {assignGroupFacility,clearGroupFacility} from "@/app/actions/facilities";
import {readOverviewLayout} from "@/app/lib/widget-layout";
import {archiveGroup} from "@/app/actions/core-coaching";
export const dynamic="force-dynamic";
const DAYS=[["MONDAY","Monday"],["TUESDAY","Tuesday"],["WEDNESDAY","Wednesday"],["THURSDAY","Thursday"],["FRIDAY","Friday"],["SATURDAY","Saturday"],["SUNDAY","Sunday"]] as const;
const day=(d:Date)=>new Intl.DateTimeFormat("en-IE",{weekday:"short",day:"numeric",month:"short"}).format(d);
function minutes(a:string,b:string){const [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number);return Math.max(0,bh*60+bm-(ah*60+am))}
function hours(slots:Array<{startTime:string;endTime:string}>){const h=slots.reduce((n,s)=>n+minutes(s.startTime,s.endTime),0)/60;return Number.isInteger(h)?String(h):h.toFixed(1)}
export default async function GroupOverview({params}:{params:Promise<{id:string}>}){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)notFound();const {id}=await params;
 const group=await prisma.trainingGroup.findFirst({where:{id,...groupScopeWhere(c.organisation.id,c.membership.id,c.access)},include:{memberships:{where:{gymnast:{status:"ACTIVE"}},include:{gymnast:true},orderBy:{joinedAt:"asc"}},coachAssignments:{include:{membership:{include:{user:true}}}},programmeAssignments:{include:{programme:true,stage:true}},scheduleSlots:{orderBy:[{orderIndex:"asc"},{startTime:"asc"}]},facilityPreference:{include:{location:true}}}});if(!group)notFound();
 const now=new Date(),programme=group.programmeAssignments[0],canManage=c.access.canManageRotations;const programmeOutcomes=programme?.stageId?await prisma.programmeStageOutcome.findMany({where:{organisationId:c.organisation.id,stageId:programme.stageId,status:"ACTIVE"},select:{id:true,title:true,category:true,apparatus:true,emphasis:true},orderBy:{orderIndex:"asc"},take:12}):[];
 const [sessions,evidence,programmes,facilities]=await Promise.all([
  prisma.trainingSession.findMany({where:{organisationId:c.organisation.id,trainingGroupId:group.id,sessionDate:{gte:now}},orderBy:[{sessionDate:"asc"},{startTime:"asc"}],take:5}),
  prisma.trainingEvidence.findMany({where:{session:{organisationId:c.organisation.id,trainingGroupId:group.id}},include:{gymnast:true,block:true},orderBy:{recordedAt:"desc"},take:6}),
  c.access.canManageProgrammesAndMethodology?prisma.coachingProgramme.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},include:{stages:{where:{status:"ACTIVE"},orderBy:{orderIndex:"asc"}}},orderBy:{name:"asc"}}):Promise.resolve([]),
  prisma.facilityLocation.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},orderBy:{name:"asc"}})
 ]);
 const gymnastIds=group.memberships.map(m=>m.gymnastId);
 const [testingSessions,routineCount,competitionCount,attendanceCount,preference]=await Promise.all([
  prisma.testingSession.findMany({where:{organisationId:c.organisation.id,trainingGroupId:group.id},include:{results:{select:{id:true}}},orderBy:{testedAt:"desc"},take:6}),
  gymnastIds.length?prisma.gymnastRoutine.count({where:{gymnastId:{in:gymnastIds},status:"ACTIVE"}}):Promise.resolve(0),
  gymnastIds.length?prisma.competitionEntry.count({where:{gymnastId:{in:gymnastIds},event:{organisationId:c.organisation.id}}}):Promise.resolve(0),
  gymnastIds.length?prisma.trainingAttendance.count({where:{gymnastId:{in:gymnastIds},session:{organisationId:c.organisation.id,trainingGroupId:group.id},status:{not:"NOT_RECORDED"}}}):Promise.resolve(0),
  prisma.membershipPresentationPreference.findUnique({where:{membershipId:c.membership.id}})
 ]);
 const schedule=group.scheduleSlots.map(s=>(DAYS.find(([v])=>v===s.dayOfWeek)?.[1]??s.dayOfWeek).slice(0,3)+" "+s.startTime+"–"+s.endTime).join(" · ");
 const card="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm";
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page">
  <a href="/groups" className="workspace-back">← My Groups</a>
  <div className="workspace-hero group-hero"><div><p className="workspace-kicker">Group overview</p><h1>{group.name}</h1><p className="workspace-meta">{programme?programme.programme.name+(programme.stage?" · "+programme.stage.name:""):"No programme"}{schedule?" · "+schedule:""}</p></div>{programmeOutcomes.length>0&&<div className="mt-4 flex flex-wrap gap-2">{programmeOutcomes.slice(0,6).map(o=><span key={o.id} className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{o.title} · {o.emphasis.toLowerCase()}</span>)}</div>}<div className="workspace-actions"><a href="/training" className="workspace-button workspace-button-primary">Start session</a><a href={"/analysis?group="+group.id} className="workspace-button">Progress</a></div></div>
  {(()=>{const next=sessions[0],week=sessions.slice(0,5),recentTesting=testingSessions[0],small=(label:string,value:string|number,href:string)=><a href={href} className="overview-data-card"><p>{label}</p><strong>{value}</strong></a>;const widgets:OverviewWidget[]=[
   {id:"NEXT",title:"Next session",category:"Schedule",default:true,defaultSize:"L",small:small("Next session",next?.title??"None","/planning"),medium:<a href={next?"/planning/"+next.id:"/planning"} className="overview-data-card"><p>Next session</p><strong>{next?.title??"No session planned"}</strong>{next&&<div><span>{day(next.sessionDate)} · {next.startTime}–{next.endTime}</span></div>}</a>},
   {id:"WEEK",title:"This week",category:"Schedule",default:true,small:small("This week",week.length+" sessions","/calendar"),medium:<a href="/calendar" className="overview-data-card"><p>This week</p><strong>{week.length} sessions</strong><div>{week.slice(0,4).map(s=><span key={s.id}>{day(s.sessionDate)} · {s.startTime}</span>)}</div></a>},
   {id:"ROTATION",title:"Rotation",category:"Training",default:true,small:small("Rotation",next?"Next session":"None",next?"/planning/"+next.id:"/rotations"),medium:<a href={next?"/planning/"+next.id:"/rotations"} className="overview-data-card"><p>Rotation</p><strong>{next?.title??"No upcoming session"}</strong><div><span>{next?"Plan the session rotation":"Open reusable club rotas"}</span></div></a>},
   {id:"TRAINING_CONTEXT",title:"Training context",category:"Training",default:true,small:small("Training context",programme?.stage?.name??programme?.programme.name??"Not set","/planning"),medium:<a href="/planning" className="overview-data-card"><p>Training context</p><strong>{programme?.programme.name??"No programme assigned"}</strong><div><span>{programme?.stage?.name??group.facilityPreference?.location.name??"No stage or facility set"}</span></div></a>},
   {id:"ROSTER",title:"Roster",category:"People",default:true,small:small("Roster",group.memberships.length,"/groups/"+group.id),medium:<div className="overview-data-card"><p>Roster</p><strong>{group.memberships.length} gymnasts</strong><div>{group.memberships.slice(0,5).map(m=><a key={m.gymnastId} href={"/gymnasts/"+m.gymnastId}>{m.gymnast.name}{m.isPrimary?" · primary":""}</a>)}</div></div>},
   {id:"PROGRESS",title:"Group progress",category:"Evidence",default:true,small:small("Group progress",evidence.length+" recent","/analysis?group="+group.id),medium:<a href={"/analysis?group="+group.id} className="overview-data-card"><p>Group progress</p><strong>{evidence.length?"Recent evidence":"No recent evidence"}</strong><div>{evidence.slice(0,4).map(e=><span key={e.id}>{e.gymnast.name} · {e.outcome}</span>)}</div></a>},
   {id:"ACTIVITY",title:"Recent activity",category:"Evidence",default:true,small:small("Recent activity",evidence.length,"/analysis?group="+group.id),medium:<a href={"/analysis?group="+group.id} className="overview-data-card"><p>Recent activity</p><strong>{evidence.length?"Training evidence":"No recent evidence"}</strong><div>{evidence.slice(0,4).map(e=><span key={e.id}>{e.gymnast.name} · {e.block.apparatus??e.block.title}</span>)}</div></a>},
   {id:"ATTENTION",title:"Worth your attention",category:"Evidence",default:true,small:small("Worth your attention",!sessions.length?"No upcoming session":"Review evidence","/analysis?group="+group.id),medium:<a href={"/analysis?group="+group.id} className="overview-data-card"><p>Worth your attention</p><strong>{!sessions.length?"No upcoming session":!evidence.length?"Limited recent evidence":"Evidence available"}</strong><div><span>{!evidence.length?"No recent evidence recorded":"Review recent observations in Analysis"}</span></div></a>},
   {id:"ATTENDANCE",title:"Attendance",category:"People",default:false,small:small("Attendance",attendanceCount,"/training"),medium:<a href="/training" className="overview-data-card"><p>Attendance</p><strong>{attendanceCount} recorded</strong><div><span>Attendance records for this group</span></div></a>},
   {id:"TESTING",title:"Testing",category:"Evidence",default:false,small:small("Testing",testingSessions.length,"/testing/results?group="+group.id),medium:<a href={"/testing/results?group="+group.id} className="overview-data-card"><p>Testing</p><strong>{recentTesting?day(recentTesting.testedAt):"Not yet assessed"}</strong><div>{recentTesting&&<span>{recentTesting.results.length} results in latest session</span>}</div></a>},
   {id:"ROUTINES",title:"Routines",category:"Technical",default:false,small:small("Routines",routineCount,"/groups/"+group.id),medium:<div className="overview-data-card"><p>Routines</p><strong>{routineCount} active</strong><div><span>Across the current roster</span></div></div>},
   {id:"COMPETITIONS",title:"Competitions",category:"Competition",default:false,small:small("Competitions",competitionCount,"/competitions"),medium:<a href="/competitions" className="overview-data-card"><p>Competitions</p><strong>{competitionCount} entries</strong><div><span>Competition entries across this roster</span></div></a>},
   {id:"PATHWAY",title:"Programme / pathway",category:"Context",default:false,small:small("Programme / pathway",programme?.programme.name??"Not assigned","#manage-group"),medium:<a href="#manage-group" className="overview-data-card"><p>Programme / pathway</p><strong>{programme?.programme.name??"Not assigned"}</strong><div>{programme?.stage&&<span>{programme.stage.name}</span>}</div></a>},
   {id:"VOLUME",title:"Training volume",category:"Training",default:false,small:small("Training volume",hours(group.scheduleSlots)+" hrs","/calendar"),medium:<a href="/calendar" className="overview-data-card"><p>Training volume</p><strong>{hours(group.scheduleSlots)} hours / week</strong><div><span>{group.scheduleSlots.length} recurring sessions</span></div></a>},
   {id:"COACH_TEAM",title:"Coach team",category:"Coaching",default:false,small:small("Coach team",group.coachAssignments.length,"#manage-group"),medium:<a href="#manage-group" className="overview-data-card"><p>Coach team</p><strong>{group.coachAssignments.length}</strong><div>{group.coachAssignments.slice(0,4).map(a=><span key={a.membershipId}>{a.membership.user.displayName}</span>)}</div></a>},
   {id:"HANDOFFS",title:"Handoffs",category:"Coaching",default:false,small:small("Handoffs","Open","/handoffs"),medium:<a href="/handoffs" className="overview-data-card"><p>Handoffs</p><strong>Coach handoff & cover</strong></a>},
   {id:"FACILITIES",title:"Facilities",category:"Context",default:false,small:small("Facilities",group.facilityPreference?.location.name??"Not assigned","#manage-group"),medium:<a href="#manage-group" className="overview-data-card"><p>Facilities</p><strong>{group.facilityPreference?.location.name??"Not assigned"}</strong></a>},
   {id:"EVIDENCE_COVERAGE",title:"Evidence coverage",category:"Evidence",default:false,small:small("Evidence coverage",evidence.length+" recent","/analysis?group="+group.id),medium:<a href={"/analysis?group="+group.id} className="overview-data-card"><p>Evidence coverage</p><strong>{evidence.length?"Recent evidence available":"Limited evidence"}</strong><div><span>{evidence.length+" recent records loaded"}</span></div></a>}
  ];return <div className="mt-7"><OverviewWidgets surface="GROUP" initialLayout={readOverviewLayout(preference,"GROUP")} widgets={widgets}/></div>})()}
  <details id="manage-group" className="management-panel mt-8"><summary>Manage group</summary><div className="management-grid">
   <section><h2>Schedule</h2><div className="mt-3 grid gap-2">{group.scheduleSlots.map(s=><details key={s.id} className="rounded-xl border border-[var(--border)] p-3"><summary className="cursor-pointer text-sm font-semibold">{DAYS.find(([v])=>v===s.dayOfWeek)?.[1]??s.dayOfWeek} · {s.startTime}–{s.endTime}</summary>{canManage&&<div className="mt-3"><form action={updateGroupScheduleSlot} className="grid gap-2"><input type="hidden" name="groupId" value={group.id}/><input type="hidden" name="scheduleId" value={s.id}/><select name="dayOfWeek" defaultValue={s.dayOfWeek} className="rounded-lg border border-[var(--border)] px-3 py-2">{DAYS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="flex gap-2"><input name="startTime" type="time" required defaultValue={s.startTime} className="min-w-0 flex-1 rounded-lg border border-[var(--border)] px-3 py-2"/><input name="endTime" type="time" required defaultValue={s.endTime} className="min-w-0 flex-1 rounded-lg border border-[var(--border)] px-3 py-2"/></div><input name="notes" defaultValue={s.notes??""} placeholder="Note" className="rounded-lg border border-[var(--border)] px-3 py-2"/><button className="workspace-button">Save</button></form><form action={deleteGroupScheduleSlot} className="mt-2"><input type="hidden" name="groupId" value={group.id}/><input type="hidden" name="scheduleId" value={s.id}/><button className="text-sm text-[var(--muted)]">Delete</button></form></div>}</details>)}{!group.scheduleSlots.length&&<span className="text-sm text-[var(--muted)]">No schedule</span>}</div>{canManage&&<form action={createGroupScheduleSlot} className="mt-3 grid gap-2"><input type="hidden" name="groupId" value={group.id}/><select name="dayOfWeek" required className="rounded-lg border border-[var(--border)] px-3 py-2">{DAYS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><div className="flex gap-2"><input name="startTime" type="time" required className="min-w-0 flex-1 rounded-lg border border-[var(--border)] px-3 py-2"/><input name="endTime" type="time" required className="min-w-0 flex-1 rounded-lg border border-[var(--border)] px-3 py-2"/></div><input name="notes" placeholder="Note" className="rounded-lg border border-[var(--border)] px-3 py-2"/><button className="workspace-button">Add time</button></form>}</section>
   <section><h2>Programme</h2><p className="mt-2 text-sm text-[var(--muted)]">{programme?programme.programme.name+(programme.stage?" · "+programme.stage.name:""):"Not assigned"}</p>{c.access.canManageProgrammesAndMethodology&&<div className="mt-3"><form action={assignGroupProgramme} className="grid gap-2"><input type="hidden" name="groupId" value={group.id}/><select name="programmeId" required className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">Programme…</option>{programmes.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="stageId" className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">No stage</option>{programmes.flatMap(p=>p.stages.map(s=><option key={s.id} value={s.id}>{p.name} · {s.name}</option>))}</select><button className="workspace-button">Assign</button></form>{programme&&<form action={clearGroupProgramme} className="mt-2"><input type="hidden" name="groupId" value={group.id}/><button className="text-sm text-[var(--muted)]">Clear programme</button></form>}</div>}</section>
   <section><h2>Facility</h2><p className="mt-2 text-sm text-[var(--muted)]">{group.facilityPreference?.location.name??"Not assigned"}</p>{canManage&&<div className="mt-3"><form action={assignGroupFacility} className="grid gap-2"><input type="hidden" name="groupId" value={group.id}/><select name="locationId" required defaultValue={group.facilityPreference?.locationId??""} className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">Facility…</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button className="workspace-button">Set facility</button></form>{group.facilityPreference&&<form action={clearGroupFacility} className="mt-2"><input type="hidden" name="groupId" value={group.id}/><button className="text-sm text-[var(--muted)]">Clear facility</button></form>}</div>}</section>
   <section><h2>Coaching team</h2><div className="mt-3 grid gap-2">{group.coachAssignments.map(a=><div key={a.membershipId} className="rounded-xl border border-[var(--border)] px-3 py-2 text-sm">{a.membership.user.displayName}</div>)}{!group.coachAssignments.length&&<span className="text-sm text-[var(--muted)]">No assigned coaches</span>}</div></section>
  <section><h2>Group lifecycle</h2><p className="mt-2 text-sm text-[var(--muted)]">Archive removes this group from active coaching surfaces without deleting its historical sessions or evidence.</p>{c.access.canManagePeopleAndRoles&&<form action={archiveGroup} className="mt-3"><input type="hidden" name="groupId" value={group.id}/><button className="workspace-button">Archive group</button></form>}</section>
  </div></details>
 </section></AppShell>
}
