-- Phase 3C canonical ruleset identity; structure only.
CREATE TABLE "RulesetProgram" ("id" TEXT NOT NULL PRIMARY KEY,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"governingBody" TEXT NOT NULL,"discipline" TEXT NOT NULL DEFAULT 'WAG',"status" TEXT NOT NULL DEFAULT 'ACTIVE',"sourceUrl" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL);
CREATE UNIQUE INDEX "RulesetProgram_code_key" ON "RulesetProgram"("code");
CREATE INDEX "RulesetProgram_governingBody_discipline_status_idx" ON "RulesetProgram"("governingBody","discipline","status");
CREATE TABLE "RulesetLevel" ("id" TEXT NOT NULL PRIMARY KEY,"programId" TEXT NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"orderIndex" INTEGER NOT NULL DEFAULT 0,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"notes" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "RulesetLevel_programId_fkey" FOREIGN KEY ("programId") REFERENCES "RulesetProgram" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "RulesetLevel_programId_code_key" ON "RulesetLevel"("programId","code");
CREATE INDEX "RulesetLevel_programId_orderIndex_status_idx" ON "RulesetLevel"("programId","orderIndex","status");
CREATE TABLE "OrganisationRulesetAssignment" ("organisationId" TEXT NOT NULL,"programId" TEXT NOT NULL,"enabledAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("organisationId","programId"),CONSTRAINT "OrganisationRulesetAssignment_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "OrganisationRulesetAssignment_programId_fkey" FOREIGN KEY ("programId") REFERENCES "RulesetProgram" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "OrganisationRulesetAssignment_programId_idx" ON "OrganisationRulesetAssignment"("programId");
CREATE TABLE "GymnastRulesetAssignment" ("gymnastId" TEXT NOT NULL PRIMARY KEY,"programId" TEXT NOT NULL,"levelId" TEXT,"assignedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GymnastRulesetAssignment_gymnastId_fkey" FOREIGN KEY ("gymnastId") REFERENCES "Gymnast" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "GymnastRulesetAssignment_programId_fkey" FOREIGN KEY ("programId") REFERENCES "RulesetProgram" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "GymnastRulesetAssignment_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "RulesetLevel" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX "GymnastRulesetAssignment_programId_levelId_idx" ON "GymnastRulesetAssignment"("programId","levelId");