import {AppShell} from "@/app/components/app-shell";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {gymnastScopeWhere} from "@/app/lib/coaching-scope";
export const dynamic="force-dynamic";
const d=(x:Date)=>x.toLocaleDateString("en-IE",{day:"2-digit",month:"short",year:"numeric"});
export default async function AnalysisPage({searchParams}:{searchParams:Promise<{gymnast?:string;compare?:string;group?:string;apparatus?:string;days?:string}>}){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return null;const q=await searchParams;
 const groups=await prisma.trainingGroup.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},select:{id:true,name:true,memberships:{select:{gymnastId:true}}},orderBy:{name:"asc"}});const gymnasts=await prisma.gymnast.findMany({where:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access),select:{id:true,name:true},orderBy:{name:"asc"}});
 const group=groups.find(g=>g.id===q.group);const visibleGymnasts=group?gymnasts.filter(g=>group.memberships.some(m=>m.gymnastId===g.id)):gymnasts;const ids=new Set(visibleGymnasts.map(g=>g.id)),gymnastId=ids.has(q.gymnast??"")?q.gymnast!:visibleGymnasts[0]?.id,compareId=ids.has(q.compare??"")&&q.compare!==gymnastId?q.compare!:null;
 const apparatus=["VAULT","UNEVEN_BARS","BALANCE_BEAM","FLOOR_EXERCISE"].includes(q.apparatus??"")?q.apparatus!:null;const days=[30,90,180,365].includes(Number(q.days))?Number(q.days):90;const since=new Date(Date.now()-days*86400000);
 const selected=visibleGymnasts.find(g=>g.id===gymnastId),compared=visibleGymnasts.find(g=>g.id===compareId);
 async function bundle(id:string|undefined){if(!id)return null;const [training,tests,competitions,programmes,rulesets,routines,videos,goals]=await Promise.all([
  prisma.trainingEvidence.findMany({where:{gymnastId:id,recordedAt:{gte:since},...(apparatus?{block:{apparatus}}:{})},select:{outcome:true,recordedAt:true,fatigueSnapshot:true,routineElementId:true,routineVaultId:true,routineCustomItemId:true},orderBy:{recordedAt:"asc"},take:1000}),
  prisma.testingResult.findMany({where:{gymnastId:id,recordedAt:{gte:since},...(apparatus?{metric:{apparatus}}:{})},select:{numberValue:true,recordedAt:true,metricNameSnapshot:true,unitSnapshot:true,directionSnapshot:true,metric:{select:{name:true,unit:true,direction:true,apparatus:true}}},orderBy:{recordedAt:"asc"},take:500}),
  prisma.competitionPerformance.findMany({where:{performedAt:{gte:since},apparatusPlan:{entry:{gymnastId:id},...(apparatus?{apparatus}:{})}},select:{finalScore:true,difficultyScore:true,executionScore:true,performedAt:true,apparatusPlan:{select:{apparatus:true,entry:{select:{event:{select:{name:true,eventDate:true,eventType:true}}}}}}},orderBy:{performedAt:"asc"},take:100}),
  prisma.gymnastProgrammeAssignmentHistory.findMany({where:{organisationId:c.organisation.id,gymnastId:id,OR:[{startedAt:{gte:since}},{endedAt:{gte:since}}]},select:{programmeName:true,stageName:true,startedAt:true,endedAt:true,changeReason:true},orderBy:{startedAt:"asc"}}),
  prisma.gymnastRulesetAssignmentHistory.findMany({where:{organisationId:c.organisation.id,gymnastId:id,OR:[{startedAt:{gte:since}},{endedAt:{gte:since}}]},select:{programName:true,levelName:true,startedAt:true,endedAt:true,changeReason:true},orderBy:{startedAt:"asc"}}),
  prisma.gymnastRoutine.findMany({where:{gymnastId:id,createdAt:{gte:since},...(apparatus?{apparatus}:{})},select:{id:true,name:true,apparatus:true,purpose:true,createdAt:true,rulesetLevelName:true},orderBy:{createdAt:"asc"}}),
  prisma.videoAsset.findMany({where:{organisationId:c.organisation.id,gymnastId:id,status:"ACTIVE",createdAt:{gte:since},...(apparatus?{apparatus}:{})},select:{id:true,title:true,apparatus:true,skillLabel:true,routineId:true,routineItemId:true,createdAt:true},orderBy:{createdAt:"asc"},take:200}),
  prisma.gymnastGoal.findMany({where:{organisationId:c.organisation.id,gymnastId:id,createdAt:{gte:since},...(apparatus?{OR:[{apparatus},{apparatus:null}]}:{})},select:{id:true,title:true,category:true,apparatus:true,status:true,createdAt:true,achievedAt:true},orderBy:{createdAt:"asc"},take:100})
 ]);return {training,tests,competitions,programmes,rulesets,routines,videos,goals}}
 const [a,b,groupBundles]=await Promise.all([bundle(gymnastId),bundle(compareId ?? undefined),group?Promise.all(visibleGymnasts.map(g=>bundle(g.id))):Promise.resolve([])]);
 const summary=(x:Awaited<ReturnType<typeof bundle>>)=>{if(!x)return null;const outcomes=x.training.reduce((z,e)=>{z[e.outcome]=(z[e.outcome]||0)+1;return z},{} as Record<string,number>);return {training:x.training.length,outcomes,tests:x.tests.length,competitions:x.competitions.filter(y=>y.finalScore!==null).length,markers:x.programmes.length+x.rulesets.length+x.routines.length+x.videos.length+x.goals.length}};
 const sa=summary(a),sb=summary(b);const metricGroups=new Map<string,{name:string;unit:string|null;values:{date:Date;value:number}[]}>();for(const t of a?.tests??[]){const k=t.metricNameSnapshot??t.metric.name;const unit=t.unitSnapshot??t.metric.unit;const g=metricGroups.get(k)??{name:k,unit,values:[]};g.values.push({date:t.recordedAt,value:t.numberValue});metricGroups.set(k,g)}
 const outcomeGroups=new Map<string,number>();for(const e of a?.training??[])outcomeGroups.set(e.outcome,(outcomeGroups.get(e.outcome)??0)+1);const totalOutcomes=[...outcomeGroups.values()].reduce((n,v)=>n+v,0);const routineLinkedTraining=(a?.training??[]).filter(e=>e.routineElementId||e.routineVaultId||e.routineCustomItemId).length;const routineLinkedVideos=(a?.videos??[]).filter(v=>v.routineId).length;const itemLinkedVideos=(a?.videos??[]).filter(v=>v.routineItemId).length;
 const groupSummary=group?groupBundles.reduce((z,x)=>{if(!x)return z;z.training+=x.training.length;z.tests+=x.tests.length;z.competitions+=x.competitions.filter(y=>y.finalScore!==null).length;for(const e of x.training)z.outcomes[e.outcome]=(z.outcomes[e.outcome]??0)+1;return z},{training:0,tests:0,competitions:0,outcomes:{} as Record<string,number>}):null;
 const timeline=[...(a?.programmes??[]).map(x=>({date:x.startedAt,label:"Programme",text:x.programmeName+(x.stageName?" · "+x.stageName:"")})),...(a?.rulesets??[]).map(x=>({date:x.startedAt,label:"Ruleset",text:x.programName+(x.levelName?" · "+x.levelName:"")})),...(a?.routines??[]).map(x=>({date:x.createdAt,label:"Routine",text:x.apparatus+" · "+x.name})),...(a?.videos??[]).map(x=>({date:x.createdAt,label:x.routineId?"Routine video":"Video",text:[x.apparatus,x.skillLabel??x.title,x.routineItemId?"specific routine item":null].filter(Boolean).join(" · ")})),...(a?.competitions??[]).map(x=>({date:x.apparatusPlan.entry.event.eventDate,label:"Competition",text:x.apparatusPlan.entry.event.name+" · "+x.apparatusPlan.apparatus})),...(a?.goals??[]).map(x=>({date:x.createdAt,label:"Goal",text:x.title+" · "+x.status.toLowerCase()})),...(a?.goals??[]).filter(x=>x.achievedAt).map(x=>({date:x.achievedAt!,label:"Goal achieved",text:x.title}))].sort((x,y)=>x.date.getTime()-y.date.getTime());
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><a href="/more" className="workspace-back">← More</a><div className="workspace-hero"><div><p className="workspace-kicker">Analysis</p><h1>Explore the evidence</h1><p className="workspace-meta">Relationships, differences and change over time — without ranking gymnasts or claiming causation.</p></div></div>
 <form className="mt-6 grid gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 md:grid-cols-5"><select name="group" defaultValue={group?.id??""} className="rounded-lg border px-3 py-2"><option value="">All accessible gymnasts</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select name="gymnast" defaultValue={gymnastId} className="rounded-lg border px-3 py-2">{visibleGymnasts.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select name="compare" defaultValue={compareId??""} className="rounded-lg border px-3 py-2"><option value="">No second gymnast</option>{visibleGymnasts.filter(g=>g.id!==gymnastId).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select name="apparatus" defaultValue={apparatus??""} className="rounded-lg border px-3 py-2"><option value="">All apparatus</option><option value="VAULT">Vault</option><option value="UNEVEN_BARS">Uneven Bars</option><option value="BALANCE_BEAM">Balance Beam</option><option value="FLOOR_EXERCISE">Floor Exercise</option></select><div className="flex gap-2"><select name="days" defaultValue={String(days)} className="min-w-0 flex-1 rounded-lg border px-3 py-2"><option value="30">30 days</option><option value="90">90 days</option><option value="180">180 days</option><option value="365">1 year</option></select><button className="rounded-lg border px-3 py-2 font-semibold">Apply</button></div></form>
 {group&&groupSummary&&<article className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Group evidence</p><h2 className="mt-1 text-lg font-semibold">{group.name}</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Gymnasts" value={visibleGymnasts.length}/><Stat label="Training observations" value={groupSummary.training}/><Stat label="Testing records" value={groupSummary.tests}/><Stat label="Competition records" value={groupSummary.competitions}/></div>{Object.keys(groupSummary.outcomes).length>0&&<p className="mt-3 text-xs text-[var(--muted)]">Recorded training outcomes across this group: {Object.entries(groupSummary.outcomes).map(([k,n])=>k.toLowerCase()+" "+n).join(" · ")}</p>}<p className="mt-3 text-xs text-[var(--muted)]">Aggregate counts describe available evidence for this selected group and period. They are not a group score and do not rank gymnasts.</p></article>}
 {selected&&<div className="mt-4 flex justify-end"><a href={"/mentor?gymnast="+selected.id+(apparatus?"&apparatus="+apparatus:"")+"&contextType=ANALYSIS&contextRef="+selected.id} className="rounded-xl border border-[var(--border)] px-3 py-2 text-sm font-semibold">Ask Mentor about this evidence →</a></div>} {!selected?<p className="mt-6 text-sm text-[var(--muted)]">No accessible gymnasts yet.</p>:<><section className={"mt-5 grid gap-4 "+(compared?"md:grid-cols-2":"")}><EvidenceCard name={selected.name} s={sa}/>{compared&&<EvidenceCard name={compared.name} s={sb}/>}</section>
 <section className="mt-5 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Training pattern</p><h2 className="mt-1 text-lg font-semibold">Recorded outcomes</h2><div className="mt-4 grid gap-2">{[...outcomeGroups.entries()].map(([outcome,count])=><div key={outcome} className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><span className="text-sm font-semibold">{outcome.replaceAll("_"," ").toLowerCase()}</span><span className="text-sm">{count} · {totalOutcomes?Math.round(count/totalOutcomes*100):0}%</span></div>)}{!totalOutcomes&&<p className="text-sm text-[var(--muted)]">No training outcomes in this period/filter.</p>}</div><p className="mt-4 text-xs text-[var(--muted)]">This describes recorded observations only. It is not a readiness score or ranking.</p></article><article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Testing trends</p><h2 className="mt-1 text-lg font-semibold">{selected.name}</h2><div className="mt-4 grid gap-3">{[...metricGroups.values()].map(m=>{const first=m.values[0],last=m.values[m.values.length-1],delta=last.value-first.value;return <div key={m.name} className="rounded-xl border border-[var(--border)] p-3"><div className="flex justify-between gap-3"><strong>{m.name}</strong><span>{last.value}{m.unit?" "+m.unit:""}</span></div><p className="mt-1 text-xs text-[var(--muted)]">{m.values.length} record{m.values.length===1?"":"s"} · first {first.value} → latest {last.value}{m.values.length>1?" · change "+(delta>0?"+":"")+delta.toFixed(2):""}</p></div>})}{!metricGroups.size&&<p className="text-sm text-[var(--muted)]">No testing evidence in this period/filter.</p>}</div><p className="mt-4 text-xs text-[var(--muted)]">Change is descriptive. Whether higher/lower is meaningful depends on the test protocol and coaching context.</p></article>
 <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Training ↔ competition</p><h2 className="mt-1 text-lg font-semibold">Recorded context</h2><p className="mt-3 text-sm">Training evidence in period: <strong>{a?.training.length??0}</strong></p><div className="mt-3 grid gap-2">{(a?.competitions??[]).map((x,i)=><div key={i} className="rounded-xl border border-[var(--border)] p-3 text-sm"><strong>{x.apparatusPlan.entry.event.name}</strong><p className="text-xs text-[var(--muted)]">{d(x.apparatusPlan.entry.event.eventDate)} · {x.apparatusPlan.apparatus}{x.finalScore!==null?" · final "+x.finalScore:" · no final score recorded"}</p></div>)}{!a?.competitions.length&&<p className="text-sm text-[var(--muted)]">No competition performances in this period/filter.</p>}</div><p className="mt-4 text-xs text-[var(--muted)]">Shown together for context; Viaform does not infer that training evidence caused a competition result.</p></article></section>
 <article className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Routine evidence</p><h2 className="mt-1 text-lg font-semibold">Plan ↔ observed evidence</h2><div className="mt-4 grid gap-3 sm:grid-cols-4"><Stat label="Routine plans" value={a?.routines.length??0}/><Stat label="Linked training" value={routineLinkedTraining}/><Stat label="Routine videos" value={routineLinkedVideos}/><Stat label="Item videos" value={itemLinkedVideos}/></div><p className="mt-4 text-xs text-[var(--muted)]">These counts show evidence explicitly linked to saved routine context. They do not determine whether a routine or skill should be changed.</p></article>
 <article className="mt-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">Context markers</p><h2 className="mt-1 text-lg font-semibold">What changed around the evidence</h2><div className="mt-4 grid gap-2">{timeline.map((x,i)=><div key={i} className="flex gap-3 rounded-xl border border-[var(--border)] p-3 text-sm"><span className="w-24 shrink-0 text-xs text-[var(--muted)]">{d(x.date)}</span><div><strong>{x.label}</strong><p className="text-[var(--muted)]">{x.text}</p></div></div>)}{!timeline.length&&<p className="text-sm text-[var(--muted)]">No programme, ruleset, routine, goal, video or competition markers recorded in this period.</p>}</div></article>
 <article className="mt-5 rounded-2xl border border-dashed border-[var(--border)] p-5"><strong>Evidence gaps</strong><p className="mt-2 text-sm text-[var(--muted)]">{!a?.training.length?"No training evidence. ":""}{!a?.tests.length?"No testing evidence. ":""}{!a?.competitions.length?"No competition performance evidence. ":""}{a?.training.length&&a?.tests.length&&a?.competitions.length?"Training, testing and competition evidence are all represented in this period.":""} Absence of evidence is not evidence of absence.</p></article></>}</section></AppShell>}
function EvidenceCard({name,s}:{name:string;s:{training:number;outcomes:Record<string,number>;tests:number;competitions:number;markers:number}|null}){return <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-lg font-semibold">{name}</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Training" value={s?.training??0}/><Stat label="Testing" value={s?.tests??0}/><Stat label="Competitions" value={s?.competitions??0}/><Stat label="Context markers" value={s?.markers??0}/></div>{s&&Object.keys(s.outcomes).length>0&&<p className="mt-3 text-xs text-[var(--muted)]">Training outcomes: {Object.entries(s.outcomes).map(([k,n])=>k.toLowerCase()+" "+n).join(" · ")}</p>}</article>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-[var(--border)] p-3"><strong className="text-xl">{value}</strong><p className="text-xs text-[var(--muted)]">{label}</p></div>}
