"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {gymnastScopeWhere} from "@/app/lib/coaching-scope";
const v=(d:FormData,k:string)=>String(d.get(k)??"").trim();
async function ctx(){const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)redirect("/more");return c}
export async function createEvaluation(d:FormData){const c=await ctx(),gymnastId=v(d,"gymnastId"),date=v(d,"evaluatedAt");const g=await prisma.gymnast.findFirst({where:{...gymnastScopeWhere(c.organisation.id,c.membership.id,c.access),id:gymnastId},select:{id:true,name:true}});if(!g)return;const e=await prisma.gymnastEvaluation.create({data:{organisationId:c.organisation.id,gymnastId:g.id,createdByMembershipId:c.membership.id,evaluationType:v(d,"evaluationType")||"INTAKE",title:v(d,"title")||g.name+" intake evaluation",evaluatedAt:/^\d{4}-\d{2}-\d{2}$/.test(date)?new Date(date+"T00:00:00.000Z"):new Date(),previousExperience:v(d,"previousExperience")||null,status:"IN_PROGRESS"}});redirect("/evaluate/"+e.id)}
export async function addEvaluationItem(d:FormData){const c=await ctx(),id=v(d,"evaluationId"),area=v(d,"area"),label=v(d,"label");if(!area||!label)return;const e=await prisma.gymnastEvaluation.findFirst({where:{id,organisationId:c.organisation.id,status:"IN_PROGRESS",gymnast:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)},select:{id:true}});if(!e)return;const raw=v(d,"numberValue"),num=raw===""?null:Number(raw);await prisma.gymnastEvaluationItem.create({data:{evaluationId:id,area,apparatus:v(d,"apparatus")||null,label,rating:v(d,"rating")||null,numberValue:num!==null&&Number.isFinite(num)?num:null,unit:v(d,"unit")||null,note:v(d,"note")||null,testMetricId:v(d,"testMetricId")||null}});revalidatePath("/evaluate/"+id)}
export async function completeEvaluation(d:FormData){const c=await ctx(),id=v(d,"evaluationId");const e=await prisma.gymnastEvaluation.findFirst({where:{id,organisationId:c.organisation.id,status:"IN_PROGRESS",gymnast:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)},select:{id:true}});if(!e)return;const programmeId=v(d,"recommendedProgrammeId"),stageId=v(d,"recommendedStageId"),groupId=v(d,"recommendedGroupId");const [p,st,g]=await Promise.all([programmeId?prisma.coachingProgramme.findFirst({where:{id:programmeId,organisationId:c.organisation.id},select:{id:true,name:true}}):null,stageId?prisma.programmeStage.findFirst({where:{id:stageId,programme:{organisationId:c.organisation.id}},select:{id:true,name:true}}):null,groupId?prisma.trainingGroup.findFirst({where:{id:groupId,organisationId:c.organisation.id},select:{id:true,name:true}}):null]);await prisma.gymnastEvaluation.update({where:{id},data:{overallObservation:v(d,"overallObservation")||null,placementContext:v(d,"placementContext")||null,recommendedProgrammeId:p?.id??null,recommendedProgrammeName:p?.name??null,recommendedStageId:st?.id??null,recommendedStageName:st?.name??null,recommendedGroupId:g?.id??null,recommendedGroupName:g?.name??null,placementDecision:v(d,"placementDecision")||null,status:"COMPLETED",completedAt:new Date()}});revalidatePath("/evaluate");redirect("/evaluate?completed="+id)}
