"use server";
import {revalidatePath} from "next/cache";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {gymnastScopeWhere} from "@/app/lib/coaching-scope";
const v=(d:FormData,k:string)=>String(d.get(k)??"").trim();
const categories=["DEVELOPMENT","SKILL","ROUTINE","PHYSICAL_PREPARATION","COMPETITION","PERSONAL"] as const;
const visibilities=["COACH_ONLY","ATHLETE","GUARDIAN","ATHLETE_GUARDIAN"] as const;
const statuses=["ACTIVE","PAUSED","ACHIEVED","ARCHIVED"] as const;
async function visibleGymnast(id:string,c:Awaited<ReturnType<typeof requireAuthContext>>){return prisma.gymnast.findFirst({where:{id,...gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)},select:{id:true,programmeAssignments:{select:{programme:{select:{name:true}},stage:{select:{name:true}}}},rulesetAssignments:{select:{program:{select:{name:true}},level:{select:{name:true}}}}}})}
async function visibleGoal(id:string,c:Awaited<ReturnType<typeof requireAuthContext>>){return prisma.gymnastGoal.findFirst({where:{id,organisationId:c.organisation.id,gymnast:{is:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)}}})}
const refresh=(gymnastId:string)=>{revalidatePath("/gymnasts/"+gymnastId);revalidatePath("/gymnasts/"+gymnastId+"/goals");revalidatePath("/analysis");revalidatePath("/athlete");revalidatePath("/guardian")};
export async function createGymnastGoal(d:FormData){const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return;const gymnast=await visibleGymnast(v(d,"gymnastId"),c),title=v(d,"title");if(!gymnast||!title||title.length>160)return;const category=v(d,"category")||"DEVELOPMENT",visibility=v(d,"visibility")||"ATHLETE_GUARDIAN";if(!categories.includes(category as any)||!visibilities.includes(visibility as any))return;const target=v(d,"targetDate");const programme=gymnast.programmeAssignments[0],rules=gymnast.rulesetAssignments[0];await prisma.gymnastGoal.create({data:{organisationId:c.organisation.id,gymnastId:gymnast.id,createdByMembershipId:c.membership.id,category,apparatus:v(d,"apparatus")||null,title,description:v(d,"description")||null,successCriteria:v(d,"successCriteria")||null,targetDate:target?new Date(target+"T12:00:00"):null,visibility,programmeNameSnapshot:programme?.programme.name??null,stageNameSnapshot:programme?.stage?.name??null,rulesetNameSnapshot:rules?.program.name??null,rulesetLevelSnapshot:rules?.level?.name??null}});refresh(gymnast.id)}
export async function addGymnastGoalUpdate(d:FormData){const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return;const goal=await visibleGoal(v(d,"goalId"),c),note=v(d,"note");if(!goal||!note||note.length>2000)return;await prisma.gymnastGoalUpdate.create({data:{goalId:goal.id,createdByMembershipId:c.membership.id,note,statusSnapshot:goal.status}});refresh(goal.gymnastId)}
export async function setGymnastGoalStatus(d:FormData){const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return;const goal=await visibleGoal(v(d,"goalId"),c),status=v(d,"status");if(!goal||!statuses.includes(status as any))return;const now=new Date();await prisma.gymnastGoal.update({where:{id:goal.id},data:{status,achievedAt:status==="ACHIEVED"?goal.achievedAt??now:null,pausedAt:status==="PAUSED"?goal.pausedAt??now:null,archivedAt:status==="ARCHIVED"?goal.archivedAt??now:null}});refresh(goal.gymnastId)}
