"use server";
import {redirect} from "next/navigation";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {gymnastScopeWhere} from "@/app/lib/coaching-scope";
const v=(d:FormData,k:string)=>String(d.get(k)??"").trim();
const words=(s:string)=>new Set(s.toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(x=>x.length>2));
const score=(q:Set<string>,...parts:(string|null|undefined)[])=>{const text=words(parts.filter(Boolean).join(" "));let n=0;q.forEach(x=>{if(text.has(x))n++});return n};
export async function askMentor(d:FormData){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)redirect("/dashboard");
 const question=v(d,"question"),gymnastId=v(d,"gymnastId")||null,apparatus=v(d,"apparatus")||null,contextType=v(d,"contextType")||"GENERAL",contextRef=v(d,"contextRef")||null;if(!question)return;
 let gymnast:null|{id:string,name:string}=null;if(gymnastId)gymnast=await prisma.gymnast.findFirst({where:{id:gymnastId,...gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)},select:{id:true,name:true}});if(gymnastId&&!gymnast)return;
 const routineContext=contextType==="ROUTINE"&&contextRef&&gymnast?await prisma.gymnastRoutine.findFirst({where:{id:contextRef,gymnastId:gymnast.id,status:"ACTIVE"},select:{id:true,name:true,apparatus:true,elements:{select:{id:true,elementDefinition:{select:{name:true,difficulty:true}}}},vaults:{select:{id:true,vaultDefinition:{select:{name:true,dValue:true}}}},customItems:{select:{id:true,label:true}}}}):null;
 const trainingContext=contextType==="TRAINING_REVIEW"&&contextRef?await prisma.trainingSession.findFirst({where:{id:contextRef,organisationId:c.organisation.id,status:"COMPLETED"},select:{id:true,title:true,trainingGroup:{select:{name:true}},evidence:{select:{outcome:true,note:true,recordedAt:true}},checkIns:{select:{feeling:true,confidence:true,fatigue:true,source:true,recordedAt:true}},}}):null;
 const testingContext=contextType==="TESTING_SESSION"&&contextRef?await prisma.testingSession.findFirst({where:{id:contextRef,organisationId:c.organisation.id},select:{id:true,name:true,batteryNameSnapshot:true,batteryVersionSnapshot:true,results:{select:{numberValue:true,pointsValue:true,classificationSnapshot:true,metricNameSnapshot:true,unitSnapshot:true,recordedAt:true}}}}):null;
 const competitionContext=contextType==="COMPETITION"&&contextRef?await prisma.competitionEvent.findFirst({where:{id:contextRef,organisationId:c.organisation.id},select:{id:true,name:true,eventType:true,eventDate:true,entries:{select:{id:true,gymnastId:true,apparatusPlans:{select:{apparatus:true,routineNameSnapshot:true,performance:{select:{status:true,difficultyScore:true,executionScore:true,penalty:true,finalScore:true,coachObservation:true,athleteReflection:{select:{rating:true,confidence:true,feltPrepared:true,whatFeltGood:true,whatFeltHard:true,athleteNote:true}}}}}}}}}}):null;
 const [methods,checks,evidence,memory]=await Promise.all([
  prisma.methodologyRecord.findMany({where:{organisationId:c.organisation.id,status:"APPROVED",...(apparatus?{OR:[{apparatus},{apparatus:null}]}:{})},select:{id:true,title:true,provenance:true,technicalObjective:true,technicalBoundaries:true,defaultApproach:true,alternativeApproaches:true,uncertainty:true,apparatus:true},take:100}),
  gymnast?prisma.trainingCheckIn.findMany({where:{gymnastId:gymnast.id},orderBy:{recordedAt:"desc"},take:5,select:{feeling:true,confidence:true,fatigue:true,source:true,recordedAt:true}}):Promise.resolve([]),
  gymnast?prisma.trainingEvidence.findMany({where:{gymnastId:gymnast.id,...(routineContext?{OR:[{routineElementId:{in:routineContext.elements.map(x=>x.id)}},{routineVaultId:{in:routineContext.vaults.map(x=>x.id)}},{routineCustomItemId:{in:routineContext.customItems.map(x=>x.id)}}]}:{})},orderBy:{recordedAt:"desc"},take:20,select:{outcome:true,note:true,fatigueSnapshot:true,recordedAt:true}}):Promise.resolve([]),
  gymnast?prisma.coachingMemoryObservation.findMany({where:{organisationId:c.organisation.id,gymnastId:gymnast.id},orderBy:{createdAt:"desc"},take:5,select:{observation:true,createdAt:true}}):Promise.resolve([])
 ]);
 const q=words(question);const relevant=methods.map(m=>({m,s:score(q,m.title,m.technicalObjective,m.technicalBoundaries,m.defaultApproach,m.alternativeApproaches,m.apparatus)})).sort((a,b)=>b.s-a.s).filter((x,i)=>x.s>0||i<3).slice(0,5).map(x=>x.m);
 const counts=evidence.reduce((a,e)=>{a[e.outcome]=(a[e.outcome]||0)+1;return a},{} as Record<string,number>);
 const lines:string[]=[];lines.push("Evidence snapshot");if(trainingContext){const tc=trainingContext.evidence.reduce((z,e)=>{z[e.outcome]=(z[e.outcome]??0)+1;return z},{} as Record<string,number>);lines.push("Training review: "+trainingContext.title+" · "+trainingContext.trainingGroup.name+" · "+trainingContext.evidence.length+" evidence records"+(trainingContext.evidence.length?" ("+Object.entries(tc).map(([k,n])=>k.toLowerCase()+" "+n).join(", ")+")":"."));}if(testingContext)lines.push("Testing context: "+testingContext.name+(testingContext.batteryNameSnapshot?" · "+testingContext.batteryNameSnapshot+" v"+(testingContext.batteryVersionSnapshot??1):"")+" · "+testingContext.results.length+" recorded results.");if(competitionContext){const plans=competitionContext.entries.flatMap(e=>e.apparatusPlans),recorded=plans.filter(x=>x.performance&&x.performance.status!=="NOT_RECORDED");lines.push("Competition context: "+competitionContext.name+" · "+competitionContext.eventType.toLowerCase()+" · "+competitionContext.entries.length+" entries · "+recorded.length+" recorded apparatus outcomes.");}if(routineContext)lines.push("Routine context: "+routineContext.name+" · "+routineContext.apparatus+" · "+(routineContext.elements.length+routineContext.vaults.length+routineContext.customItems.length)+" saved items.");if(contextType==="ANALYSIS"&&gymnast)lines.push("Analysis context: evidence exploration for "+gymnast.name+(apparatus?" · "+apparatus:"")+".");if(gymnast){lines.push(gymnast.name+": "+evidence.length+" recent training evidence records"+(evidence.length?" ("+Object.entries(counts).map(([k,n])=>k.toLowerCase()+" "+n).join(", ")+")":"."));const latest=checks[0];if(latest)lines.push("Latest Athlete State: "+[latest.feeling,latest.confidence,latest.fatigue].filter(Boolean).join(" · ")+" — gymnast self-report.");if(memory.length)lines.push("Recent Coaching Memory: "+memory[0].observation);}else lines.push("No gymnast was selected, so this answer is not using gymnast-specific evidence.");
 lines.push("");lines.push("Relevant methodology");if(relevant.length)relevant.forEach(m=>lines.push("• "+m.title+" ["+m.provenance.replaceAll("_"," ").toLowerCase()+"]"+(m.defaultApproach?": "+m.defaultApproach:"")));else lines.push("No approved club methodology matched this question.");
 lines.push("");lines.push("Worth considering");if(relevant[0]?.technicalObjective)lines.push(relevant[0].technicalObjective);else if(evidence.length)lines.push("Review the pattern in the recent evidence alongside the context in which it was recorded; the records alone do not establish why the pattern occurred.");else lines.push("There is limited stored evidence for Viaform to connect to this question.");
 if(relevant[0]?.alternativeApproaches)lines.push("Alternative approach: "+relevant[0].alternativeApproaches);if(relevant[0]?.technicalBoundaries)lines.push("Boundary: "+relevant[0].technicalBoundaries);
 lines.push("");lines.push("Coach decision required");lines.push("Use the evidence and methodology above as context. Viaform is not making a readiness, progression, selection or technical decision for you.");
 const hasOriginEvidence=!!routineContext||!!trainingContext||!!testingContext||!!competitionContext||contextType==="ANALYSIS";const uncertainty=[...relevant.map(m=>m.uncertainty).filter(Boolean),!evidence.length&&gymnast&&!hasOriginEvidence?"Limited recent training evidence.":null].filter(Boolean).join(" ");
 const row=await prisma.mentorQuestion.create({data:{organisationId:c.organisation.id,askedByMembershipId:c.membership.id,gymnastId:gymnast?.id??null,question,contextType,contextRef,apparatus,answer:lines.join("\n"),evidenceSnapshot:JSON.stringify({context:{type:contextType,ref:contextRef,routine:routineContext,training:trainingContext,testing:testingContext,competition:competitionContext},trainingEvidence:evidence,athleteState:checks,coachingMemory:memory}),methodologySnapshot:JSON.stringify(relevant),uncertainty:uncertainty||null}});
 redirect("/mentor?answer="+row.id);
}
