"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAuthContext } from "@/app/lib/auth";
import { prisma } from "@/app/lib/prisma";
const v=(d:FormData,k:string)=>String(d.get(k)??"").trim();
async function manager(){const c=await requireAuthContext();if(!c.access.canManageProgrammesAndMethodology)redirect("/rulesets?error=permission");return c;}
export async function createRulesetProgram(d:FormData){const c=await manager(),code=v(d,"code").toUpperCase(),name=v(d,"name"),governingBody=v(d,"governingBody"),discipline=v(d,"discipline")||"WAG";if(!code||!name||!governingBody)return;const p=await prisma.rulesetProgram.create({data:{code,name,governingBody,discipline}}).catch(()=>null);if(p)await prisma.organisationRulesetAssignment.create({data:{organisationId:c.organisation.id,programId:p.id}});revalidatePath("/rulesets");}
export async function createRulesetLevel(d:FormData){const c=await manager(),programId=v(d,"programId"),code=v(d,"code").toUpperCase(),name=v(d,"name");const enabled=await prisma.organisationRulesetAssignment.findUnique({where:{organisationId_programId:{organisationId:c.organisation.id,programId}}});if(!enabled||!code||!name)return;const count=await prisma.rulesetLevel.count({where:{programId}});await prisma.rulesetLevel.create({data:{programId,code,name,orderIndex:count}}).catch(()=>null);revalidatePath("/rulesets");}
export async function assignGymnastRuleset(d:FormData){const c=await manager(),gymnastId=v(d,"gymnastId"),programId=v(d,"programId"),levelId=v(d,"levelId");const gymnast=await prisma.gymnast.findFirst({where:{id:gymnastId,organisationId:c.organisation.id}}),enabled=await prisma.organisationRulesetAssignment.findUnique({where:{organisationId_programId:{organisationId:c.organisation.id,programId}}}),level=levelId?await prisma.rulesetLevel.findFirst({where:{id:levelId,programId}}):null;if(!gymnast||!enabled||(levelId&&!level))return;await prisma.gymnastRulesetAssignment.upsert({where:{gymnastId},create:{gymnastId,programId,levelId:level?.id},update:{programId,levelId:level?.id??null}});revalidatePath("/gymnasts/"+gymnastId);}
export async function clearGymnastRuleset(d:FormData){const c=await manager(),gymnastId=v(d,"gymnastId");const gymnast=await prisma.gymnast.findFirst({where:{id:gymnastId,organisationId:c.organisation.id}});if(!gymnast)return;await prisma.gymnastRulesetAssignment.deleteMany({where:{gymnastId}});revalidatePath("/gymnasts/"+gymnastId);}
