"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAuthContext } from "@/app/lib/auth";
import { prisma } from "@/app/lib/prisma";
import { logServerTiming } from "@/app/lib/server-performance";
const v=(d:FormData,k:string)=>String(d.get(k)??"").trim();
async function manager(){const c=await requireAuthContext();if(!c.access.canManageProgrammesAndMethodology)redirect("/rulesets?error=permission");return c;}
export async function enableRulesetProgram(d:FormData){const c=await manager(),programId=v(d,"programId");const p=await prisma.rulesetProgram.findFirst({where:{id:programId,status:"ACTIVE"}});if(!p)return;await prisma.organisationRulesetAssignment.upsert({where:{organisationId_programId:{organisationId:c.organisation.id,programId}},create:{organisationId:c.organisation.id,programId},update:{}});revalidatePath("/rulesets");}
export async function disableRulesetProgram(d:FormData){const c=await manager(),programId=v(d,"programId");await prisma.$transaction([prisma.gymnastRulesetAssignment.deleteMany({where:{programId,gymnast:{organisationId:c.organisation.id}}}),prisma.organisationRulesetAssignment.deleteMany({where:{organisationId:c.organisation.id,programId}})]);revalidatePath("/rulesets");}
export async function assignGymnastRuleset(d:FormData){const startedAt=Date.now(),c=await manager(),gymnastId=v(d,"gymnastId"),selection=v(d,"rulesetAssignment"),[selectedProgramId="",selectedLevelId=""]=selection.split(":"),programId=selectedProgramId||v(d,"programId"),levelId=selection?selectedLevelId:v(d,"levelId");const [gymnast,enabled,level]=await Promise.all([prisma.gymnast.findFirst({where:{id:gymnastId,organisationId:c.organisation.id}}),programId?prisma.organisationRulesetAssignment.findUnique({where:{organisationId_programId:{organisationId:c.organisation.id,programId}}}):Promise.resolve(null),levelId?prisma.rulesetLevel.findFirst({where:{id:levelId,programId,status:"ACTIVE"}}):Promise.resolve(null)]);if(!gymnast||!enabled||(levelId&&!level))return;await prisma.gymnastRulesetAssignment.upsert({where:{gymnastId},create:{gymnastId,programId,levelId:level?.id},update:{programId,levelId:level?.id??null}});revalidatePath("/gymnasts/"+gymnastId);logServerTiming("action.ruleset.assign-gymnast",startedAt);}
export async function clearGymnastRuleset(d:FormData){const c=await manager(),gymnastId=v(d,"gymnastId");const gymnast=await prisma.gymnast.findFirst({where:{id:gymnastId,organisationId:c.organisation.id}});if(!gymnast)return;await prisma.gymnastRulesetAssignment.deleteMany({where:{gymnastId}});revalidatePath("/gymnasts/"+gymnastId);}
