"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAuthContext } from "@/app/lib/auth";
import { prisma } from "@/app/lib/prisma";
import { logServerTiming } from "@/app/lib/server-performance";
const v=(d:FormData,k:string)=>String(d.get(k)??"").trim();
async function manager(){const c=await requireAuthContext();if(!c.access.canManageProgrammesAndMethodology)redirect("/rulesets?error=permission");return c;}
export async function enableRulesetProgram(d:FormData){const c=await manager(),programId=v(d,"programId");const p=await prisma.rulesetProgram.findFirst({where:{id:programId,status:"ACTIVE"}});if(!p)return;await prisma.organisationRulesetAssignment.upsert({where:{organisationId_programId:{organisationId:c.organisation.id,programId}},create:{organisationId:c.organisation.id,programId},update:{}});revalidatePath("/rulesets");}
export async function disableRulesetProgram(d:FormData){const c=await manager(),programId=v(d,"programId"),now=new Date();const current=await prisma.gymnastRulesetAssignment.findMany({where:{programId,gymnast:{organisationId:c.organisation.id}},select:{gymnastId:true}});await prisma.$transaction(async tx=>{if(current.length)await tx.gymnastRulesetAssignmentHistory.updateMany({where:{gymnastId:{in:current.map(x=>x.gymnastId)},endedAt:null},data:{endedAt:now,changeReason:"RULESET_DISABLED"}});await tx.gymnastRulesetAssignment.deleteMany({where:{programId,gymnast:{organisationId:c.organisation.id}}});await tx.organisationRulesetAssignment.deleteMany({where:{organisationId:c.organisation.id,programId}})});revalidatePath("/rulesets");}
export async function assignGymnastRuleset(d:FormData){const startedAt=Date.now(),c=await manager(),gymnastId=v(d,"gymnastId"),selection=v(d,"rulesetAssignment"),[selectedProgramId="",selectedLevelId=""]=selection.split(":"),programId=selectedProgramId||v(d,"programId"),levelId=selection?selectedLevelId:v(d,"levelId");const [gymnast,enabled,level,program,current]=await Promise.all([prisma.gymnast.findFirst({where:{id:gymnastId,organisationId:c.organisation.id,status:"ACTIVE"}}),programId?prisma.organisationRulesetAssignment.findUnique({where:{organisationId_programId:{organisationId:c.organisation.id,programId}}}):Promise.resolve(null),levelId?prisma.rulesetLevel.findFirst({where:{id:levelId,programId,status:"ACTIVE"}}):Promise.resolve(null),programId?prisma.rulesetProgram.findUnique({where:{id:programId}}):Promise.resolve(null),prisma.gymnastRulesetAssignment.findUnique({where:{gymnastId}})]);if(!gymnast||!enabled||!program||(levelId&&!level))return;if(current?.programId===programId&&(current.levelId??null)===(level?.id??null))return;const now=new Date();await prisma.$transaction(async tx=>{await tx.gymnastRulesetAssignmentHistory.updateMany({where:{gymnastId,endedAt:null},data:{endedAt:now}});await tx.gymnastRulesetAssignment.upsert({where:{gymnastId},create:{gymnastId,programId,levelId:level?.id},update:{programId,levelId:level?.id??null,assignedAt:now}});await tx.gymnastRulesetAssignmentHistory.create({data:{organisationId:c.organisation.id,gymnastId,programId,levelId:level?.id,programCode:program.code,programName:program.name,levelCode:level?.code??null,levelName:level?.name??null,startedAt:now}})});revalidatePath("/gymnasts/"+gymnastId);logServerTiming("action.ruleset.assign-gymnast",startedAt);}
export async function clearGymnastRuleset(d:FormData){const c=await manager(),gymnastId=v(d,"gymnastId");const gymnast=await prisma.gymnast.findFirst({where:{id:gymnastId,organisationId:c.organisation.id}});if(!gymnast)return;const now=new Date();await prisma.$transaction([prisma.gymnastRulesetAssignmentHistory.updateMany({where:{gymnastId,endedAt:null},data:{endedAt:now,changeReason:"CLEARED"}}),prisma.gymnastRulesetAssignment.deleteMany({where:{gymnastId}})]);revalidatePath("/gymnasts/"+gymnastId);}
