-- Bars completeness audit: current-cycle named elements absent from the restored legacy-derived subset.
-- Descriptions/values are from World Gymnastics current-cycle official publications; stable Viaform identities remain keyed by FIG number + variant.
INSERT OR IGNORE INTO "FigElementDefinition" ("id","packageId","apparatus","officialNumber","variantKey","name","aliases","difficulty","groupCode","groupName","sourcePage","metadata","verificationStatus","status") VALUES ('fig25_ub_pet_1','canonical_fig_wag_2025_2028','BARS','1.404','a','Stretch jump (legs together) with 1/1 turn (360°) over LB to hang on HB (Petrova)','["petrova","full turning jump over low bar"]','D','Mounts','Mounts',74,'{"catalogue":"FIG WAG 2025-2028","revision":"2026-08-27","currentCycleNamedElement":true}','VERIFIED','ACTIVE');
INSERT OR IGNORE INTO "ViaformSkill" ("id","discipline","apparatus","name","aliases","provenance","figElementDefinitionId","canonicalKey","status","createdAt","updatedAt") SELECT 'fig_element_'||"id",'WAG','BARS','Petrova',"aliases",'FIG',"id",'FIG:ELEMENT:BARS:'||"officialNumber"||':'||"variantKey",'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "FigElementDefinition" WHERE "id"='fig25_ub_pet_1';
INSERT OR IGNORE INTO "FigElementDefinition" ("id","packageId","apparatus","officialNumber","variantKey","name","aliases","difficulty","groupCode","groupName","sourcePage","metadata","verificationStatus","status") VALUES ('fig25_ub_godwin','canonical_fig_wag_2025_2028','BARS','2.504','a','Clear hip circle forward to handstand with 1/1 turn (360°) in handstand phase (Godwin)','["godwin","weiler full","weiler kip full"]','E','Casts & clear hips','Casts & clear hips',79,'{"catalogue":"FIG WAG 2025-2028","revision":"2026-08-27","currentCycleNamedElement":true}','VERIFIED','ACTIVE');
INSERT OR IGNORE INTO "ViaformSkill" ("id","discipline","apparatus","name","aliases","provenance","figElementDefinitionId","canonicalKey","status","createdAt","updatedAt") SELECT 'fig_element_'||"id",'WAG','BARS','Godwin',"aliases",'FIG',"id",'FIG:ELEMENT:BARS:'||"officialNumber"||':'||"variantKey",'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "FigElementDefinition" WHERE "id"='fig25_ub_godwin';
INSERT OR IGNORE INTO "FigElementDefinition" ("id","packageId","apparatus","officialNumber","variantKey","name","aliases","difficulty","groupCode","groupName","sourcePage","metadata","verificationStatus","status") VALUES ('fig25_ub_zhang','canonical_fig_wag_2025_2028','BARS','2.706','a','Clear hip circle on HB with counter-stretched reverse hecht in layout position over HB to hang (Zhang)','["zhang","clear hip layout tkatchev"]','G','Casts & clear hips','Casts & clear hips',81,'{"catalogue":"FIG WAG 2025-2028","revision":"2026-08-27","currentCycleNamedElement":true}','VERIFIED','ACTIVE');
INSERT OR IGNORE INTO "ViaformSkill" ("id","discipline","apparatus","name","aliases","provenance","figElementDefinitionId","canonicalKey","status","createdAt","updatedAt") SELECT 'fig_element_'||"id",'WAG','BARS','Zhang',"aliases",'FIG',"id",'FIG:ELEMENT:BARS:'||"officialNumber"||':'||"variantKey",'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "FigElementDefinition" WHERE "id"='fig25_ub_zhang';
INSERT OR IGNORE INTO "FigElementDefinition" ("id","packageId","apparatus","officialNumber","variantKey","name","aliases","difficulty","groupCode","groupName","sourcePage","metadata","verificationStatus","status") VALUES ('fig25_ub_yang','canonical_fig_wag_2025_2028','BARS','3.708','a','Jaeger salto stretched with 1/1 turn (360°) to hang on HB (Yang)','["yang","layout jaeger full","jaeger full"]','G','Giant circles','Giant circles',88,'{"catalogue":"FIG WAG 2025-2028","revision":"2026-08-27","currentCycleNamedElement":true}','VERIFIED','ACTIVE');
INSERT OR IGNORE INTO "ViaformSkill" ("id","discipline","apparatus","name","aliases","provenance","figElementDefinitionId","canonicalKey","status","createdAt","updatedAt") SELECT 'fig_element_'||"id",'WAG','BARS','Yang',"aliases",'FIG',"id",'FIG:ELEMENT:BARS:'||"officialNumber"||':'||"variantKey",'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "FigElementDefinition" WHERE "id"='fig25_ub_yang';
INSERT OR IGNORE INTO "FigElementDefinition" ("id","packageId","apparatus","officialNumber","variantKey","name","aliases","difficulty","groupCode","groupName","sourcePage","metadata","verificationStatus","status") VALUES ('fig25_ub_sayer','canonical_fig_wag_2025_2028','BARS','4.308','a','Clear pike circle backward on HB with flight to clear support on LB (Sayer)','["sayer","inbar high to low"]','C','Stalder circles','Stalder circles',93,'{"catalogue":"FIG WAG 2025-2028","revision":"2026-08-27","currentCycleNamedElement":true}','VERIFIED','ACTIVE');
INSERT OR IGNORE INTO "ViaformSkill" ("id","discipline","apparatus","name","aliases","provenance","figElementDefinitionId","canonicalKey","status","createdAt","updatedAt") SELECT 'fig_element_'||"id",'WAG','BARS','Sayer',"aliases",'FIG',"id",'FIG:ELEMENT:BARS:'||"officialNumber"||':'||"variantKey",'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "FigElementDefinition" WHERE "id"='fig25_ub_sayer';
INSERT OR IGNORE INTO "FigElementDefinition" ("id","packageId","apparatus","officialNumber","variantKey","name","aliases","difficulty","groupCode","groupName","sourcePage","metadata","verificationStatus","status") VALUES ('fig25_ub_nemour','canonical_fig_wag_2025_2028','BARS','4.710','a','Clear pike circle backward with counter stretched reverse hecht in layout position over HB to hang (Nemour)','["nemour","inbar layout tkatchev"]','G','Stalder circles','Stalder circles',94,'{"catalogue":"FIG WAG 2025-2028","revision":"2026-08-27","currentCycleNamedElement":true}','VERIFIED','ACTIVE');
INSERT OR IGNORE INTO "ViaformSkill" ("id","discipline","apparatus","name","aliases","provenance","figElementDefinitionId","canonicalKey","status","createdAt","updatedAt") SELECT 'fig_element_'||"id",'WAG','BARS','Nemour',"aliases",'FIG',"id",'FIG:ELEMENT:BARS:'||"officialNumber"||':'||"variantKey",'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "FigElementDefinition" WHERE "id"='fig25_ub_nemour';
INSERT OR IGNORE INTO "FigElementDefinition" ("id","packageId","apparatus","officialNumber","variantKey","name","aliases","difficulty","groupCode","groupName","sourcePage","metadata","verificationStatus","status") VALUES ('fig25_ub_okamura','canonical_fig_wag_2025_2028','BARS','6.405','c','From L-grip, swing backward with 1/2 turn (180°) to double salto backward piked (Okamura)','["okamura","l-grip half double pike"]','D','Dismounts','Dismounts',103,'{"catalogue":"FIG WAG 2025-2028","revision":"2026-08-27","currentCycleNamedElement":true}','VERIFIED','ACTIVE');
INSERT OR IGNORE INTO "ViaformSkill" ("id","discipline","apparatus","name","aliases","provenance","figElementDefinitionId","canonicalKey","status","createdAt","updatedAt") SELECT 'fig_element_'||"id",'WAG','BARS','Okamura',"aliases",'FIG',"id",'FIG:ELEMENT:BARS:'||"officialNumber"||':'||"variantKey",'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM "FigElementDefinition" WHERE "id"='fig25_ub_okamura';
