"use client";
import type {ReactNode} from "react";
import {usePathname} from "next/navigation";
import {signOut} from "@/app/actions/auth";
import type {AccessProfile} from "@/app/lib/access-control";
import {coachingRoleLabel,primaryNavigation} from "@/app/lib/navigation";
import {ViaformMark} from "@/app/components/viaform-mark";
import {BannerThemeIndicator} from "@/app/components/banner-theme-indicator";
type Props={children:ReactNode;organisationName:string;displayName:string;access:AccessProfile};
type IconName="home"|"calendar"|"groups"|"planning"|"training"|"testing"|"routine"|"competition"|"more";
function NavIcon({name}:{name:IconName}){const paths:Record<IconName,ReactNode>={home:<><path d="M3 10.5 12 3l9 7.5"/><path d="M5.5 9.5V21h13V9.5"/><path d="M9.5 21v-6h5v6"/></>,calendar:<><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/><path d="M8 14h3M13 14h3M8 17h3"/></>,groups:<><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3.5 20c.6-4 2.4-6 5.5-6s5 2 5.5 6"/><path d="M14.5 15c3.4-.5 5.3 1.3 6 4.5"/></>,planning:<><path d="M4 18 9 13l4 3 7-9"/><path d="M16 7h4v4"/></>,training:<><path d="M4 8h3M17 8h3M7 5v6M17 5v6M7 8h10"/><path d="M6 16h12M8 13v6M16 13v6"/></>,testing:<><path d="M9 3h6M10 3v5l-5 9a2.5 2.5 0 0 0 2.2 4h9.6a2.5 2.5 0 0 0 2.2-4l-5-9V3"/><path d="M7.5 15h9"/></>,routine:<><path d="M6 3h12v18H6z"/><path d="M9 7h6M9 11h6M9 15h4"/><path d="m14 17 1.5 1.5L19 15"/></>,competition:<><path d="M8 4h8v4a4 4 0 0 1-8 0V4Z"/><path d="M8 6H4v1a4 4 0 0 0 4 4M16 6h4v1a4 4 0 0 1-4 4M12 12v5M8 21h8M9 17h6"/></>,more:<><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></>};return <svg className="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
const icons:Record<string,IconName>={Home:"home",Calendar:"calendar","My Groups":"groups",Planning:"planning",Training:"training",Testing:"testing",Routines:"routine",Competitions:"competition",More:"more"};
const short:Record<string,string>={"My Groups":"Groups",Planning:"Plan",Training:"Train",Testing:"Test",Competitions:"Compete"};
export function AppShell({children,organisationName,displayName,access}:Props){
 const pathname=usePathname(),navigation=primaryNavigation(access).filter(x=>x.enabled),phone=access.canUseCoachingWorkspace?navigation.filter(x=>["Home","My Groups","Planning","Training","More"].includes(x.label)):navigation;
 const roles=[...(access.isAdministrator?["Administrator"]:[]),...access.coachingRoles.map(coachingRoleLabel)],active=(href:string)=>href==="/dashboard"?pathname==="/dashboard":pathname===href||pathname.startsWith(href+"/");
 const links=(items:typeof navigation,cls:string)=>items.map(item=><a key={item.href} href={item.href} aria-current={active(item.href)?"page":undefined} className={cls+(active(item.href)?" nav-active":"")}><NavIcon name={icons[item.label]??"more"}/><span>{short[item.label]??item.label}</span></a>);
 return <div className="app-shell"><div className="app-frame"><aside className="app-sidebar"><div className="app-sidebar-inner"><a href="/dashboard" className="brand-lockup"><ViaformMark/><span><strong>VIAFORM</strong></span></a><div className="sidebar-identity"><small>COACHING AS</small><strong>{displayName}</strong><span>{roles.join(" · ")}</span></div><nav className="sidebar-nav">{links(navigation,"nav-link")}</nav><a href="/appearance" className="sidebar-profile-link">Appearance</a></div></aside><div className="app-content"><header className="app-banner"><a href="/dashboard" className="app-banner-brand"><ViaformMark/><span className="app-banner-wordmark">VIAFORM</span></a><div className="app-banner-image" aria-hidden="true"/><div className="app-banner-tools"><BannerThemeIndicator/><div className="banner-identity"><strong>{displayName}</strong><small>{roles.join(" · ")}</small></div><form action={signOut}><button className="signout-button">Sign out</button></form></div></header><main className="content-main">{children}</main></div></div>{phone.length>1&&<nav className="phone-bottom-nav">{links(phone,"mobile-nav-link")}</nav>}{navigation.length>1&&<nav className="tablet-bottom-nav">{links(navigation,"mobile-nav-link")}</nav>}</div>
}