"use client";
import {useMemo,useState,useTransition,type ReactNode} from "react";
import {resetHomeWidgetLayout,saveHomeWidgetLayout} from "@/app/actions/preferences";
type Widget={id:string;title:string;content:ReactNode;wide?:boolean};
export type WidgetLayout={order:string[];hidden:string[];wide:string[]};
export function OverviewWidgets({widgets,initialLayout}:{widgets:Widget[];initialLayout?:WidgetLayout|null}){
 const ids=useMemo(()=>widgets.map(w=>w.id),[widgets]),normalise=(layout?:WidgetLayout|null):WidgetLayout=>{const supplied=(layout?.order??[]).filter(x=>ids.includes(x)),defaultWide=widgets.filter(w=>w.wide).map(w=>w.id);return {order:[...supplied,...ids.filter(x=>!supplied.includes(x))],hidden:(layout?.hidden??[]).filter(x=>ids.includes(x)),wide:layout?(layout.wide??[]).filter(x=>ids.includes(x)):defaultWide}};
 const [editing,setEditing]=useState(false),[saved,setSaved]=useState<WidgetLayout>(()=>normalise(initialLayout)),[pending,startTransition]=useTransition();
 const persist=(next:WidgetLayout)=>{setSaved(next);startTransition(()=>saveHomeWidgetLayout(next))};
 const map=new Map(widgets.map(w=>[w.id,w])),visible=saved.order.filter(id=>!saved.hidden.includes(id)).map(id=>map.get(id)).filter(Boolean) as Widget[],hidden=saved.order.filter(id=>saved.hidden.includes(id)).map(id=>map.get(id)).filter(Boolean) as Widget[];
 const move=(id:string,d:number)=>{const o=[...saved.order],i=o.indexOf(id),j=i+d;if(i<0||j<0||j>=o.length)return;[o[i],o[j]]=[o[j],o[i]];persist({...saved,order:o})};
 const hide=(id:string)=>persist({...saved,hidden:saved.hidden.includes(id)?saved.hidden.filter(x=>x!==id):[...saved.hidden,id]});
 const widen=(id:string)=>persist({...saved,wide:saved.wide.includes(id)?saved.wide.filter(x=>x!==id):[...saved.wide,id]});
 const reset=()=>{setSaved(normalise(null));startTransition(()=>resetHomeWidgetLayout())};
 return <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold">Overview</p><div className="flex items-center gap-3"><span className="text-xs text-[var(--muted)]">{pending?"Saving…":"Saved"}</span><button type="button" onClick={()=>setEditing(x=>!x)} className="rounded-xl border border-[var(--border)] px-3 py-2 text-sm font-semibold">{editing?"Done":"Arrange overview"}</button></div></div>
 {editing&&<div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-dashed border-[var(--border)] p-3 text-xs text-[var(--muted)]"><span>Layout</span><button type="button" className="font-semibold" onClick={reset}>Reset default</button></div>}
 <div className="grid gap-4 lg:grid-cols-2">{visible.map((w,i)=>{const wide=saved.wide.includes(w.id);return <div key={w.id} className={wide?"lg:col-span-2":""}>{editing&&<div className="mb-1 flex flex-wrap items-center justify-between gap-2 rounded-t-xl border border-b-0 border-[var(--border)] px-3 py-2 text-xs"><strong>{w.title}</strong><span className="flex gap-2"><button type="button" disabled={i===0||pending} onClick={()=>move(w.id,-1)}>←</button><button type="button" disabled={i===visible.length-1||pending} onClick={()=>move(w.id,1)}>→</button><button type="button" disabled={pending} onClick={()=>widen(w.id)}>{wide?"Standard":"Wide"}</button><button type="button" disabled={pending} onClick={()=>hide(w.id)}>Hide</button></span></div>}{w.content}</div>})}</div>
 {editing&&hidden.length>0&&<div className="mt-4 flex flex-wrap gap-2 text-sm"><span className="text-[var(--muted)]">Hidden:</span>{hidden.map(w=><button type="button" disabled={pending} key={w.id} onClick={()=>hide(w.id)} className="font-semibold">+ {w.title}</button>)}</div>}</section>;
}