import {prisma} from "@/app/lib/prisma";
const day=(d:Date)=>new Intl.DateTimeFormat("en-IE",{weekday:"short",day:"numeric",month:"short"}).format(d);
const fullDate=(d:Date)=>new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",year:"numeric"}).format(d);
const apparatus:Record<string,string>={VAULT:"Vault",BARS:"Uneven Bars",UNEVEN_BARS:"Uneven Bars",BEAM:"Balance Beam",BALANCE_BEAM:"Balance Beam",FLOOR:"Floor Exercise",FLOOR_EXERCISE:"Floor Exercise",PHYSICAL_PREPARATION:"Physical preparation"};
export async function PortalGymnastView({gymnastId,organisationId,audience}:{gymnastId:string;organisationId:string;audience:"ATHLETE"|"GUARDIAN"}){
 const gymnast=await prisma.gymnast.findFirst({where:{id:gymnastId,organisationId},select:{id:true,name:true,programmeAssignments:{select:{programme:{select:{name:true}},stage:{select:{name:true}}}},rulesetAssignments:{select:{program:{select:{name:true}},level:{select:{name:true}}}}}});if(!gymnast)return null;
 const now=new Date();
 const [sessions,evidence,tests,routines,competitions]=await Promise.all([
  prisma.trainingSession.findMany({where:{organisationId,sessionDate:{gte:now},gymnasts:{some:{gymnastId}}},select:{id:true,title:true,sessionDate:true,startTime:true,endTime:true,trainingGroup:{select:{name:true}}},orderBy:[{sessionDate:"asc"},{startTime:"asc"}],take:6}),
  prisma.trainingEvidence.findMany({where:{gymnastId,session:{organisationId}},select:{id:true,outcome:true,recordedAt:true,block:{select:{apparatus:true,title:true}},session:{select:{title:true,sessionDate:true}}},orderBy:{recordedAt:"desc"},take:30}),
  prisma.testingResult.findMany({where:{gymnastId,session:{organisationId}},select:{id:true,numberValue:true,recordedAt:true,metric:{select:{name:true,unit:true}},session:{select:{name:true,testedAt:true}}},orderBy:{recordedAt:"desc"},take:6}),
  prisma.gymnastRoutine.findMany({where:{gymnastId,status:"ACTIVE"},select:{id:true,name:true,apparatus:true,purpose:true},orderBy:{updatedAt:"desc"}}),
  prisma.competitionEntry.findMany({where:{gymnastId,event:{organisationId}},select:{id:true,status:true,event:{select:{name:true,eventDate:true}},apparatusPlans:{select:{apparatus:true,performance:{select:{status:true,finalScore:true,rank:true}}}}},orderBy:{updatedAt:"desc"},take:5})
 ]);
 const programme=gymnast.programmeAssignments[0],rules=gymnast.rulesetAssignments[0],counts=evidence.reduce((a,x)=>{if(x.outcome==="MADE")a.made++;if(x.outcome==="MISSED")a.missed++;if(x.outcome==="SPOTTED")a.spotted++;return a},{made:0,missed:0,spotted:0});
 const card="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm";
 return <div>
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[var(--accent-strong)]">{audience==="ATHLETE"?"My training, goals and progress":"Athlete view"}</p><h1 className="mt-1 text-3xl font-semibold">{gymnast.name}</h1></div>{audience==="GUARDIAN"&&<span className="rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 py-1 text-xs text-[var(--muted)]">Parent / guardian view</span>}</div>
  <section id="training" className="scroll-mt-24 pt-8"><div><p className="text-sm font-semibold text-[var(--muted)]">{audience==="ATHLETE"?"My Training":"Training"}</p><h2 className="mt-1 text-2xl font-semibold">Coming up</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2">{sessions.map(s=><article key={s.id} className={card}><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">{day(s.sessionDate)} · {s.startTime}–{s.endTime}</p><h3 className="mt-2 font-semibold">{s.title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{s.trainingGroup.name}</p></article>)}{!sessions.length&&<p className="rounded-2xl border border-dashed border-[var(--border)] p-5 text-sm text-[var(--muted)]">No upcoming assigned training sessions are currently shown.</p>}</div></section>
  <section id="goals" className="scroll-mt-24 pt-9"><p className="text-sm font-semibold text-[var(--muted)]">{audience==="ATHLETE"?"My Goals":"Current pathway"}</p><h2 className="mt-1 text-2xl font-semibold">What I’m working towards</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">This is the shared pathway context already held in Viaform. Internal coaching strategy and coach-only notes are not shown here.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><article className={card}><p className="text-xs text-[var(--muted)]">Programme</p><strong className="mt-2 block">{programme?.programme.name??"No programme assigned"}</strong><p className="mt-1 text-sm text-[var(--muted)]">{programme?.stage?.name??"No stage recorded"}</p></article><article className={card}><p className="text-xs text-[var(--muted)]">Competition level</p><strong className="mt-2 block">{rules?.program.name??"No ruleset assigned"}</strong><p className="mt-1 text-sm text-[var(--muted)]">{rules?.level?.name??"No level recorded"}</p></article><article className={card}><p className="text-xs text-[var(--muted)]">Current routines</p><strong className="mt-2 block">{routines.length}</strong><p className="mt-1 text-sm text-[var(--muted)]">{routines.length?routines.map(r=>apparatus[r.apparatus]??r.apparatus).join(" · "):"No active routine plans"}</p></article></div>{routines.length>0&&<div className="mt-3 flex flex-wrap gap-2">{routines.map(r=><span key={r.id} className="rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm">{apparatus[r.apparatus]??r.apparatus} · {r.name}</span>)}</div>}</section>
  <section id="progress" className="scroll-mt-24 pt-9"><p className="text-sm font-semibold text-[var(--muted)]">{audience==="ATHLETE"?"My Progress":"Progress"}</p><h2 className="mt-1 text-2xl font-semibold">Evidence over time</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Results are evidence, not an automatic judgement of progress or readiness.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><article className={card}><p className="text-xs text-[var(--muted)]">Recent observations</p><strong className="mt-2 block text-2xl">{evidence.length}</strong></article><article className={card}><p className="text-xs text-[var(--muted)]">Made</p><strong className="mt-2 block text-2xl">{counts.made}</strong></article><article className={card}><p className="text-xs text-[var(--muted)]">Spotted / missed</p><strong className="mt-2 block text-2xl">{counts.spotted} / {counts.missed}</strong></article></div>
   <div className="mt-5 grid gap-5 lg:grid-cols-2"><article className={card}><h3 className="font-semibold">Recent testing</h3><div className="mt-3 grid gap-3">{tests.map(t=><div key={t.id} className="border-t border-[var(--border)] pt-3 first:border-0 first:pt-0"><div className="flex justify-between gap-3"><strong className="text-sm">{t.metric.name}</strong><span className="text-xs text-[var(--muted)]">{fullDate(t.recordedAt)}</span></div><p className="mt-1 text-sm">{t.numberValue}{t.metric.unit?" "+t.metric.unit:""}</p></div>)}{!tests.length&&<p className="text-sm text-[var(--muted)]">No testing results recorded yet.</p>}</div></article><article className={card}><h3 className="font-semibold">Competition record</h3><div className="mt-3 grid gap-3">{competitions.map(e=><div key={e.id} className="border-t border-[var(--border)] pt-3 first:border-0 first:pt-0"><div className="flex justify-between gap-3"><strong className="text-sm">{e.event.name}</strong><span className="text-xs text-[var(--muted)]">{fullDate(e.event.eventDate)}</span></div><div className="mt-2 flex flex-wrap gap-2">{e.apparatusPlans.map(p=><span key={p.apparatus} className="rounded-full bg-[var(--surface-soft)] px-2 py-1 text-xs">{apparatus[p.apparatus]??p.apparatus}{p.performance?.finalScore!=null?" · "+p.performance.finalScore.toFixed(3):""}{p.performance?.rank!=null?" · #"+p.performance.rank:""}</span>)}</div></div>)}{!competitions.length&&<p className="text-sm text-[var(--muted)]">No competition record yet.</p>}</div></article></div>
  </section>
 </div>
}