"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {saveVideoAnalysis} from "@/app/actions/video";

type Mark={type:"line"|"arrow"|"rect"|"circle"|"angle"|"free";points:number[]};
export function VideoAnalysisWorkspace({assetId}:{assetId:string}){
 const video=useRef<HTMLVideoElement>(null),compare=useRef<HTMLVideoElement>(null);
 const [src,setSrc]=useState(""),[compareSrc,setCompareSrc]=useState(""),[rate,setRate]=useState(1),[mode,setMode]=useState<"single"|"side"|"overlay">("single"),[tool,setTool]=useState<Mark["type"]>("line"),[marks,setMarks]=useState<Mark[]>([]),[draft,setDraft]=useState<number[]>([]),[time,setTime]=useState(0),[start,setStart]=useState<number|null>(null),[end,setEnd]=useState<number|null>(null),[loop,setLoop]=useState(false),[opacity,setOpacity]=useState(.5),[zoom,setZoom]=useState(1);
 useEffect(()=>()=>{if(src)URL.revokeObjectURL(src);if(compareSrc)URL.revokeObjectURL(compareSrc)},[src,compareSrc]);
 useEffect(()=>{if(video.current)video.current.playbackRate=rate;if(compare.current)compare.current.playbackRate=rate},[rate]);
 const frame=(d:number)=>{if(video.current){video.current.pause();video.current.currentTime=Math.max(0,video.current.currentTime+d/30)}};
 const click=(e:React.MouseEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect(),p=[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height];const need=tool==="angle"?6:4;const next=[...draft,...p];if(next.length>=need){setMarks(m=>[...m,{type:tool,points:next}]);setDraft([])}else setDraft(next)};
 const angle=(p:number[])=>{const [ax,ay,bx,by,cx,cy]=p;const u=[ax-bx,ay-by],v=[cx-bx,cy-by];const dot=u[0]*v[0]+u[1]*v[1],mag=Math.hypot(...u)*Math.hypot(...v);return mag?Math.acos(Math.max(-1,Math.min(1,dot/mag)))*180/Math.PI:0};
 const svgMarks=useMemo(()=>marks.map((m,i)=>{const p=m.points.map((x,j)=>x*(j%2?100:100));if(m.type==="angle")return <g key={i}><polyline points={p[0]+","+p[1]+" "+p[2]+","+p[3]+" "+p[4]+","+p[5]} fill="none" stroke="currentColor" strokeWidth="1"/><text x={p[2]+2} y={p[3]-2} fontSize="4" fill="currentColor">{angle(m.points).toFixed(1)}°</text></g>;if(m.type==="rect")return <rect key={i} x={Math.min(p[0],p[2])} y={Math.min(p[1],p[3])} width={Math.abs(p[2]-p[0])} height={Math.abs(p[3]-p[1])} fill="none" stroke="currentColor"/>;if(m.type==="circle")return <ellipse key={i} cx={(p[0]+p[2])/2} cy={(p[1]+p[3])/2} rx={Math.abs(p[2]-p[0])/2} ry={Math.abs(p[3]-p[1])/2} fill="none" stroke="currentColor"/>;return <line key={i} x1={p[0]} y1={p[1]} x2={p[2]} y2={p[3]} stroke="currentColor" strokeWidth="1"/>}),[marks]);
 const load=(f:File|null,set:(s:string)=>void)=>{if(f)set(URL.createObjectURL(f))};
 return <div className="grid gap-4">
  <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4">
   <div className="flex flex-wrap gap-2 text-sm"><label className="rounded-lg border border-[var(--border)] px-3 py-2 font-semibold">Load video<input type="file" accept="video/*" capture="environment" className="hidden" onChange={e=>load(e.target.files?.[0]??null,setSrc)}/></label><label className="rounded-lg border border-[var(--border)] px-3 py-2 font-semibold">Comparison video<input type="file" accept="video/*" className="hidden" onChange={e=>load(e.target.files?.[0]??null,setCompareSrc)}/></label><select value={mode} onChange={e=>setMode(e.target.value as typeof mode)} className="rounded-lg border border-[var(--border)] px-2"><option value="single">Single</option><option value="side">Side by side</option><option value="overlay">Overlay</option></select></div>
   <div className={mode==="side"?"mt-4 grid gap-3 md:grid-cols-2":"relative mt-4 overflow-hidden rounded-xl bg-black"}>
    <div className="relative" style={{transform:"scale("+zoom+")"}}><video ref={video} src={src||undefined} controls className="w-full" onTimeUpdate={e=>{const t=e.currentTarget.currentTime;setTime(t);if(loop&&end!==null&&start!==null&&t>=end)e.currentTarget.currentTime=start}}/><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full" onClick={click}>{svgMarks}</svg></div>
    {mode==="side"&&<video ref={compare} src={compareSrc||undefined} controls className="w-full"/>}
    {mode==="overlay"&&compareSrc&&<video ref={compare} src={compareSrc} className="pointer-events-none absolute inset-0 h-full w-full object-contain" style={{opacity}}/>}
   </div>
   {!src&&<p className="mt-3 text-sm text-[var(--muted)]">Choose or capture a video on this device. Footage stays local to the browser in this version; saved Viaform analysis stores the coaching metadata and annotations, not the video bytes.</p>}
   <div className="mt-4 flex flex-wrap gap-2 text-sm"><button type="button" onClick={()=>frame(-1)} className="rounded-lg border px-3 py-2">← frame</button><button type="button" onClick={()=>frame(1)} className="rounded-lg border px-3 py-2">frame →</button><select value={rate} onChange={e=>setRate(Number(e.target.value))} className="rounded-lg border px-2"><option value=".25">0.25×</option><option value=".5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select><button type="button" onClick={()=>setStart(time)} className="rounded-lg border px-3 py-2">Range start</button><button type="button" onClick={()=>setEnd(time)} className="rounded-lg border px-3 py-2">Range end</button><button type="button" onClick={()=>setLoop(x=>!x)} className="rounded-lg border px-3 py-2">Loop {loop?"on":"off"}</button></div>
   <div className="mt-3 flex flex-wrap items-center gap-2 text-sm"><span>Draw:</span>{(["line","arrow","rect","circle","angle"] as const).map(t=><button type="button" key={t} onClick={()=>{setTool(t);setDraft([])}} className="rounded-lg border px-3 py-2">{t}</button>)}<button type="button" onClick={()=>{setMarks([]);setDraft([])}} className="rounded-lg border px-3 py-2">Clear</button><label>Zoom <input type="range" min="1" max="3" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label>{mode==="overlay"&&<label>Opacity <input type="range" min="0" max="1" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label>}</div>
  </div>
  <form action={saveVideoAnalysis} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5">
   <input type="hidden" name="videoAssetId" value={assetId}/><input type="hidden" name="timestampSeconds" value={time}/><input type="hidden" name="rangeStartSeconds" value={start??""}/><input type="hidden" name="rangeEndSeconds" value={end??""}/><input type="hidden" name="playbackRate" value={rate}/><input type="hidden" name="zoom" value={zoom}/><input type="hidden" name="comparisonMode" value={mode}/><input type="hidden" name="overlayOpacity" value={opacity}/><input type="hidden" name="annotationJson" value={JSON.stringify(marks)}/>
   <input name="title" placeholder="Analysis title" className="rounded-lg border px-3 py-2"/><input name="technicalTags" placeholder="Technical tags, comma separated" className="rounded-lg border px-3 py-2"/><textarea name="observation" placeholder="Timestamped coaching observation" className="min-h-24 rounded-lg border px-3 py-2"/><button className="rounded-lg border px-3 py-2 font-semibold">Save current analysis</button>
   <p className="text-xs text-[var(--muted)]">Saves the current timestamp, range, playback rate, zoom, comparison mode, overlay opacity and drawings/angle measurements with the coaching observation.</p>
  </form>
 </div>
}
