"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {saveVideoAnalysis,updateVideoAssetMetadata} from "@/app/actions/video";
type Mark={type:"line"|"arrow"|"rect"|"circle"|"angle"|"free";points:number[]};
export function VideoAnalysisWorkspace({assetId}:{assetId:string}){
 const video=useRef<HTMLVideoElement>(null),compare=useRef<HTMLVideoElement>(null),drawing=useRef(false);
 const [src,setSrc]=useState(""),[compareSrc,setCompareSrc]=useState(""),[rate,setRate]=useState(1),[mode,setMode]=useState<"single"|"side"|"overlay">("single"),[tool,setTool]=useState<Mark["type"]>("line"),[marks,setMarks]=useState<Mark[]>([]),[draft,setDraft]=useState<number[]>([]),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[start,setStart]=useState<number|null>(null),[end,setEnd]=useState<number|null>(null),[loop,setLoop]=useState(false),[opacity,setOpacity]=useState(.5),[zoom,setZoom]=useState(1),[panX,setPanX]=useState(0),[panY,setPanY]=useState(0),[offset,setOffset]=useState(0),[alignX,setAlignX]=useState(0),[alignY,setAlignY]=useState(0),[blend,setBlend]=useState<"normal"|"difference">("normal");
 useEffect(()=>()=>{if(src)URL.revokeObjectURL(src);if(compareSrc)URL.revokeObjectURL(compareSrc)},[src,compareSrc]);useEffect(()=>{if(video.current)video.current.playbackRate=rate;if(compare.current)compare.current.playbackRate=rate},[rate]);
 const seek=(t:number)=>{if(video.current){const n=Math.max(0,Math.min(duration||Infinity,t));video.current.currentTime=n;setTime(n)}};const frame=(d:number)=>{video.current?.pause();seek(time+d/30)};
 const point=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();return[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]};
 const down=(e:React.PointerEvent<SVGSVGElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);if(tool==="free"){drawing.current=true;setDraft(p)}else{const need=tool==="angle"?6:4,next=[...draft,...p];if(next.length>=need){setMarks(m=>[...m,{type:tool,points:next}]);setDraft([])}else setDraft(next)}};
 const move=(e:React.PointerEvent<SVGSVGElement>)=>{if(tool==="free"&&drawing.current)setDraft(x=>[...x,...point(e)])};const up=()=>{if(tool==="free"&&drawing.current&&draft.length>=4)setMarks(m=>[...m,{type:"free",points:draft}]);drawing.current=false;setDraft([])};
 const angle=(p:number[])=>{const[ax,ay,bx,by,cx,cy]=p,u=[ax-bx,ay-by],v=[cx-bx,cy-by],mag=Math.hypot(...u)*Math.hypot(...v);return mag?Math.acos(Math.max(-1,Math.min(1,(u[0]*v[0]+u[1]*v[1])/mag)))*180/Math.PI:0};
 const render=(m:Mark,i:number)=>{const p=m.points.map(x=>x*100);if(m.type==="free")return <polyline key={i} points={Array.from({length:p.length/2},(_,j)=>p[j*2]+","+p[j*2+1]).join(" ")} fill="none" stroke="currentColor" strokeWidth="1"/>;
 if(m.type==="angle")return <g key={i}><polyline points={p[0]+","+p[1]+" "+p[2]+","+p[3]+" "+p[4]+","+p[5]} fill="none" stroke="currentColor"/><circle cx={p[2]} cy={p[3]} r="1.2" fill="currentColor"/><text x={p[2]+2} y={p[3]-2} fontSize="4" fill="currentColor">{angle(m.points).toFixed(1)}°</text></g>;
 if(m.type==="rect")return <rect key={i} x={Math.min(p[0],p[2])} y={Math.min(p[1],p[3])} width={Math.abs(p[2]-p[0])} height={Math.abs(p[3]-p[1])} fill="none" stroke="currentColor"/>;
 if(m.type==="circle")return <ellipse key={i} cx={(p[0]+p[2])/2} cy={(p[1]+p[3])/2} rx={Math.abs(p[2]-p[0])/2} ry={Math.abs(p[3]-p[1])/2} fill="none" stroke="currentColor"/>;
 return <line key={i} x1={p[0]} y1={p[1]} x2={p[2]} y2={p[3]} stroke="currentColor" markerEnd={m.type==="arrow"?"url(#arrow)":undefined}/>};
 const load=async(f:File|null,set:(s:string)=>void,primary=false)=>{if(!f)return;set(URL.createObjectURL(f));if(primary){const fd=new FormData();fd.set("videoAssetId",assetId);fd.set("fileName",f.name);fd.set("mimeType",f.type);await updateVideoAssetMetadata(fd)}};
 const sync=()=>{if(video.current&&compare.current){const next=Math.max(0,video.current.currentTime+offset);compare.current.currentTime=next;compare.current.playbackRate=rate}};
 const freeze=()=>video.current?.pause();
 return <div className="grid gap-4"><div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4">
 <div className="flex flex-wrap gap-2 text-sm"><label className="rounded-lg border px-3 py-2 font-semibold">Load / capture<input type="file" accept="video/*" capture="environment" className="hidden" onChange={e=>load(e.target.files?.[0]??null,setSrc,true)}/></label><label className="rounded-lg border px-3 py-2 font-semibold">Comparison video<input type="file" accept="video/*" className="hidden" onChange={e=>load(e.target.files?.[0]??null,setCompareSrc)}/></label><select value={mode} onChange={e=>setMode(e.target.value as typeof mode)} className="rounded-lg border px-2"><option value="single">Single</option><option value="side">Side by side</option><option value="overlay">Overlay</option></select>{mode!=="single"&&<button type="button" onClick={sync} className="rounded-lg border px-3 py-2 font-semibold">Sync comparison</button>}</div>
 <div className={mode==="side"?"mt-4 grid gap-3 md:grid-cols-2":"relative mt-4 overflow-hidden rounded-xl bg-black"}><div className="relative overflow-hidden"><div style={{transform:`translate(${panX}%,${panY}%) scale(${zoom})`,transformOrigin:"center"}}><video ref={video} src={src||undefined} controls className="w-full" onLoadedMetadata={e=>{setDuration(e.currentTarget.duration);const fd=new FormData();fd.set("videoAssetId",assetId);fd.set("durationSeconds",String(e.currentTarget.duration));void updateVideoAssetMetadata(fd)}} onTimeUpdate={e=>{const t=e.currentTarget.currentTime;setTime(t);if(loop&&end!==null&&start!==null&&t>=end)seek(start)}}/><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full touch-none" onPointerDown={down} onPointerMove={move} onPointerUp={up}><defs><marker id="arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 z" fill="currentColor"/></marker></defs>{marks.map(render)}{draft.length>=2&&tool==="free"&&render({type:"free",points:draft},-1)}</svg></div></div>
 {mode==="side"&&<video ref={compare} src={compareSrc||undefined} controls className="w-full"/>}{mode==="overlay"&&compareSrc&&<video ref={compare} src={compareSrc} className="pointer-events-none absolute h-full w-full object-contain" style={{opacity,left:alignX+"%",top:alignY+"%",mixBlendMode:blend}}/>}</div>
 {!src&&<p className="mt-3 text-sm text-[var(--muted)]">Choose or capture a video on this device. Footage stays local; Viaform saves coaching metadata and analysis rather than the video bytes.</p>}
 <div className="mt-4 grid gap-3"><div className="flex flex-wrap items-center gap-2 text-sm"><button type="button" onClick={()=>frame(-1)} className="rounded-lg border px-3 py-2">← frame</button><button type="button" onClick={freeze} className="rounded-lg border px-3 py-2">Freeze</button><button type="button" onClick={()=>frame(1)} className="rounded-lg border px-3 py-2">frame →</button><input aria-label="Precise time" type="number" min="0" max={duration||undefined} step=".01" value={time.toFixed(2)} onChange={e=>seek(Number(e.target.value))} className="w-24 rounded-lg border px-2 py-2"/><span>{duration?"/ "+duration.toFixed(2)+"s":""}</span><input aria-label="Precise scrubber" type="range" min="0" max={duration||1} step=".01" value={Math.min(time,duration||1)} onChange={e=>seek(Number(e.target.value))} className="min-w-40 flex-1"/></div>
 <div className="flex flex-wrap gap-2 text-sm"><select value={rate} onChange={e=>setRate(Number(e.target.value))} className="rounded-lg border px-2"><option value=".25">0.25×</option><option value=".5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select><button type="button" onClick={()=>setStart(time)} className="rounded-lg border px-3 py-2">Range start</button><button type="button" onClick={()=>setEnd(time)} className="rounded-lg border px-3 py-2">Range end</button><button type="button" onClick={()=>setLoop(x=>!x)} className="rounded-lg border px-3 py-2">Loop {loop?"on":"off"}</button></div></div>
 <div className="mt-3 flex flex-wrap items-center gap-2 text-sm"><span>Draw:</span>{(["line","arrow","rect","circle","angle","free"] as const).map(t=><button type="button" key={t} onClick={()=>{setTool(t);setDraft([])}} className="rounded-lg border px-3 py-2">{t}</button>)}<button type="button" onClick={()=>setMarks(m=>m.slice(0,-1))} className="rounded-lg border px-3 py-2">Undo mark</button><button type="button" onClick={()=>{setMarks([]);setDraft([])}} className="rounded-lg border px-3 py-2">Clear</button></div>
 <div className="mt-3 grid gap-2 text-sm md:grid-cols-2"><label>Zoom {zoom.toFixed(1)}× <input className="w-full" type="range" min="1" max="3" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Pan X {panX}% <input className="w-full" type="range" min="-50" max="50" value={panX} onChange={e=>setPanX(Number(e.target.value))}/></label><label>Pan Y {panY}% <input className="w-full" type="range" min="-50" max="50" value={panY} onChange={e=>setPanY(Number(e.target.value))}/></label>{mode!=="single"&&<label>Comparison offset {offset.toFixed(2)}s <input className="w-full" type="range" min="-5" max="5" step=".01" value={offset} onChange={e=>setOffset(Number(e.target.value))}/></label>}{mode==="overlay"&&<><label>Overlay opacity <input className="w-full" type="range" min="0" max="1" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><label>Overlay X <input className="w-full" type="range" min="-25" max="25" value={alignX} onChange={e=>setAlignX(Number(e.target.value))}/></label><label>Overlay Y <input className="w-full" type="range" min="-25" max="25" value={alignY} onChange={e=>setAlignY(Number(e.target.value))}/></label><label>Blend <select value={blend} onChange={e=>setBlend(e.target.value as typeof blend)} className="ml-2 rounded-lg border px-2 py-1"><option value="normal">Normal</option><option value="difference">Difference</option></select></label></>}</div></div>
 <form action={saveVideoAnalysis} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><input type="hidden" name="videoAssetId" value={assetId}/>{[["timestampSeconds",time],["rangeStartSeconds",start??""],["rangeEndSeconds",end??""],["playbackRate",rate],["zoom",zoom],["panX",panX],["panY",panY],["comparisonMode",mode],["comparisonOffset",offset],["overlayOpacity",opacity]].map(([n,v])=><input key={String(n)} type="hidden" name={String(n)} value={v}/>) }<input type="hidden" name="annotationJson" value={JSON.stringify(marks)}/><input name="title" placeholder="Analysis title" className="rounded-lg border px-3 py-2"/><input name="technicalTags" placeholder="Technical tags, comma separated" className="rounded-lg border px-3 py-2"/><textarea name="observation" placeholder="Timestamped coaching observation" className="min-h-24 rounded-lg border px-3 py-2"/><button className="rounded-lg border px-3 py-2 font-semibold">Save current analysis</button><p className="text-xs text-[var(--muted)]">Saves timing, range, playback, zoom/pan, comparison offset, overlay opacity and annotations. Overlay alignment/blend remain a viewing aid in this refinement.</p></form></div>}
