-- Vault coach-facing identity audit. FIG vault definitions and D-values remain authoritative and unchanged.
UPDATE "ViaformSkill" SET "name"='Front Handspring',"aliases"='["front handspring vault","handspring","fhs vault"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:1.00:a';
UPDATE "ViaformSkill" SET "name"='Handspring 1 1/2',"aliases"='["handspring 1.5","kim"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:1.03:a';
UPDATE "ViaformSkill" SET "name"='Korbut',"aliases"='["korbut","full on full off"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:1.31:a';
UPDATE "ViaformSkill" SET "name"='Yurchenko Timer',"aliases"='["yurchenko timer","roundoff back handspring on"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:1.40:a';
UPDATE "ViaformSkill" SET "name"='Chusovitina',"aliases"='["chusovitina","handspring front pike full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:2.22:a';
UPDATE "ViaformSkill" SET "name"='Evdokimova',"aliases"='["evdokimova","handspring front layout"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:2.30:a';
UPDATE "ViaformSkill" SET "name"='Wang',"aliases"='["wang","handspring front layout half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:2.31:a';
UPDATE "ViaformSkill" SET "name"='Chusovitina',"aliases"='["chusovitina","handspring front layout 1.5"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:2.33:a';
UPDATE "ViaformSkill" SET "name"='Yeo',"aliases"='["yeo","handspring front layout double full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:2.34:a';
UPDATE "ViaformSkill" SET "name"='Davydova',"aliases"='["davydova","full on front tuck"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:2.40:a';
UPDATE "ViaformSkill" SET "name"='Produnova',"aliases"='["produnova","handspring double front","double front vault"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:2.50:a';
UPDATE "ViaformSkill" SET "name"='Tsukahara Tuck',"aliases"='["tsuk tuck","tsukahara tuck","tourischeva"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:3.10:a';
UPDATE "ViaformSkill" SET "name"='Tsukahara Pike',"aliases"='["tsuk pike","tsukahara pike"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:3.20:a';
UPDATE "ViaformSkill" SET "name"='Tsukahara Layout',"aliases"='["tsuk layout","layout tsuk"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:3.30:a';
UPDATE "ViaformSkill" SET "name"='Zamolodchikova',"aliases"='["zamolodchikova","tsuk double full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:3.34:a';
UPDATE "ViaformSkill" SET "name"='Yurchenko Tuck',"aliases"='["yurchenko tuck","yurchenko tucked"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.10:a';
UPDATE "ViaformSkill" SET "name"='Yurchenko Pike',"aliases"='["yurchenko pike","yurchenko piked"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.20:a';
UPDATE "ViaformSkill" SET "name"='Yurchenko Layout',"aliases"='["yurchenko layout","yurchenko straight","layout yurchenko"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.30:a';
UPDATE "ViaformSkill" SET "name"='Yurchenko Full',"aliases"='["yurchenko full","yurchenko layout full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.32:a';
UPDATE "ViaformSkill" SET "name"='Yurchenko 1 1/2',"aliases"='["yurchenko 1.5","yurchenko one and a half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.33:a';
UPDATE "ViaformSkill" SET "name"='Yurchenko Double Full',"aliases"='["yurchenko double full","dty","baitova"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.34:a';
UPDATE "ViaformSkill" SET "name"='Amanar',"aliases"='["amanar","yurchenko 2.5"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.35:a';
UPDATE "ViaformSkill" SET "name"='Luconi',"aliases"='["luconi","three-quarter-on back tuck"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.40:a';
UPDATE "ViaformSkill" SET "name"='Biles',"aliases"='["biles","yurchenko double pike","double pike vault"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:4.62:a';
UPDATE "ViaformSkill" SET "name"='Ivantcheva',"aliases"='["ivantcheva","half-on front tuck"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.10:a';
UPDATE "ViaformSkill" SET "name"='Servente',"aliases"='["servente","half-on front tuck half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.11:a';
UPDATE "ViaformSkill" SET "name"='Khorkina',"aliases"='["khorkina","half-on front tuck 1.5"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.13:a';
UPDATE "ViaformSkill" SET "name"='Omelianchik',"aliases"='["omelianchik","half-on front pike"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.20:a';
UPDATE "ViaformSkill" SET "name"='Podkopayeva',"aliases"='["podkopayeva","half-on front pike half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.21:a';
UPDATE "ViaformSkill" SET "name"='Mustafina',"aliases"='["mustafina","half-on front full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.32:a';
UPDATE "ViaformSkill" SET "name"='Cheng',"aliases"='["cheng","half-on front 1.5"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.33:a';
UPDATE "ViaformSkill" SET "name"='Biles',"aliases"='["biles","half-on front double full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:VAULT:5.34:a';
