import { notFound } from "next/navigation";
import { AppShell } from "@/app/components/app-shell";
import { closeCoachHandoff, createCoachHandoff, updateHandoffCover } from "@/app/actions/handoffs";
import { requireAuthContext } from "@/app/lib/auth";
import { groupScopeWhere, gymnastScopeWhere } from "@/app/lib/coaching-scope";
import { prisma } from "@/app/lib/prisma";

export const dynamic="force-dynamic";
const date=(value:Date)=>new Intl.DateTimeFormat("en-IE",{dateStyle:"medium",timeStyle:"short"}).format(value);
type Snapshot={capturedAt?:string;groups?:string[];programme?:{name:string;stage:string|null}|null;ruleset?:{programme:string;level:string}|null;routines?:{id:string;name:string;apparatus:string;purpose:string}[];recentTraining?:{outcome:string;note:string|null;recordedAt:string}[];recentTesting?:{metric:string;value:number;unit:string;recordedAt:string}[]};
const snapshot=(value:string):Snapshot=>{try{return JSON.parse(value)}catch{return {}}};

export default async function HandoffsPage(){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)notFound();
 const [coaches,groups,gymnasts,handoffs]=await Promise.all([
  prisma.organisationMembership.findMany({where:{organisationId:c.organisation.id,isActive:true,id:{not:c.membership.id}},include:{user:true},orderBy:{joinedAt:"asc"}}),
  prisma.trainingGroup.findMany({where:groupScopeWhere(c.organisation.id,c.membership.id,c.access),include:{memberships:{include:{gymnast:true}}},orderBy:{name:"asc"}}),
  prisma.gymnast.findMany({where:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access),orderBy:{name:"asc"}}),
  prisma.coachHandoff.findMany({where:{organisationId:c.organisation.id,...(c.access.canViewAllCoachingData?{}:{OR:[{fromMembershipId:c.membership.id},{toMembershipId:c.membership.id}]})},include:{fromMembership:{include:{user:true}},toMembership:{include:{user:true}},trainingGroup:true,gymnasts:{include:{gymnast:true},orderBy:{gymnast:{name:"asc"}}}},orderBy:{createdAt:"desc"},take:40})
 ]);
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><a href="/more" className="workspace-back">← More</a><div className="workspace-hero"><div><p className="workspace-kicker">Coach handoff & cover</p><h1>Handoffs</h1><p className="workspace-meta">{handoffs.filter(h=>h.status==="ACTIVE").length} active</p></div></div>
  <details className="mt-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><summary className="cursor-pointer font-semibold">+ Create handoff</summary>
   <form action={createCoachHandoff} className="mt-4 grid gap-4">
    <div className="grid gap-3 md:grid-cols-3"><select name="toMembershipId" required className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="">Cover coach…</option>{coaches.map(m=><option key={m.id} value={m.id}>{m.user.displayName}</option>)}</select><select name="scope" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="SELECTED">Selected gymnasts</option><option value="GROUP">Whole group</option></select><input name="title" placeholder="Handoff title" className="rounded-xl border border-[var(--border)] px-3 py-3"/></div>
    <label className="text-sm font-semibold">Whole-group option<select name="trainingGroupId" className="mt-1 w-full rounded-xl border border-[var(--border)] px-3 py-3"><option value="">Choose group when Whole group is selected</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.memberships.length}</option>)}</select></label>
    <fieldset><legend className="text-sm font-semibold">Selected-gymnast option</legend><div className="mt-2 grid max-h-56 gap-2 overflow-auto rounded-xl border border-[var(--border)] p-3 sm:grid-cols-2 lg:grid-cols-3">{gymnasts.map(g=><label key={g.id} className="text-sm"><input type="checkbox" name="gymnastId" value={g.id} className="mr-2"/>{g.name}</label>)}</div></fieldset>
    <div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Starts<input name="startsAt" type="datetime-local" className="mt-1 w-full rounded-xl border border-[var(--border)] px-3 py-3"/></label><label className="text-sm font-semibold">Cover until<input name="endsAt" type="datetime-local" className="mt-1 w-full rounded-xl border border-[var(--border)] px-3 py-3"/></label></div>
    <input name="sharedFocus" placeholder="Shared cover focus" className="rounded-xl border border-[var(--border)] px-3 py-3"/><textarea name="sharedNote" placeholder="Shared practical context, priorities or restrictions" className="min-h-24 rounded-xl border border-[var(--border)] px-3 py-3"/>
    <details className="rounded-xl border border-[var(--border)] p-3"><summary className="cursor-pointer text-sm font-semibold">Optional gymnast-specific notes</summary><div className="mt-3 grid gap-2 md:grid-cols-2">{gymnasts.map(g=><label key={g.id} className="text-xs font-semibold">{g.name}<textarea name={"note_"+g.id} placeholder="Only if this gymnast needs extra context" className="mt-1 min-h-16 w-full rounded-lg border border-[var(--border)] p-2 text-sm"/></label>)}</div></details>
    <button className="w-fit rounded-xl bg-[var(--foreground)] px-4 py-3 text-sm font-semibold text-white">Create handoff</button>
   </form>
  </details>
  <div className="mt-8 grid gap-4">{handoffs.map(h=>{const recipient=h.toMembershipId===c.membership.id;return <details key={h.id} open={h.status==="ACTIVE"} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><summary className="cursor-pointer"><span className="font-semibold">{h.title}</span><span className="ml-2 text-xs text-[var(--muted)]">{h.fromMembership.user.displayName} → {h.toMembership.user.displayName} · {h.status} · {h.gymnasts.length} gymnast{h.gymnasts.length===1?"":"s"}</span></summary>
   <div className="mt-4 grid gap-3 md:grid-cols-3"><div><p className="text-xs font-semibold text-[var(--muted)]">Cover window</p><p className="mt-1 text-sm">{date(h.startsAt)}{h.endsAt?" → "+date(h.endsAt):" · open-ended"}</p></div><div><p className="text-xs font-semibold text-[var(--muted)]">Shared focus</p><p className="mt-1 text-sm">{h.sharedFocus||"No shared focus."}</p></div><div><p className="text-xs font-semibold text-[var(--muted)]">Shared note</p><p className="mt-1 text-sm">{h.sharedNote||"No shared note."}</p></div></div>
   <div className="mt-4 grid gap-3">{h.gymnasts.map(entry=>{const snap=snapshot(entry.contextSnapshot);return <article key={entry.id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{entry.gymnast.name}</h3><p className="mt-1 text-xs text-[var(--muted)]">{entry.individualNote||"No individual exception."}</p></div><span className="text-xs text-[var(--muted)]">Context frozen at handoff</span></div>
    <div className="mt-3 grid gap-2 text-xs text-[var(--muted)] md:grid-cols-3"><p><strong>Programme:</strong> {snap.programme?.name||"—"}{snap.programme?.stage?" · "+snap.programme.stage:""}</p><p><strong>Ruleset:</strong> {snap.ruleset?snap.ruleset.programme+" · "+snap.ruleset.level:"—"}</p><p><strong>Routines:</strong> {snap.routines?.map(r=>r.apparatus+" · "+r.name).join("; ")||"—"}</p></div>
    {recipient&&h.status==="ACTIVE"&&<form action={updateHandoffCover} className="mt-3 flex flex-wrap gap-2 border-t border-[var(--border)] pt-3"><input type="hidden" name="handoffId" value={h.id}/><input type="hidden" name="entryId" value={entry.id}/><input name="coverNote" defaultValue={entry.coverNote??""} placeholder="Return note for this gymnast" className="min-w-64 flex-1 rounded-lg border border-[var(--border)] px-3 py-2 text-sm"/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Save return note</button></form>}
    {!recipient&&entry.coverNote&&<p className="mt-3 text-sm"><strong>Cover return:</strong> {entry.coverNote}</p>}</article>})}</div>
   {recipient&&h.status==="ACTIVE"&&<form action={updateHandoffCover} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="handoffId" value={h.id}/><input name="returnNote" defaultValue={h.returnNote??""} placeholder="Overall cover return" className="min-w-64 flex-1 rounded-lg border border-[var(--border)] px-3 py-2 text-sm"/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Save overall return</button></form>}
   {h.fromMembershipId===c.membership.id&&h.status==="ACTIVE"&&<form action={closeCoachHandoff} className="mt-3"><input type="hidden" name="handoffId" value={h.id}/><button className="text-sm font-semibold">Close handoff</button></form>}
  </details>})}{!handoffs.length&&<p className="rounded-2xl border border-dashed border-[var(--border)] p-6 text-sm text-[var(--muted)]">No coach handoffs yet.</p>}</div>
 </section></AppShell>;
}
