-- Floor coach-facing identity audit, verified against the current FIG WAG 2025-2028 Floor table structure.
-- This changes Viaform display/search vocabulary only; FIG source descriptions remain untouched.
UPDATE "ViaformSkill" SET "name"='Split Leap',"aliases"='["split leap","split leap forward","split leap fwd"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.101:a';
UPDATE "ViaformSkill" SET "name"='Split Leap 1/2',"aliases"='["split leap half","split leap 180"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.201:a';
UPDATE "ViaformSkill" SET "name"='Split Leap Full',"aliases"='["split leap full","split leap 360"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.301:a';
UPDATE "ViaformSkill" SET "name"='Tour Jeté',"aliases"='["tour jete","fouette hop","fouette hop leg change"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.202:a';
UPDATE "ViaformSkill" SET "name"='Produnova',"aliases"='["produnova","tour jete half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.302:a';
UPDATE "ViaformSkill" SET "name"='Csillag',"aliases"='["csillag","tour jete straddle"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.302:b';
UPDATE "ViaformSkill" SET "name"='Gogean',"aliases"='["gogean","tour jete full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.402:a';
UPDATE "ViaformSkill" SET "name"='Tuck Jump to Split',"aliases"='["tuck jump split","tuck jump to split"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.103:a';
UPDATE "ViaformSkill" SET "name"='Forward Butterfly',"aliases"='["forward butterfly","butterfly forward"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.203:a';
UPDATE "ViaformSkill" SET "name"='Backward Butterfly',"aliases"='["backward butterfly","butterfly backward"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.203:b';
UPDATE "ViaformSkill" SET "name"='Straddle/Side Leap 1/4',"aliases"='["straddle leap quarter","side leap quarter"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.104:a';
UPDATE "ViaformSkill" SET "name"='Switch Wolf Leap',"aliases"='["switch wolf","change leg wolf leap"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.105:a';
UPDATE "ViaformSkill" SET "name"='Johnson',"aliases"='["johnson","switch side leap"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.204:a';
UPDATE "ViaformSkill" SET "name"='Switch Leap',"aliases"='["switch leap","change leg leap"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.205:a';
UPDATE "ViaformSkill" SET "name"='Frolova',"aliases"='["frolova","switch leap half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.304:a';
UPDATE "ViaformSkill" SET "name"='Johnson 1/2',"aliases"='["johnson half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.304:b';
UPDATE "ViaformSkill" SET "name"='Switch Ring Leap',"aliases"='["switch ring","switch leap ring"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.305:a';
UPDATE "ViaformSkill" SET "name"='Switch Leap Full',"aliases"='["switch full","switch leap full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.404:a';
UPDATE "ViaformSkill" SET "name"='Bulimar',"aliases"='["bulimar","johnson full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.404:b';
UPDATE "ViaformSkill" SET "name"='Sankova',"aliases"='["sankova","switch ring half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.405:a';
UPDATE "ViaformSkill" SET "name"='Pike Jump',"aliases"='["pike jump"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.106:a';
UPDATE "ViaformSkill" SET "name"='Straddle/Side Split Jump',"aliases"='["straddle jump","side split jump"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.107:a';
UPDATE "ViaformSkill" SET "name"='Sheep Jump',"aliases"='["sheep jump"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.206:a';
UPDATE "ViaformSkill" SET "name"='Straddle/Side Split Jump 1/2',"aliases"='["straddle jump half","side split jump half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.207:a';
UPDATE "ViaformSkill" SET "name"='Split Jump 1/2',"aliases"='["split jump half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.207:b';
UPDATE "ViaformSkill" SET "name"='Moerz',"aliases"='["moerz","pike jump full to front support"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.306:a';
UPDATE "ViaformSkill" SET "name"='Popa',"aliases"='["popa","straddle jump full","side split jump full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.307:a';
UPDATE "ViaformSkill" SET "name"='Split Jump Full',"aliases"='["split jump full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.307:b';
UPDATE "ViaformSkill" SET "name"='Straddle/Side Split Jump 1 1/2',"aliases"='["straddle jump 1.5","side split jump 1.5"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.407:a';
UPDATE "ViaformSkill" SET "name"='Split Jump 1 1/2',"aliases"='["split jump 1.5"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.407:b';
UPDATE "ViaformSkill" SET "name"='Split Jump',"aliases"='["split jump"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.109:a';
UPDATE "ViaformSkill" SET "name"='Stag Jump',"aliases"='["stag jump"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.109:b';
UPDATE "ViaformSkill" SET "name"='Stag Jump 1/2',"aliases"='["stag jump half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.109:c';
UPDATE "ViaformSkill" SET "name"='Sissone',"aliases"='["sissone"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.109:d';
UPDATE "ViaformSkill" SET "name"='Sissone Ring',"aliases"='["sissone ring","ring sissone"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.209:a';
UPDATE "ViaformSkill" SET "name"='Stag Ring Jump',"aliases"='["stag ring","stag ring jump"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.209:b';
UPDATE "ViaformSkill" SET "name"='Split Ring Jump',"aliases"='["split ring jump"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.209:c';
UPDATE "ViaformSkill" SET "name"='Split Ring Jump 1/2',"aliases"='["split ring jump half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.209:d';
UPDATE "ViaformSkill" SET "name"='Ring Leap',"aliases"='["ring leap","split ring leap"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.309:a';
UPDATE "ViaformSkill" SET "name"='Jurkowska-Kowalska',"aliases"='["jurkowska-kowalska","split ring jump full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.309:b';
UPDATE "ViaformSkill" SET "name"='Ferrari',"aliases"='["ferrari","tour jete ring half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:1.409:a';
UPDATE "ViaformSkill" SET "name"='Heron',"aliases"='["heron","double tuck 1.5","double back tuck 1.5"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:5.602:a';
UPDATE "ViaformSkill" SET "name"='Silivas',"aliases"='["silivas","double double tuck","double back tuck double full"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:5.802:a';
UPDATE "ViaformSkill" SET "name"='Biles II',"aliases"='["biles 2","biles ii","triple twisting double tuck"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:5.1002:a';
UPDATE "ViaformSkill" SET "name"='Biles',"aliases"='["biles","double layout half"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:5.703:a';
UPDATE "ViaformSkill" SET "name"='Chusovitina/Touzhikova',"aliases"='["chusovitina","touzhikova","full twisting double layout"]',"updatedAt"=CURRENT_TIMESTAMP WHERE "canonicalKey"='FIG:ELEMENT:FLOOR:5.803:a';
