import {AppShell} from "@/app/components/app-shell";
import {createTrainingSession,createTrainingWeekFromSchedule} from "@/app/actions/training-planning";
import {createMacrocycle,updateMacrocycle,setMacrocycleStatus,createMacrocyclePhase,updateMacrocyclePhase,deleteMacrocyclePhase,createTrainingPlan,updateTrainingPlan,setTrainingPlanStatus,assignSessionToTrainingPlan,removeSessionFromTrainingPlan,addTrainingPlanItem,updateTrainingPlanItem,removeTrainingPlanItem,buildSessionFromTrainingPlan,addMacrocycleFocusPeriod,removeMacrocycleFocusPeriod,updateMacrocycleFocusPeriod} from "@/app/actions/training-structure";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {groupScopeWhere,gymnastScopeWhere} from "@/app/lib/coaching-scope";
import {redirect} from "next/navigation";

export const dynamic="force-dynamic";
const day=(d:Date)=>d.toISOString().slice(0,10);
const control="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2";
const dateField="grid gap-1 text-xs font-semibold text-[var(--muted)]";

export default async function Planning({searchParams}:{searchParams:Promise<{view?:string}>}){
 const c=await requireAuthContext(),params=await searchParams,view=params.view==="plans"?"plans":params.view==="macrocycles"?"macrocycles":"sessions";
 if(!c.access.canUseCoachingWorkspace)redirect("/dashboard");
 const scope=groupScopeWhere(c.organisation.id,c.membership.id,c.access);
 const [groups,gymnasts,sessions,cycles,plans]=await Promise.all([
  prisma.trainingGroup.findMany({where:scope,include:{scheduleSlots:{orderBy:[{orderIndex:"asc"},{startTime:"asc"}]}},orderBy:{name:"asc"}}),
  prisma.gymnast.findMany({where:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access),include:{groups:{select:{trainingGroupId:true}}},orderBy:{name:"asc"}}),
  prisma.trainingSession.findMany({where:{organisationId:c.organisation.id,trainingGroup:scope,status:"PLANNED"},include:{trainingGroup:true,blocks:{select:{id:true,durationMin:true}}},orderBy:[{sessionDate:"asc"},{startTime:"asc"}],take:200}),
  prisma.macrocycle.findMany({where:{organisationId:c.organisation.id,...(c.access.canViewAllCoachingData?{}:{OR:[{groups:{some:{trainingGroup:scope}}},{gymnasts:{some:{gymnast:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)}}}]})},include:{groups:{include:{trainingGroup:{select:{name:true}}}},gymnasts:{include:{gymnast:{select:{name:true}}}},phases:{include:{periods:{orderBy:[{orderIndex:"asc"},{startDate:"asc"}]}},orderBy:[{orderIndex:"asc"},{startDate:"asc"}]},trainingPlans:{select:{id:true}}},orderBy:{startDate:"desc"}}),
  prisma.trainingPlan.findMany({where:{organisationId:c.organisation.id,trainingGroup:scope},include:{trainingGroup:{select:{name:true}},gymnast:{select:{name:true}},macrocycle:{select:{name:true}},items:{include:{gymnast:{select:{name:true}}},orderBy:{orderIndex:"asc"}},sessions:{select:{id:true,title:true,sessionDate:true,startTime:true,status:true},orderBy:{sessionDate:"asc"}}},orderBy:{startDate:"desc"}})
 ]);
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page">
  <div className="workspace-hero"><div><p className="workspace-kicker">Planning</p><h1>Planning</h1><p className="workspace-meta">{view==="sessions"?`${sessions.length} planned sessions`:view==="plans"?`${plans.filter(p=>p.status==="ACTIVE").length} active training plans`:`${cycles.filter(m=>m.status==="ACTIVE").length} active macrocycles`}</p></div></div>
  <nav className="groups-workspace-nav" aria-label="Planning views"><div className="workspace-tabs"><a href="/planning?view=sessions" className={view==="sessions"?"active":""}>Sessions</a><a href="/planning?view=plans" className={view==="plans"?"active":""}>Training plans</a><a href="/planning?view=macrocycles" className={view==="macrocycles"?"active":""}>Macrocycles</a></div></nav>

  {view==="sessions"&&<>
   <details className="management-panel mt-6"><summary>+ Plan sessions</summary><div className="management-grid"><section><h2>Build week</h2><form action={createTrainingWeekFromSchedule} className="mt-3 grid gap-2"><select name="groupId" required className={control}><option value="">Group…</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input name="weekStart" type="date" required className={control}/><button className="workspace-button">Create scheduled sessions</button></form></section><section><h2>Single session</h2><form action={createTrainingSession} className="mt-3 grid gap-2"><select name="groupId" required className={control}><option value="">Group…</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><input name="sessionDate" type="date" required className={control}/><input name="startTime" type="time" required className={control}/><input name="endTime" type="time" required className={control}/></div><input name="title" placeholder="Session title" className={control}/><input name="sessionIntent" placeholder="Session intent" className={control}/><textarea name="notes" placeholder="Notes" className={control}/><button className="workspace-button workspace-button-primary">Create session</button></form></section></div></details>
   <div className="mt-7 grid gap-5 lg:grid-cols-[1fr_300px]"><div><div className="section-heading"><h2>Planned sessions</h2><span>{sessions.length}</span></div><div className="mt-3 grid gap-3">{sessions.map(s=><a key={s.id} href={"/planning/"+s.id} className="workspace-row"><div><strong>{s.title}</strong><span>{s.trainingGroup.name} · {day(s.sessionDate)} · {s.startTime}–{s.endTime}</span>{s.sessionIntent&&<small>{s.sessionIntent}</small>}</div><em>{s.blocks.length} blocks</em></a>)}{!sessions.length&&<div className="empty-state">No sessions planned</div>}</div></div><aside><div className="section-heading"><h2>Weekly schedule</h2></div><div className="mt-3 grid gap-3">{groups.map(g=><div key={g.id} className="compact-card"><strong>{g.name}</strong><div className="mt-2 grid gap-1">{g.scheduleSlots.map(s=><span key={s.id}>{s.dayOfWeek.slice(0,3)} · {s.startTime}–{s.endTime}</span>)}{!g.scheduleSlots.length&&<span>No recurring times</span>}</div></div>)}</div></aside></div>
  </>}

  {view==="plans"&&<>
   <details className="management-panel mt-6"><summary>+ Create training plan</summary><form action={createTrainingPlan} className="workspace-form-grid sm:grid-cols-2"><input name="name" required maxLength={120} placeholder="Plan name" className={control}/><select name="scope" required className={control}><option value="">Plan for…</option><optgroup label="Groups">{groups.map(g=><option key={g.id} value={"GROUP:"+g.id}>{g.name}</option>)}</optgroup><optgroup label="Individual gymnasts">{gymnasts.flatMap(g=>g.groups.filter(link=>groups.some(group=>group.id===link.trainingGroupId)).map(link=><option key={g.id+link.trainingGroupId} value={"GYMNAST:"+g.id+":"+link.trainingGroupId}>{g.name} · {groups.find(group=>group.id===link.trainingGroupId)?.name}</option>))}</optgroup></select><p className="text-xs text-[var(--muted)]">Group plans may contain shared and gymnast specific work. Individual plans use the selected group for their sessions.</p><label className={dateField}>Start<input name="startDate" type="date" required className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required className={control}/></label><select name="macrocycleId" className={control}><option value="">No macrocycle</option>{cycles.filter(m=>m.status==="ACTIVE").map(m=><option key={m.id} value={m.id}>{m.name} · {[...m.groups.map(g=>g.trainingGroup.name),...m.gymnasts.map(g=>g.gymnast.name)].join(", ")}</option>)}</select><input name="focus" placeholder="Training focus" className={control}/><textarea name="notes" placeholder="Plan notes" className={control}/><button className="workspace-button workspace-button-primary">Create plan</button></form></details>
   <div className="mt-7 grid gap-4">{plans.map(p=><details key={p.id} className="management-panel"><summary>{p.name} · {p.gymnast?.name??p.trainingGroup.name} <small className="ml-2 text-[var(--muted)]">{day(p.startDate)} – {day(p.endDate)} · {p.items.length} work items · {p.sessions.length} sessions · {p.status.toLowerCase()}</small></summary><div className="p-5"><p className="text-sm text-[var(--muted)]">{p.focus||"No focus set"}{p.macrocycle?" · "+p.macrocycle.name:""} · session group: {p.trainingGroup.name}</p>{p.notes&&<p className="mt-2 text-sm">{p.notes}</p>}
    <h3 className="mt-5 text-sm font-semibold">Planned work</h3><div className="mt-2 grid gap-2">{p.items.map(item=><details key={item.id} className="rounded-xl border border-[var(--border)] p-3"><summary className="cursor-pointer text-sm font-semibold">{item.category.replaceAll("_"," ")} · {item.title}{item.gymnast?" · "+item.gymnast.name:" · shared"}{item.targetCount?" · target "+item.targetCount:""}</summary><form action={updateTrainingPlanItem} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="planId" value={p.id}/><input type="hidden" name="itemId" value={item.id}/><input name="title" required defaultValue={item.title} className={control}/><select name="category" defaultValue={item.category} className={control}>{["WARM_UP","APPARATUS","PHYSICAL_PREPARATION","CONDITIONING","ROUTINES","TESTING","OTHER"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select><select name="apparatus" defaultValue={item.apparatus??""} className={control}><option value="">No apparatus</option>{["VAULT","UNEVEN_BARS","BALANCE_BEAM","FLOOR_EXERCISE","PHYSICAL_PREPARATION"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select><select name="gymnastId" defaultValue={item.gymnastId??""} disabled={Boolean(p.gymnastId)} className={control}><option value="">{p.gymnastId?"Individual plan":"Shared with group"}</option>{gymnasts.filter(g=>g.groups.some(link=>link.trainingGroupId===p.trainingGroupId)).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input name="durationMin" type="number" min="1" max="480" defaultValue={item.durationMin??""} placeholder="Minutes" className={control}/><input name="targetCount" type="number" min="1" max="1000" defaultValue={item.targetCount??""} placeholder="Target repetitions" className={control}/><input name="notes" defaultValue={item.notes??""} placeholder="Drills or cues" className={control}/><button className="workspace-button">Save item</button></form><form action={removeTrainingPlanItem} className="mt-2"><input type="hidden" name="planId" value={p.id}/><input type="hidden" name="itemId" value={item.id}/><button className="text-xs text-[var(--muted)]">Remove item</button></form></details>)}{!p.items.length&&<p className="text-sm text-[var(--muted)]">Add warm-up, apparatus work, conditioning, or cool-down before building a session.</p>}</div>
    {p.status==="ACTIVE"&&<form action={addTrainingPlanItem} className="mt-4 grid gap-2 sm:grid-cols-2"><input type="hidden" name="planId" value={p.id}/><input name="title" required maxLength={160} placeholder="Work item or drill" className={control}/><select name="category" required className={control}>{["WARM_UP","APPARATUS","PHYSICAL_PREPARATION","CONDITIONING","ROUTINES","TESTING","OTHER"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select><select name="apparatus" className={control}><option value="">No apparatus</option>{["VAULT","UNEVEN_BARS","BALANCE_BEAM","FLOOR_EXERCISE","PHYSICAL_PREPARATION"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select><select name="gymnastId" className={control} defaultValue={p.gymnastId??""} disabled={Boolean(p.gymnastId)}><option value="">{p.gymnastId?"Individual plan":"Shared with group"}</option>{gymnasts.filter(g=>g.groups.some(link=>link.trainingGroupId===p.trainingGroupId)).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input name="durationMin" type="number" min="1" max="480" placeholder="Minutes (optional)" className={control}/><input name="targetCount" type="number" min="1" max="1000" placeholder="Target repetitions (optional)" className={control}/><input name="notes" placeholder="Drills, sequence, or coaching cues" className={control}/><button className="workspace-button">Add planned work</button></form>}
    {p.status==="ACTIVE"&&p.items.length>0&&<form action={buildSessionFromTrainingPlan} className="mt-6 grid gap-2 rounded-xl border border-[var(--border)] p-4 sm:grid-cols-2"><input type="hidden" name="planId" value={p.id}/><strong className="sm:col-span-2">Build a session from this plan</strong><label className={dateField}>Date<input name="sessionDate" type="date" required min={day(p.startDate)} max={day(p.endDate)} className={control}/></label><input name="title" placeholder="Session title (optional)" className={control}/><label className={dateField}>Start time<input name="startTime" type="time" required className={control}/></label><label className={dateField}>End time<input name="endTime" type="time" required className={control}/></label><button className="workspace-button workspace-button-primary sm:col-span-2">Create planned session</button></form>}
    <div className="mt-4 grid gap-2">{p.sessions.map(s=><div key={s.id} className="workspace-row"><a href={s.status==="PLANNED"?"/planning/"+s.id:"/training/"+s.id} className="text-sm font-semibold">{s.title} · {day(s.sessionDate)} · {s.startTime}</a>{s.status==="PLANNED"&&<form action={removeSessionFromTrainingPlan}><input type="hidden" name="planId" value={p.id}/><input type="hidden" name="sessionId" value={s.id}/><button className="text-xs text-[var(--muted)]">Remove</button></form>}</div>)}{!p.sessions.length&&<p className="text-sm text-[var(--muted)]">No sessions attached yet.</p>}</div>
    {p.status==="ACTIVE"&&!p.gymnastId&&<form action={assignSessionToTrainingPlan} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="planId" value={p.id}/><select name="sessionId" required className={control}><option value="">Add planned session…</option>{sessions.filter(s=>!p.gymnastId&&s.trainingGroupId===p.trainingGroupId&&!s.trainingPlanId&&s.sessionDate>=p.startDate&&s.sessionDate<=p.endDate).map(s=><option key={s.id} value={s.id}>{day(s.sessionDate)} · {s.title}</option>)}</select><button className="workspace-button">Add session</button></form>}
    <details className="mt-5"><summary className="cursor-pointer text-sm font-semibold">Edit plan</summary><form action={updateTrainingPlan} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="planId" value={p.id}/><input name="name" required maxLength={120} defaultValue={p.name} className={control}/><input name="focus" defaultValue={p.focus??""} placeholder="Focus" className={control}/><label className={dateField}>Start<input name="startDate" type="date" required defaultValue={day(p.startDate)} className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required defaultValue={day(p.endDate)} className={control}/></label><textarea name="notes" defaultValue={p.notes??""} placeholder="Notes" className={control}/><button className="workspace-button">Save plan</button></form><form action={setTrainingPlanStatus} className="mt-3"><input type="hidden" name="planId" value={p.id}/><input type="hidden" name="status" value={p.status==="ACTIVE"?"ARCHIVED":"ACTIVE"}/><button className="text-sm font-semibold text-[var(--muted)]">{p.status==="ACTIVE"?"Archive plan":"Reactivate plan"}</button></form></details>
   </div></details>)}{!plans.length&&<div className="empty-state">No training plans yet. Create one for a group or gymnast, then add planned work.</div>}</div>
  </>}

  {view==="macrocycles"&&<>
   <details className="management-panel mt-6"><summary>+ Create macrocycle</summary><form action={createMacrocycle} className="workspace-form-grid sm:grid-cols-2"><input name="name" required maxLength={120} placeholder="Macrocycle name" className={control}/><p className="text-xs text-[var(--muted)]">Choose one scope: a group or an individual gymnast.</p><select name="scope" required className={control}><option value="">Macrocycle for…</option><optgroup label="Groups">{groups.map(g=><option key={g.id} value={"GROUP:"+g.id}>{g.name}</option>)}</optgroup><optgroup label="Individual gymnasts">{gymnasts.map(g=><option key={g.id} value={"GYMNAST:"+g.id}>{g.name}</option>)}</optgroup></select><label className={dateField}>Start<input name="startDate" type="date" required className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required className={control}/></label><textarea name="notes" placeholder="Purpose and notes" className={control}/><button className="workspace-button workspace-button-primary">Create macrocycle</button></form></details>
   <div className="mt-7 grid gap-4">{cycles.map(m=><details key={m.id} className="management-panel"><summary>{m.name} · {[...m.groups.map(g=>g.trainingGroup.name),...m.gymnasts.map(g=>g.gymnast.name)].join(", ")||"Club"} <small className="ml-2 text-[var(--muted)]">{day(m.startDate)} – {day(m.endDate)} · {m.status.toLowerCase()}</small></summary><div className="p-5">{m.notes&&<p className="text-sm">{m.notes}</p>}<h2 className="mt-4 text-sm font-semibold">Phases</h2><div className="mt-2 grid gap-2">{m.phases.map(phase=><details key={phase.id} className="rounded-xl border border-[var(--border)] p-3"><summary className="cursor-pointer text-sm font-semibold">{phase.name} · {day(phase.startDate)} – {day(phase.endDate)}</summary><form action={updateMacrocyclePhase} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="macrocycleId" value={m.id}/><input type="hidden" name="phaseId" value={phase.id}/><input name="name" required maxLength={120} defaultValue={phase.name} className={control}/><input name="notes" defaultValue={phase.notes??""} placeholder="Notes" className={control}/><label className={dateField}>Start<input name="startDate" type="date" required defaultValue={day(phase.startDate)} className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required defaultValue={day(phase.endDate)} className={control}/></label><textarea name="goals" defaultValue={phase.goals??""} placeholder="Phase goals" className={control}/><input name="apparatusFocus" defaultValue={phase.apparatusFocus??""} placeholder="Apparatus focus" className={control}/><input name="conditioningFocus" defaultValue={phase.conditioningFocus??""} placeholder="Conditioning and flexibility" className={control}/><input name="artistryFocus" defaultValue={phase.artistryFocus??""} placeholder="Artistry and dance" className={control}/><button className="workspace-button">Save phase</button></form>
    <h3 className="mt-4 text-sm font-semibold">Focus periods</h3><div className="mt-2 grid gap-2">{phase.periods.map(period=><div key={period.id} className="rounded-lg border border-[var(--border)] p-3 text-xs"><strong>{period.name} · {day(period.startDate)} – {day(period.endDate)}</strong><p className="mt-1 text-[var(--muted)]">{[period.apparatusFocus,period.conditioningFocus,period.artistryFocus].filter(Boolean).join(" · ")}</p><details className="mt-2"><summary>Edit period</summary><form action={updateMacrocycleFocusPeriod} className="mt-2 grid gap-2 sm:grid-cols-2"><input type="hidden" name="phaseId" value={phase.id}/><input type="hidden" name="periodId" value={period.id}/><input name="name" required defaultValue={period.name} className={control}/><input name="apparatusFocus" defaultValue={period.apparatusFocus??""} placeholder="Apparatus focus" className={control}/><label className={dateField}>Start<input name="startDate" type="date" required min={day(phase.startDate)} max={day(phase.endDate)} defaultValue={day(period.startDate)} className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required min={day(phase.startDate)} max={day(phase.endDate)} defaultValue={day(period.endDate)} className={control}/></label><input name="conditioningFocus" defaultValue={period.conditioningFocus??""} placeholder="Conditioning" className={control}/><input name="artistryFocus" defaultValue={period.artistryFocus??""} placeholder="Artistry" className={control}/><input name="notes" defaultValue={period.notes??""} placeholder="Notes" className={control}/><button className="workspace-button">Save period</button></form></details><form action={removeMacrocycleFocusPeriod} className="mt-2"><input type="hidden" name="phaseId" value={phase.id}/><input type="hidden" name="periodId" value={period.id}/><button className="text-[var(--muted)]">Remove period</button></form></div>)}{!phase.periods.length&&<p className="text-xs text-[var(--muted)]">No shorter focus periods yet.</p>}</div>
    <form action={addMacrocycleFocusPeriod} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="phaseId" value={phase.id}/><input name="name" required maxLength={120} placeholder="Focus period name" className={control}/><input name="apparatusFocus" placeholder="Apparatus focus" className={control}/><label className={dateField}>Start<input name="startDate" type="date" required min={day(phase.startDate)} max={day(phase.endDate)} className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required min={day(phase.startDate)} max={day(phase.endDate)} className={control}/></label><input name="conditioningFocus" placeholder="Conditioning and flexibility" className={control}/><input name="artistryFocus" placeholder="Artistry and dance" className={control}/><input name="notes" placeholder="Additional notes" className={control}/><button className="workspace-button">Add focus period</button></form><form action={deleteMacrocyclePhase} className="mt-3"><input type="hidden" name="macrocycleId" value={m.id}/><input type="hidden" name="phaseId" value={phase.id}/><button className="text-xs text-[var(--muted)]">Remove phase</button></form></details>)}{!m.phases.length&&<p className="text-sm text-[var(--muted)]">No phases yet.</p>}</div>
    {m.status==="ACTIVE"&&<form action={createMacrocyclePhase} className="mt-4 grid gap-2 sm:grid-cols-2"><input type="hidden" name="macrocycleId" value={m.id}/><input name="name" required maxLength={120} placeholder="Phase name" className={control}/><input name="goals" placeholder="Phase goals" className={control}/><label className={dateField}>Start<input name="startDate" type="date" required min={day(m.startDate)} max={day(m.endDate)} className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required min={day(m.startDate)} max={day(m.endDate)} className={control}/></label><input name="apparatusFocus" placeholder="Apparatus focus" className={control}/><input name="conditioningFocus" placeholder="Conditioning and flexibility" className={control}/><input name="artistryFocus" placeholder="Artistry and dance" className={control}/><input name="notes" placeholder="Notes" className={control}/><button className="workspace-button">Add phase</button></form>}
    <details className="mt-5"><summary className="cursor-pointer text-sm font-semibold">Edit macrocycle</summary><form action={updateMacrocycle} className="mt-3 grid gap-2 sm:grid-cols-2"><input type="hidden" name="macrocycleId" value={m.id}/><input name="name" required maxLength={120} defaultValue={m.name} className={control}/><input name="notes" defaultValue={m.notes??""} placeholder="Purpose and notes" className={control}/><label className={dateField}>Start<input name="startDate" type="date" required defaultValue={day(m.startDate)} className={control}/></label><label className={dateField}>End<input name="endDate" type="date" required defaultValue={day(m.endDate)} className={control}/></label><button className="workspace-button">Save macrocycle</button></form><form action={setMacrocycleStatus} className="mt-3"><input type="hidden" name="macrocycleId" value={m.id}/><input type="hidden" name="status" value={m.status==="ACTIVE"?"ARCHIVED":"ACTIVE"}/><button className="text-sm font-semibold text-[var(--muted)]">{m.status==="ACTIVE"?"Archive macrocycle":"Reactivate macrocycle"}</button></form></details><p className="mt-4 text-xs text-[var(--muted)]">{m.trainingPlans.length} linked plans · phases appear in Calendar</p>
   </div></details>)}{!cycles.length&&<div className="empty-state">No macrocycles yet. Create one for a group or gymnast, then add phases.</div>}</div>
  </>}
 </section></AppShell>;
}
