import {notFound} from "next/navigation";
import {AppShell} from "@/app/components/app-shell";
import {createPortalAccess,resetPortalPassword,setPortalAccessActive} from "@/app/actions/portal-access";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
export const dynamic="force-dynamic";
const age=(dob:Date|null)=>dob?Math.floor((Date.now()-dob.getTime())/31557600000):null;
export default async function PortalAccessPage(){
 const c=await requireAuthContext();if(!c.access.canManagePeopleAndRoles)notFound();
 const [gymnasts,accesses]=await Promise.all([
  prisma.gymnast.findMany({where:{organisationId:c.organisation.id},orderBy:{name:"asc"},select:{id:true,name:true,dateOfBirth:true}}),
  prisma.athletePortalAccess.findMany({where:{organisationId:c.organisation.id},include:{user:true,gymnast:true},orderBy:[{status:"asc"},{createdAt:"desc"}]})
 ]);
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><a href="/people" className="workspace-back">← People & roles</a><div className="workspace-hero"><div><p className="workspace-kicker">Athlete & family access</p><h1>Linked accounts</h1><p className="workspace-meta">{accesses.filter(a=>a.status==="ACTIVE").length} active · {accesses.length} linked</p></div></div>
 <details className="mt-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><summary className="cursor-pointer font-semibold">+ Link athlete or guardian account</summary><p className="mt-2 text-xs leading-5 text-[var(--muted)]">For a new email, set an initial password of at least 10 characters. If the email already belongs to a Viaform user, the existing login is linked and its password is not changed.</p><form action={createPortalAccess} className="mt-4 grid gap-4"><div className="grid gap-3 md:grid-cols-2"><select name="gymnastId" required className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="">Gymnast…</option>{gymnasts.map(g=><option key={g.id} value={g.id}>{g.name}{age(g.dateOfBirth)!==null?" · age "+age(g.dateOfBirth):""}</option>)}</select><select name="relationship" required className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="ATHLETE">Athlete · own account</option><option value="GUARDIAN">Parent / guardian</option></select></div><div className="grid gap-3 md:grid-cols-3"><input name="displayName" required placeholder="Account holder name" className="rounded-xl border border-[var(--border)] px-3 py-3"/><input name="email" type="email" required placeholder="Email" className="rounded-xl border border-[var(--border)] px-3 py-3"/><input name="password" type="password" minLength={10} placeholder="Initial password for new account" className="rounded-xl border border-[var(--border)] px-3 py-3"/></div><button className="w-fit rounded-xl bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-white">Link account</button></form></details>
 <div className="mt-8 grid gap-4">{accesses.map(a=><article key={a.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{a.gymnast.name}</h2><p className="mt-1 text-sm">{a.relationship==="ATHLETE"?"Athlete account":"Parent / guardian"} · {a.user.displayName}</p><p className="mt-1 text-xs text-[var(--muted)]">{a.user.email}</p></div><span className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{a.status==="ACTIVE"?"Active":"Inactive"}</span></div><div className="mt-4 flex flex-wrap gap-3 border-t border-[var(--border)] pt-4"><form action={resetPortalPassword} className="flex flex-wrap gap-2"><input type="hidden" name="accessId" value={a.id}/><input name="password" type="password" minLength={10} required placeholder="New password" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm"/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Reset password</button></form><form action={setPortalAccessActive}><input type="hidden" name="accessId" value={a.id}/><input type="hidden" name="active" value={a.status==="ACTIVE"?"false":"true"}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">{a.status==="ACTIVE"?"Deactivate link":"Reactivate link"}</button></form></div></article>)}{!accesses.length&&<p className="rounded-2xl border border-dashed border-[var(--border)] p-6 text-sm text-[var(--muted)]">No athlete or guardian accounts are linked yet.</p>}</div></section></AppShell>
}