import {AppShell} from "@/app/components/app-shell";
import {createCalendarCompetition,createCalendarEvent,deleteCalendarEvent} from "@/app/actions/calendar";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {groupScopeWhere,gymnastScopeWhere} from "@/app/lib/coaching-scope";
export const dynamic="force-dynamic";
type ViewMode="year"|"month"|"week";
const parseDate=(v?:string)=>{const d=v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?new Date(v+"T00:00:00.000Z"):new Date();return Number.isNaN(d.getTime())?new Date():new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()))};
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x};
const addMonths=(d:Date,n:number)=>new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+n,1));
const addYears=(d:Date,n:number)=>new Date(Date.UTC(d.getUTCFullYear()+n,d.getUTCMonth(),Math.min(d.getUTCDate(),new Date(Date.UTC(d.getUTCFullYear()+n,d.getUTCMonth()+1,0)).getUTCDate())));
const startOfWeek=(d:Date)=>addDays(d,d.getUTCDay()===0?-6:1-d.getUTCDay());
const startOfMonthGrid=(d:Date)=>startOfWeek(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1)));
const endOfMonthGrid=(d:Date)=>addDays(startOfWeek(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0))),7);
const dateKey=(d:Date)=>d.toISOString().slice(0,10);
const timeMinutes=(v:string)=>{const [h,m]=v.split(":").map(Number);return h*60+m};
const shortDay=(d:Date)=>new Intl.DateTimeFormat("en-IE",{weekday:"short",timeZone:"UTC"}).format(d);
const monthTitle=(d:Date)=>new Intl.DateTimeFormat("en-IE",{month:"long",year:"numeric",timeZone:"UTC"}).format(d);
const weekTitle=(s:Date)=>{const e=addDays(s,6),a=new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",timeZone:"UTC"}).format(s),b=new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(e);return a+" – "+b};
const sessionHref=(s:{id:string;status:string})=>s.status==="IN_PROGRESS"||s.status==="COMPLETED"?"/training/"+s.id:"/planning/"+s.id;
const statusLabel=(s:string)=>s==="IN_PROGRESS"?"Live":s==="COMPLETED"?"Completed":"Planned";
const dayOverlap=(day:Date,start:Date,end?:Date|null)=>{const next=addDays(day,1),finish=end??start;return start<next&&finish>=day};
const scopeLabel=(m:{groups:{trainingGroup:{name:string}}[];gymnasts:{gymnast:{name:string}}[]})=>{const gs=m.groups.map(x=>x.trainingGroup.name),as=m.gymnasts.map(x=>x.gymnast.name);return [...gs,...as].slice(0,3).join(" · ")+(gs.length+as.length>3?" +"+(gs.length+as.length-3):"")||"Club"};
export default async function CalendarPage({searchParams}:{searchParams:Promise<{date?:string;view?:string}>}){
 const c=await requireAuthContext(),params=await searchParams,anchor=parseDate(params.date),view:ViewMode=params.view==="week"?"week":params.view==="year"?"year":"month",today=parseDate();
 const rangeStart=view==="year"?new Date(Date.UTC(anchor.getUTCFullYear(),0,1)):view==="week"?startOfWeek(anchor):startOfMonthGrid(anchor),rangeEnd=view==="year"?new Date(Date.UTC(anchor.getUTCFullYear()+1,0,1)):view==="week"?addDays(rangeStart,7):endOfMonthGrid(anchor),previous=view==="year"?addYears(anchor,-1):view==="week"?addDays(anchor,-7):addMonths(anchor,-1),next=view==="year"?addYears(anchor,1):view==="week"?addDays(anchor,7):addMonths(anchor,1);
 const groupScope=groupScopeWhere(c.organisation.id,c.membership.id,c.access),gymnastScope=gymnastScopeWhere(c.organisation.id,c.membership.id,c.access);
 const macroVisibility=c.access.canViewAllCoachingData?{}:{OR:[{groups:{some:{trainingGroup:groupScope}}},{gymnasts:{some:{gymnast:gymnastScope}}},{AND:[{groups:{none:{}}},{gymnasts:{none:{}}}]}]};
 const [sessions,calendarEvents,competitions,macrocycles]=c.access.canUseCoachingWorkspace?await Promise.all([
  prisma.trainingSession.findMany({where:{organisationId:c.organisation.id,sessionDate:{gte:rangeStart,lt:rangeEnd},trainingGroup:groupScope},select:{id:true,status:true,sessionDate:true,startTime:true,endTime:true,title:true,trainingGroup:{select:{name:true}},facilityAssignment:{select:{location:{select:{name:true}}}},blocks:{select:{durationMin:true}}},orderBy:[{sessionDate:"asc"},{startTime:"asc"}]}),
  prisma.calendarEvent.findMany({where:{organisationId:c.organisation.id,startDate:{lt:rangeEnd},OR:[{endDate:null},{endDate:{gte:rangeStart}}]},orderBy:[{startDate:"asc"},{title:"asc"}]}),
  prisma.competitionEvent.findMany({where:{organisationId:c.organisation.id,eventDate:{gte:rangeStart,lt:rangeEnd},status:{not:"CANCELLED"}},select:{id:true,name:true,eventDate:true,eventType:true},orderBy:{eventDate:"asc"}}),
  prisma.macrocycle.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE",AND:[macroVisibility,{OR:[{startDate:{lt:rangeEnd},endDate:{gte:rangeStart}},{startDate:{lte:today},endDate:{gte:today}}]}]},include:{groups:{include:{trainingGroup:{select:{name:true}}}},gymnasts:{include:{gymnast:{select:{name:true}}}},phases:{include:{periods:{orderBy:{orderIndex:"asc"}}},orderBy:[{orderIndex:"asc"},{startDate:"asc"}]}},orderBy:{startDate:"asc"}})
 ]):[[],[],[],[]];
 const currentMacrocycles=macrocycles.filter(m=>m.startDate<=today&&m.endDate>=today);
 const title=view==="year"?String(anchor.getUTCFullYear()):view==="week"?weekTitle(rangeStart):monthTitle(anchor),monthDays=view==="month"?Array.from({length:Math.round((rangeEnd.getTime()-rangeStart.getTime())/86400000)},(_,i)=>addDays(rangeStart,i)):[],weekDays=Array.from({length:7},(_,i)=>addDays(rangeStart,i));
 const weekSessionMinutes=view==="week"?sessions.flatMap(s=>[timeMinutes(s.startTime),timeMinutes(s.endTime)]):[],earliest=weekSessionMinutes.length?Math.max(0,Math.floor(Math.min(...weekSessionMinutes)/60)*60-60):8*60,latest=weekSessionMinutes.length?Math.min(1440,Math.ceil(Math.max(...weekSessionMinutes)/60)*60+60):22*60,calendarStart=Math.min(earliest,480),calendarEnd=Math.max(latest,1320),totalMinutes=calendarEnd-calendarStart,hourRows=Array.from({length:Math.ceil(totalMinutes/60)+1},(_,i)=>calendarStart/60+i);
 const linkFor=(d:Date,target:ViewMode=view)=>"/calendar?view="+target+"&date="+dateKey(d);
 const phaseItems=(day:Date)=>macrocycles.flatMap(m=>m.phases.filter(p=>dayOverlap(day,p.startDate,p.endDate)).map(p=>{const period=p.periods.find(x=>dayOverlap(day,x.startDate,x.endDate));return {id:"phase-"+p.id,label:period?.name??p.name,sub:period?m.name+" · "+p.name:m.name,kind:"macro" as const}}));
 const dateItems=(day:Date)=>[
  ...calendarEvents.filter(e=>dayOverlap(day,e.startDate,e.endDate)).map(e=>({id:"date-"+e.id,label:e.title,sub:e.eventType==="HOLIDAY"?"Holiday":"Important date",kind:e.eventType==="HOLIDAY"?"holiday" as const:"important" as const,href:null as string|null})),
  ...competitions.filter(e=>dateKey(e.eventDate)===dateKey(day)).map(e=>({id:"comp-"+e.id,label:e.name,sub:"Competition",kind:"competition" as const,href:"/competitions/"+e.id})),
  ...phaseItems(day).map(e=>({...e,href:null as string|null}))
 ];
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page">
  <div className="workspace-hero"><div><p className="workspace-kicker">Calendar</p><h1>{title}</h1><p className="workspace-meta">{sessions.length} session{sessions.length===1?"":"s"} · {calendarEvents.length+competitions.length} calendar item{calendarEvents.length+competitions.length===1?"":"s"}</p></div><div className="workspace-actions">
   <div className="calendar-view-toggle"><a href={linkFor(anchor,"year")} className={view==="year"?"active":""}>Year</a><a href={linkFor(anchor,"month")} className={view==="month"?"active":""}>Month</a><a href={linkFor(anchor,"week")} className={view==="week"?"active":""}>Week</a></div>
   <a href={linkFor(previous)} aria-label={"Previous "+view} className="workspace-button">←</a><a href={"/calendar?view="+view} className="workspace-button">Today</a><a href={linkFor(next)} aria-label={"Next "+view} className="workspace-button">→</a>
  </div></div>
  {currentMacrocycles.length>0&&<div className="calendar-macrocycles">{currentMacrocycles.map(m=>{const phase=m.phases.find(p=>p.startDate<=today&&p.endDate>=today);return <div key={m.id} className="calendar-macrocycle"><span>Current macrocycle</span><strong>{m.name}</strong><em>{phase?phase.name+" · ":""}{scopeLabel(m)}</em></div>})}</div>}
  <details id="add-calendar-item" className="management-panel mt-6"><summary>Add to calendar</summary><div className="management-grid">
   {c.access.canManageRotations&&<section><h2>Date or holiday</h2><form action={createCalendarEvent} className="mt-3 grid gap-2"><select name="eventType" required defaultValue="IMPORTANT_DATE" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="IMPORTANT_DATE">Important date</option><option value="HOLIDAY">Holiday</option></select><input name="title" required placeholder="Title" className="rounded-xl border border-[var(--border)] px-3 py-3"/><div className="grid grid-cols-2 gap-2"><label className="calendar-field">Start<input name="startDate" type="date" required/></label><label className="calendar-field">End<input name="endDate" type="date"/></label></div><textarea name="notes" placeholder="Notes" className="min-h-20 rounded-xl border border-[var(--border)] px-3 py-3"/><button className="workspace-button workspace-button-primary">Add date</button></form></section>}
   <section><h2>Competition</h2><form action={createCalendarCompetition} className="mt-3 grid gap-2"><input name="name" required placeholder="Competition name" className="rounded-xl border border-[var(--border)] px-3 py-3"/><select name="eventType" required defaultValue="EXTERNAL" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="EXTERNAL">External competition</option><option value="CONTROL">Control competition</option></select><input name="eventDate" type="date" required className="rounded-xl border border-[var(--border)] px-3 py-3"/><input name="location" placeholder="Location" className="rounded-xl border border-[var(--border)] px-3 py-3"/><button className="workspace-button workspace-button-primary">Create competition</button></form></section>
  </div>{c.access.canManageRotations&&calendarEvents.length>0&&<div className="calendar-date-manager">{calendarEvents.map(e=><div key={e.id}><span><strong>{e.title}</strong><small>{e.eventType==="HOLIDAY"?"Holiday":"Important date"} · {dateKey(e.startDate)}{e.endDate&&dateKey(e.endDate)!==dateKey(e.startDate)?" – "+dateKey(e.endDate):""}</small></span><form action={deleteCalendarEvent}><input type="hidden" name="eventId" value={e.id}/><button>Remove</button></form></div>)}</div>}</details>
  {view==="year"?<div className="calendar-year-grid mt-6">{Array.from({length:12},(_,month)=>{const first=new Date(Date.UTC(anchor.getUTCFullYear(),month,1)),daysInMonth=new Date(Date.UTC(anchor.getUTCFullYear(),month+1,0)).getUTCDate(),offset=(first.getUTCDay()+6)%7;return <section key={month} className="calendar-year-month"><h2><a href={linkFor(first,"month")}>{new Intl.DateTimeFormat("en-IE",{month:"long",timeZone:"UTC"}).format(first)}</a></h2><div className="calendar-year-days">{["M","T","W","T","F","S","S"].map((d,i)=><span key={i} className="calendar-year-weekday">{d}</span>)}{Array.from({length:offset},(_,i)=><span key={"blank-"+i}/>)}{Array.from({length:daysInMonth},(_,i)=>{const day=addDays(first,i),key=dateKey(day),count=sessions.filter(s=>dateKey(s.sessionDate)===key).length+dateItems(day).length;return <a key={key} href={linkFor(day,"week")} aria-label={key+(count?" · "+count+" calendar item"+(count===1?"":"s"):"")} className={"calendar-year-day "+(key===dateKey(today)?"calendar-today ":"")+(count?"has-items":"")}>{i+1}</a>})}</div></section>})}</div>:
  view==="month"?<div className="mt-6 overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="min-w-[760px]"><div className="grid grid-cols-7 border-b border-[var(--border)]">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><div key={d} className="px-3 py-3 text-center text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">{d}</div>)}</div><div className="grid grid-cols-7">{monthDays.map((day,index)=>{const key=dateKey(day),daySessions=sessions.filter(s=>dateKey(s.sessionDate)===key),items=dateItems(day),outside=day.getUTCMonth()!==anchor.getUTCMonth(),isToday=key===dateKey(today);return <div key={key} className={"min-h-[168px] border-b border-r border-[var(--border)] p-2 "+(outside?"opacity-55 ":"")+((index+1)%7===0?"border-r-0 ":"")}><div className="mb-2 flex items-center justify-between"><a href={linkFor(day,"week")} className={"flex h-8 min-w-8 items-center justify-center rounded-full px-2 text-sm font-semibold "+(isToday?"calendar-today":"")}>{day.getUTCDate()}</a>{daySessions.length+items.length>0&&<span className="text-[10px] text-[var(--muted)]">{daySessions.length+items.length}</span>}</div><div className="grid gap-1.5">{items.slice(0,3).map(item=>item.href?<a key={item.id} href={item.href} className={"calendar-item "+item.kind}><strong>{item.label}</strong><span>{item.sub}</span></a>:<div key={item.id} className={"calendar-item "+item.kind}><strong>{item.label}</strong><span>{item.sub}</span></div>)}{daySessions.slice(0,Math.max(1,4-items.length)).map(s=><a key={s.id} href={sessionHref(s)} className="calendar-session"><strong>{s.startTime} · {s.trainingGroup.name}</strong><span>{s.title}</span>{s.status!=="PLANNED"&&<small>{statusLabel(s.status)}</small>}</a>)}{daySessions.length+items.length>5&&<a href={linkFor(day,"week")} className="px-2 py-1 text-xs font-semibold">+ {daySessions.length+items.length-5} more</a>}</div></div>})}</div></div></div>:
  <div className="mt-6 overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="min-w-[980px]"><div className="grid grid-cols-[64px_repeat(7,minmax(128px,1fr))] border-b border-[var(--border)]"><div className="border-r border-[var(--border)]"/>{weekDays.map(day=>{const key=dateKey(day),isToday=key===dateKey(today);return <div key={key} className="border-r border-[var(--border)] px-2 py-3 text-center last:border-r-0"><span className="block text-xs font-semibold uppercase tracking-wide text-[var(--muted)]">{shortDay(day)}</span><span className={"mx-auto mt-1 flex h-9 w-9 items-center justify-center rounded-full text-lg font-semibold "+(isToday?"calendar-today":"")}>{day.getUTCDate()}</span></div>})}</div>
   <div className="grid grid-cols-[64px_repeat(7,minmax(128px,1fr))] border-b border-[var(--border)]"><div className="border-r border-[var(--border)] px-2 py-3 text-[10px] font-semibold uppercase tracking-wide text-[var(--muted)]">All day</div>{weekDays.map(day=><div key={dateKey(day)} className="min-h-20 border-r border-[var(--border)] p-1.5 last:border-r-0"><div className="grid gap-1">{dateItems(day).map(item=>item.href?<a key={item.id} href={item.href} className={"calendar-item "+item.kind}><strong>{item.label}</strong></a>:<div key={item.id} className={"calendar-item "+item.kind}><strong>{item.label}</strong></div>)}</div></div>)}</div>
   <div className="grid grid-cols-[64px_repeat(7,minmax(128px,1fr))]"><div className="relative border-r border-[var(--border)]" style={{height:totalMinutes+"px"}}>{hourRows.map(h=><span key={h} className="absolute right-2 -translate-y-1/2 text-[10px] text-[var(--muted)]" style={{top:(h*60-calendarStart)+"px"}}>{String(h).padStart(2,"0")}:00</span>)}</div>{weekDays.map(day=>{const key=dateKey(day),daySessions=sessions.filter(s=>dateKey(s.sessionDate)===key);return <div key={key} className="relative border-r border-[var(--border)] last:border-r-0" style={{height:totalMinutes+"px"}}>{hourRows.map(h=><div key={h} className="absolute left-0 right-0 border-t border-[var(--border)] opacity-60" style={{top:(h*60-calendarStart)+"px"}}/>)}{daySessions.map(s=>{const start=timeMinutes(s.startTime),end=timeMinutes(s.endTime),top=Math.max(0,start-calendarStart),height=Math.max(38,end-start),mins=s.blocks.reduce((n,b)=>n+(b.durationMin??0),0);return <a key={s.id} href={sessionHref(s)} className="calendar-week-session" style={{top:top+"px",height:height+"px"}} title={s.title+" · "+s.trainingGroup.name}><strong>{s.startTime}–{s.endTime}</strong><strong>{s.trainingGroup.name}</strong>{height>=58&&<span>{s.title}</span>}{height>=82&&<small>{statusLabel(s.status)}{s.facilityAssignment?" · "+s.facilityAssignment.location.name:""}{mins?" · "+mins+" min planned":""}</small>}</a>})}</div>})}</div></div></div>}
 </section></AppShell>
}
