import { notFound } from "next/navigation";
import { AppShell } from "@/app/components/app-shell";
import { createTrustedContributor, setTrustedContributorStatus } from "@/app/actions/contributors";
import { requireAuthContext } from "@/app/lib/auth";
import { prisma } from "@/app/lib/prisma";
export const dynamic="force-dynamic";
export default async function ContributorsPage(){
 const c=await requireAuthContext();if(!c.access.canManageProgrammesAndMethodology)notFound();
 const contributors=await prisma.trustedContributor.findMany({where:{organisationId:c.organisation.id},include:{_count:{select:{methodologyRecords:true}}},orderBy:[{status:"asc"},{name:"asc"}]});
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><a href="/more" className="workspace-back">← More</a><div className="workspace-hero"><div><p className="workspace-kicker">Methodology sources</p><h1>Trusted contributors</h1><p className="workspace-meta">{contributors.length} active contributor{contributors.length===1?"":"s"}</p></div></div>
  <details className="mt-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><summary className="cursor-pointer font-semibold">+ Add trusted contributor</summary><form action={createTrustedContributor} className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-3"><input name="name" required placeholder="Name" className="rounded-xl border border-[var(--border)] px-3 py-3"/><input name="roleLabel" placeholder="Role / speciality" className="rounded-xl border border-[var(--border)] px-3 py-3"/><input name="organisationName" placeholder="Organisation (optional)" className="rounded-xl border border-[var(--border)] px-3 py-3"/></div><textarea name="scopeNote" placeholder="What areas is this contributor trusted for?" className="min-h-20 rounded-xl border border-[var(--border)] px-3 py-3"/><textarea name="sourceNote" placeholder="Source / relationship note" className="min-h-20 rounded-xl border border-[var(--border)] px-3 py-3"/><button className="w-fit rounded-xl bg-[var(--foreground)] px-4 py-3 text-sm font-semibold text-white">Add contributor</button></form></details>
  <div className="mt-8 grid gap-4">{contributors.map(x=><article key={x.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{x.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">{[x.roleLabel,x.organisationName].filter(Boolean).join(" · ")||"No role detail"}</p></div><span className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{x.status}</span></div>{x.scopeNote&&<p className="mt-3 text-sm"><strong>Trusted scope:</strong> {x.scopeNote}</p>}{x.sourceNote&&<p className="mt-2 text-sm text-[var(--muted)]"><strong>Source note:</strong> {x.sourceNote}</p>}<p className="mt-3 text-xs text-[var(--muted)]">{x._count.methodologyRecords} methodology record{x._count.methodologyRecords===1?"":"s"} linked</p><form action={setTrustedContributorStatus} className="mt-3"><input type="hidden" name="contributorId" value={x.id}/><input type="hidden" name="status" value={x.status==="ACTIVE"?"ARCHIVED":"ACTIVE"}/><button className="text-sm font-semibold">{x.status==="ACTIVE"?"Archive contributor":"Reactivate contributor"}</button></form></article>)}</div>
 </section></AppShell>;
}