-- Complete current Gymnastics Ireland WAG Uneven Bars requirements for the General and Plus pathways.
-- Source authority: General V4 January 2026 and Plus V4 February 2026 NDP Guidelines.

WITH "barsRules" ("id","packageId","levelCode","valueJson","sourcePage") AS (
  VALUES
    ('gi25_general_bars_1','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_1','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"LOW_BAR","startPosition":"standing shoulders at or below bar height","springboardOrCoachingBlockAllowed":true,"equipmentSourcePage":21},"routine":["JUMP_TO_FRONT_SUPPORT_STRAIGHT_ARMS","TWO_CONNECTED_CASTS_GOOD_CHEST_SHAPE_STRAIGHT_ARMS","PRESS_BAR_TO_KNEES_HOLD_2_SECONDS","ROLL_FORWARD_TO_TUCK_HANG_HOLD_2_SECONDS","RETURN_TO_STAND"],"bonuses":[{"value":0.2,"alternative":"UPWARD_HIP_CIRCLE_INSTEAD_OF_REQUIREMENT_1"},{"value":0.2,"condition":"PRESS_BAR_AT_LEAST_HALFWAY_BETWEEN_KNEES_AND_ANKLE"},{"value":0.2,"condition":"TUCK_HANG_HELD_5_SECONDS"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',23),
    ('gi25_general_bars_2','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_2','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"LOW_BAR","equipmentSourcePage":21},"routine":["UPWARD_HIP_CIRCLE","THREE_CASTS_GOOD_CHEST_SHAPE_STRAIGHT_ARMS","PRESS_BAR_TO_KNEES_HOLD_3_SECONDS","LOWER_TO_FRONT_SUPPORT","ROLL_FORWARD_SLOWLY_TO_V_HANG_HOLD_3_SECONDS","RETURN_TO_STAND"],"recognition":{"vHang":"toes touching bar and no lower than 45 degrees from vertical"},"bonuses":[{"value":0.2,"condition":"PRESS_BAR_AT_LEAST_HALFWAY_BETWEEN_KNEES_AND_ANKLE"},{"value":0.2,"condition":"V_HANG_HELD_MORE_THAN_5_SECONDS"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',24),
    ('gi25_general_bars_3','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_3','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"LOW_BAR","equipmentSourcePage":21},"routine":["UPWARD_HIP_CIRCLE","THREE_CASTS_LEGS_TOGETHER","BACKWARD_HIP_CIRCLE","CAST_LEGS_TOGETHER","BACKWARD_HIP_CIRCLE_IMMEDIATE_UNDERSHOOT"],"recognition":{"undershoot":"no feet on and no cast into"},"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',25),
    ('gi25_general_bars_4','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_4','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"LOW_BAR","startPosition":"back to high bar","equipmentSourcePage":21},"routine":["GLIDE_SWING_BACK_RELEASE_TO_STAND","UPWARD_HIP_CIRCLE","THREE_CASTS_LEGS_TOGETHER","BACKWARD_HIP_CIRCLE","CAST_TO_PIKE_OR_STRADDLE_ON_UNDERSHOOT"],"bonuses":[{"value":0.2,"alternative":"UPSTART_INSTEAD_OF_GLIDE_SWING_AND_UPWARD_HIP_CIRCLE"},{"value":0.2,"alternative":"PIKE_OR_STRADDLE_ON_STRETCH_JUMP_OFF"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',26),
    ('gi25_general_bars_5','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_5','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"A_BARS","dismountSafetyMatCm":30,"replacesTopFigMatCm":10,"figLandingAreaCm":20,"equipmentSourcePage":21},"routine":["GLIDE_SWING_BACK_RELEASE_TO_STAND","UPWARD_HIP_CIRCLE","CAST_BACKWARD_HIP_CIRCLE","CAST_TO_PIKE_OR_STRADDLE_ON_JUMP_TO_HIGH_BAR","THREE_SWINGS","THIRD_SWING_WRAP_OVER","IMMEDIATE_UNDERSHOOT_DISMOUNT"],"bonuses":[{"value":0.2,"alternative":"UPSTART_INSTEAD_OF_GLIDE_SWING_AND_UPWARD_HIP_CIRCLE"},{"value":0.2,"condition":"CIRCLE_LOW_BAR_TWICE_AFTER_FIRST_CAST"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',27),
    ('gi25_general_bars_6','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_6','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"A_BARS","safetyMatCm":20,"replacesTopFigMatCm":10,"figLandingAreaCm":20,"equipmentSourcePage":21},"routine":["GLIDE_SWING_BACK_RELEASE_TO_STAND","UPWARD_HIP_CIRCLE","CAST_BACKWARD_HIP_CIRCLE","CAST_TO_PIKE_OR_STRADDLE_ON_CATCH_HIGH_BAR","THREE_TAP_SWINGS","THIRD_SWING_WRAP_OVER","IMMEDIATE_UNDERSWING_SWING_BACK","SWING_TO_WRAP_OVER","CAST_TO_FLYAWAY_OR_FIG_CODED_NON_SALTO_DISMOUNT"],"bonuses":[{"value":0.2,"alternative":"UPSTART_INSTEAD_OF_GLIDE_SWING_AND_UPWARD_HIP_CIRCLE"},{"value":0.2,"condition":"CIRCLE_LOW_BAR_TWICE_AFTER_FIRST_CAST"},{"value":0.2,"alternative":"LONG_UPSTART_AFTER_UNDERSWING_INSTEAD_OF_SECOND_WRAP_OVER"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',28),
    ('gi25_general_bars_7','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_7','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"A_BARS","safetyMatCm":20,"replacesTopFigMatCm":10,"figLandingAreaCm":20,"equipmentSourcePage":21},"routine":["UPSTART","CAST_BACKWARD_HIP_CIRCLE","CAST_TO_PIKE_OR_STRADDLE_ON_CATCH_HIGH_BAR","THREE_TAP_SWINGS","THIRD_SWING_WRAP_OVER","IMMEDIATE_UNDERSWING","SWING_BACK","LONG_UPSTART","FIG_CODED_DISMOUNT"],"bonuses":[{"value":0.2,"alternative":"SOLE_CIRCLE_JUMP_TO_HIGH_BAR_INSTEAD_OF_PIKE_ON","recognition":"no deduction for bent legs"},{"value":0.2,"condition":"FLYAWAY"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',29),
    ('gi25_general_bars_8','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_8','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"A_BARS","safetyMatCm":20,"replacesTopFigMatCm":10,"equipmentSourcePage":21},"routine":["UPSTART","CAST_BACKWARD_HIP_CIRCLE","CAST_FLOAT_UPSTART","CAST_TO_PIKE_OR_STRADDLE_ON_CATCH_HIGH_BAR","THREE_TAP_SWINGS","THIRD_SWING_WRAP_OVER","IMMEDIATE_UNDERSWING_SWING_BACK","LONG_UPSTART","FIG_CODED_DISMOUNT"],"bonuses":[{"value":0.2,"alternative":"CLEAR_CIRCLE_TO_HANDSTAND_INTO_FLOAT_UPSTART_INSTEAD_OF_BACKWARD_HIP_CIRCLE_AND_CAST"},{"value":0.2,"alternative":"SOLE_CIRCLE_TO_HIGH_BAR_INSTEAD_OF_PIKE_ON","recognition":"no deduction for bent legs"},{"value":0.2,"alternative":"GIANT_CIRCLE","omits":["THREE_TAP_SWINGS","WRAP_OVER","UNDERSWING","LONG_UPSTART"]}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',30),
    ('gi25_general_bars_9','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_9','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":12,"difficulty":2,"execution":10},"routineConstruction":{"count":6,"source":"FIG_WAG_2025_2028_CODE_OR_LISTED_J_ELEMENTS","dismountIncluded":true},"listedJElements":["PIKE_OR_STRADDLE_ON_TO_HIGH_BAR","PIKE_ON_UNDERSHOOT_HALF_TURN_REGRASP_SAME_BAR_NOT_ABOVE_HORIZONTAL","THREE_QUARTER_GIANT_HALF_TURN_NOT_ABOVE_HORIZONTAL","CAST_THREE_QUARTER_GIANT_WRAP_OVER_IMMEDIATE_UNDERSWING","UNDERSHOOT_DISMOUNT"],"recognition":{"aboveHorizontalForListedTurns":"coded FIG element"},"bonuses":[{"value":0.2,"condition":"EACH_FIG_CODED_ELEMENT","exclusions":["UPSTART","LONG_UPSTART","BACKWARD_HIP_CIRCLE","NON_SALTO_DISMOUNT"]}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',31),
    ('gi25_general_bars_10','canonical_gi_wag_general_2025_plus_v4_2026_01','GENERAL_10','{"competitionContext":"LEVEL","startValue":{"mode":"FIG_D_PLUS_E"},"routineConstruction":{"count":6,"source":"FIG_WAG_2025_2028_CODE","dismountIncluded":true},"compositionRequirements":[{"value":0.5,"requirement":"CLOSE_BAR_ELEMENT_EXCEPT_BACK_HIP"},{"value":0.5,"requirement":"CHANGE_BAR_USING_ELEMENT"},{"value":0.5,"requirement":"CAST_WITHIN_45_DEGREES_OF_HANDSTAND","note":"no deduction for change of bar without an element"}],"printedStandaloneValue":1,"bonuses":[{"value":0.5,"condition":"EACH_FIG_COMPOSITION_REQUIREMENT"},{"value":0.2,"maxCount":8,"condition":"EACH_CODED_ELEMENT","exclusions":["A_VALUED_UPSTARTS","BACKWARD_HIP_CIRCLE","NON_SALTO_DISMOUNT"]}],"scoreTreatment":{"allBonusAddedTo":"D_SCORE"},"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',32),
    ('gi25_general_bars_advanced_teams','canonical_gi_wag_general_2025_plus_v4_2026_01','ADVANCED_TEAMS','{"competitionContext":"TEAM","startValue":{"mode":"FIG_D_PLUS_E"},"routineConstruction":{"count":6,"source":"FIG_WAG_2025_2028_CODE","dismountIncluded":true},"compositionRequirements":[{"value":0.5,"requirement":"CLOSE_BAR_ELEMENT_EXCEPT_BACK_HIP"},{"value":0.5,"requirement":"CHANGE_BAR_USING_ELEMENT"},{"value":0.5,"requirement":"CAST_WITHIN_45_DEGREES_OF_HANDSTAND","note":"no deduction for change of bar without an element"}],"printedStandaloneValue":1,"bonuses":[{"value":0.5,"condition":"EACH_FIG_COMPOSITION_REQUIREMENT"},{"value":0.2,"maxCount":8,"condition":"EACH_CODED_ELEMENT","exclusions":["A_VALUED_UPSTARTS","BACKWARD_HIP_CIRCLE","NON_SALTO_DISMOUNT"]}],"scoreTreatment":{"allBonusAddedTo":"D_SCORE"},"assignableLevel":false,"sameRequirementsAs":"GENERAL_10","requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',32),
    ('gi25_general_bars_intermediate_teams','canonical_gi_wag_general_2025_plus_v4_2026_01','INTERMEDIATE_TEAMS','{"competitionContext":"TEAM","assignableLevel":false,"startValue":{"mode":"FIXED","total":13,"difficulty":3,"execution":10},"equipment":{"bar":"A_BARS","safetyMatCm":20,"replacesTopFigMatCm":10,"figLandingAreaCm":20,"equipmentSourcePage":21},"routine":["UPSTART_CAST_BACKWARD_HIP_CIRCLE","CAST_TO_PIKE_OR_STRADDLE_ON_CATCH_HIGH_BAR","THREE_SWINGS","THIRD_SWING_WRAP_OVER","IMMEDIATE_UNDERSWING","SWING_BACK","SWING_TO_WRAP_OVER","CAST_TO_FLYAWAY_OR_OTHER_FIG_CODED_NON_SALTO_DISMOUNT"],"bonuses":[{"value":0.2,"alternative":"CLEAR_CIRCLE_TO_HANDSTAND_INSTEAD_OF_BACKWARD_HIP_CIRCLE"},{"value":0.2,"alternative":"SOLE_CIRCLE_TO_HIGH_BAR_INSTEAD_OF_PIKE_ON","recognition":"no deduction for bent legs"},{"value":0.2,"alternative":"LONG_UPSTART_INSTEAD_OF_SECOND_WRAP_OVER"},{"value":0.2,"alternative":"GIANT_CIRCLE","omits":["THREE_SWINGS","WRAP_OVER","UNDERSWING","LONG_UPSTART"]}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',33),
    ('gi25_plus_bars_1','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_1','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13},"equipment":{"bar":"LOW_BAR"},"routine":["THREE_GLIDE_SWINGS_RETURN_TO_STAND","UPWARD_HIP_CIRCLE","THREE_CONNECTED_CASTS_GOOD_CHEST_SHAPE_STRAIGHT_ARMS","PRESS_BAR_TO_KNEES_HOLD_3_SECONDS","LOWER_TO_FRONT_SUPPORT","ROLL_FORWARD_SLOWLY_TO_V_HANG_HOLD_3_SECONDS_TOES_AT_BAR","LOWER_TO_L_HANG","RETURN_TO_V_HANG_HOLD_3_SECONDS","RETURN_TO_STAND"],"bonuses":[{"value":0.5,"alternative":"UPSTART_INSTEAD_OF_UPWARD_HIP_CIRCLE"},{"value":0.2,"condition":"EACH_CAST_CLEARLY_ABOVE_HORIZONTAL"},{"value":0.2,"condition":"PRESS_BAR_AT_LEAST_HALFWAY_BETWEEN_KNEES_AND_ANKLE"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',20),
    ('gi25_plus_bars_2','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_2','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13},"equipment":{"bar":"SINGLE_LOW_BAR","heightCm":175},"routine":["THREE_CONNECTED_GLIDE_SWINGS_FROM_STANDING","UPWARD_HIP_CIRCLE","THREE_CASTS_LEGS_TOGETHER","THIRD_CAST_BACKWARD_HIP_CIRCLE","IMMEDIATE_UNDERSHOOT_DISMOUNT"],"bonuses":[{"value":0.5,"alternative":"UPSTART_INSTEAD_OF_UPWARD_HIP_CIRCLE"},{"value":0.2,"condition":"EACH_CAST_AT_OR_ABOVE_45_DEGREES_ABOVE_HORIZONTAL"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',21),
    ('gi25_plus_bars_3','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_3','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13},"equipment":{"bar":"A_BARS_HIGH_BAR","highBarHeightCm":255,"safetyMatsUnderneathUpToCm":40,"startFacing":"LOW_BAR"},"routine":["FROM_HANG_TWO_CHIN_UPS_FEET_IN_FRONT","TWO_PIKE_LEG_LIFTS","HOLD_DISH_AND_ARCH_SWING_SHAPES_2_SECONDS_EACH_IMMEDIATE_TROLLEY_SWING_SWING_BACK","THREE_SWINGS_THIRD_TO_WRAP_OVER_IMMEDIATE_UNDERSWING_SWING_BACK","LONG_UPSTART_ROLL_FORWARD_TO_HANG_JUMP_DOWN_DISMOUNT"],"recognition":{"trolleySwingHeightDeduction":false},"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',22),
    ('gi25_plus_bars_4','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_4','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13},"equipment":{"bar":"A_BARS","dismountAdditionalSafetyMatCm":40,"figLandingMatCm":20},"routine":["UPSTART","CAST","UPSTART","CAST","PIKE_ON_JUMP_TO_HIGH_BAR","FOUR_SWINGS","FOURTH_SWING_WRAP_OVER_IMMEDIATE_UNDERSWING_SWING_BACK","LONG_UPSTART","FIG_CODED_DISMOUNT"],"bonuses":[{"value":0.2,"alternative":"LONG_UPSTART_GIANT_CIRCLE_INSTEAD_OF_REQUIREMENTS_6_7_8"},{"value":0.2,"condition":"STRAIGHT_OR_DISHED_FLYAWAY"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',23),
    ('gi25_plus_bars_5','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_5','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13},"orderOptional":true,"equipment":{"bar":"A_BARS","landingAdditionalSafetyMatCm":40},"routine":["UPSTART","CLOSE_BAR_ELEMENT_EXCLUDING_BACKWARD_FORWARD_HIP_CIRCLE_AND_SOLE_CIRCLE","PIKE_ON","LONG_UPSTART","GIANT_CIRCLE","FIG_CODED_DISMOUNT"],"sourceNumberingNote":"printed sequence labels dismount as 7; no separate requirement 6 is printed","bonuses":[{"value":0.2,"alternative":"SOLE_CIRCLE_TO_HIGH_BAR_INSTEAD_OF_PIKE_ON","recognition":"no deduction for bent legs"},{"value":0.2,"condition":"DISHED_OR_STRAIGHT_FLYAWAY"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',24),
    ('gi25_plus_bars_6','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_6','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13},"orderOptional":true,"equipment":{"optionalAdditionalSafetyMatCm":20,"topMatCm":10},"routine":["UPSTART","TWO_CLOSE_BAR_ELEMENTS_SAME_OR_DIFFERENT_EXCLUDING_BACKWARD_FORWARD_HIP_CIRCLE_AND_SOLE_CIRCLE","SOLE_CIRCLE","LONG_UPSTART","TWO_GIANTS","FIG_CODED_DISMOUNT"],"bonuses":[{"value":0.2,"condition":"B_OR_HIGHER_DISMOUNT"},{"value":0.2,"alternative":"ANY_SHOOT_TO_HIGH_BAR_INSTEAD_OF_SOLE_CIRCLE"},{"value":0.2,"condition":"DIFFERENT_SECOND_CLOSE_BAR_ELEMENT"},{"value":0.5,"condition":"ANY_FIG_COMPOSITION_REQUIREMENT"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',25),
    ('gi25_plus_bars_7','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_7','{"competitionContext":"LEVEL","startValue":{"mode":"FIXED","total":13},"orderOptional":true,"equipment":{"bar":"A_BARS","gymnastMayBeLiftedToStartOnHighBar":true},"optionalEntry":"TROLLEY_SWING_IF_NEEDED","routine":["LONG_UPSTART","TWO_DIFFERENT_CLOSE_BAR_ELEMENTS_EXCLUDING_BACKWARD_FORWARD_HIP_CIRCLE_AND_SOLE_CIRCLE","TWO_SWING_HALF_TURNS_BLIND_CHANGE","TWO_GIANTS","FIG_CODED_DISMOUNT"],"bonuses":[{"value":0.2,"condition":"DIFFERENT_SECOND_CLOSE_BAR_ELEMENT"},{"value":0.2,"condition":"B_OR_HIGHER_DISMOUNT"},{"value":0.5,"condition":"ANY_FIG_COMPOSITION_REQUIREMENT"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',26),
    ('gi25_plus_bars_2_3_teams','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_2_3_TEAMS','{"competitionContext":"TEAM","assignableLevel":false,"startValue":{"mode":"FIXED","total":13},"equipment":{"bar":"A_BARS_HIGH_BAR","highBarHeightCm":255,"safetyMatsUnderneathUpToCm":40},"routine":["FROM_HANG_HOLD_DISH_AND_ARCH_SWING_SHAPES_2_SECONDS_EACH_IMMEDIATE_TROLLEY_SWING_SWING_BACK","THREE_SWINGS_THIRD_TO_WRAP_OVER","IMMEDIATE_UNDERSWING_SWING_BACK_DROP_OFF"],"bonuses":[{"value":0.5,"alternative":"LONG_UPSTART_AFTER_REQUIREMENT_3_THEN_ROLL_FORWARD_TO_HANG_JUMP_DOWN_DISMOUNT"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',29),
    ('gi25_plus_bars_4_5_teams','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_4_5_TEAMS','{"competitionContext":"TEAM","assignableLevel":false,"startValue":{"mode":"FIXED","total":12},"equipment":{"bar":"A_BARS","dismountAdditionalSafetyMatCm":40,"figLandingMatCm":20},"routine":["UPSTART","CAST","UPSTART","CAST","PIKE_ON_JUMP_TO_HIGH_BAR","FOUR_TAP_SWINGS","FOURTH_SWING_WRAP_OVER_IMMEDIATE_UNDERSWING_SWING_BACK","LONG_UPSTART","FIG_CODED_DISMOUNT"],"bonuses":[{"value":0.5,"condition":"CLOSE_BAR_ELEMENT_BETWEEN_REQUIREMENTS_1_AND_3","exclusions":["BACKWARD_HIP_CIRCLE","FORWARD_HIP_CIRCLE","SOLE_CIRCLE"]},{"value":0.2,"alternative":"SOLE_CIRCLE_TO_HIGH_BAR_INSTEAD_OF_PIKE_ON","recognition":"no deduction for bent legs; Plus level only"},{"value":0.5,"alternative":"LONG_UPSTART_GIANT_CIRCLE_INSTEAD_OF_REQUIREMENTS_6_7_8"},{"value":0.2,"condition":"STRAIGHT_OR_DISHED_FLYAWAY"}],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',30),
    ('gi25_plus_bars_6_7_teams','canonical_gi_wag_plus_2025_plus_v4_2026_02','PLUS_6_7_TEAMS','{"competitionContext":"TEAM","assignableLevel":false,"startValue":{"mode":"FIG"},"requirements":{"source":"FIG_WAG_2025_2028","minimumElements":6,"maximumCountingElements":8,"dismountTreatment":"AS_FIG"},"shortExerciseModification":{"ifOnly5ElementsFinalScoreDeduction":2},"bonuses":[{"value":0.5,"condition":"SEVEN_OR_MORE_FIG_ELEMENTS","repeatedElementsCount":false}],"equipment":{"optionalAdditionalDismountMatCm":20},"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',31)
)
INSERT INTO "FigApparatusRule" (
  "id","packageId","apparatus","levelCode","ruleType","ruleKey","valueJson","sourcePage","verificationStatus"
)
SELECT
  "barsRules"."id","barsRules"."packageId",'UNEVEN_BARS',"barsRules"."levelCode",
  'PRESCRIBED_ROUTINE','bars_routine',"barsRules"."valueJson","barsRules"."sourcePage",'VERIFIED'
FROM "barsRules"
WHERE EXISTS (SELECT 1 FROM "RulesetPackage" package WHERE package."id" = "barsRules"."packageId")
AND NOT EXISTS (
  SELECT 1 FROM "FigApparatusRule" existing
  WHERE existing."packageId" = "barsRules"."packageId"
    AND existing."apparatus" = 'UNEVEN_BARS'
    AND existing."levelCode" = "barsRules"."levelCode"
    AND existing."ruleKey" = 'bars_routine'
);
