-- Complete cross-apparatus GI WAG 2026 integration rules and Plus Physical Preparation.
-- Source authority: General V4 January 2026 and Plus V4 February 2026.
WITH "rules" ("id","packageId","apparatus","levelCode","ruleType","ruleKey","valueJson","sourcePage") AS (
  VALUES
    ('gi25_general_age_basis','canonical_gi_wag_general_2025_plus_v4_2026_01','ALL','ALL','ELIGIBILITY','age_basis','{"ageDeterminedOn":"JANUARY_1_OF_COMPETITION_YEAR","minimumTurningAge":7,"mustCompeteWithinAgeGroup":true,"insufficientNumbersMayReduceCategories":true,"clubAndCoachResponsibleForCorrectAgeCategoryAndLevel":true}',6),
    ('gi25_general_age_groups','canonical_gi_wag_general_2025_plus_v4_2026_01','ALL','ALL','ELIGIBILITY','competition_age_groups','{"INTRO":["U7","U8","U9","U10","O10"],"GENERAL_1":["U7","U8","U9","U10","U11","O11"],"GENERAL_2":["U8","U9","U10","U11","O11"],"GENERAL_3":["U8","U9","U10","U11","U12","U13","O13"],"GENERAL_4":["U9","U10","U11","U12","U13","U14","U15","O15"],"GENERAL_5":["U11","U12","U13","U14","U16","O16"],"GENERAL_6":["U12","U13","U15","O15"],"GENERAL_7":["U13","U15","O15"],"GENERAL_8":["U13","U15","O15"],"GENERAL_9":["U15","O15"],"GENERAL_10":["U15","O15"],"INTERMEDIATE_TEAMS":["U14","OPEN"],"ADVANCED_TEAMS":["OPEN"]}',8),
    ('gi25_general_team_scoring','canonical_gi_wag_general_2025_plus_v4_2026_01','ALL','ALL','COMPETITION','team_composition_and_scoring','{"teamsPerClubLimit":null,"teamSize":{"minimum":3,"maximum":5},"allFiveMayPerformEachApparatus":true,"countingScoresPerApparatus":3,"apparatusTotalsForFinalTeamScore":4}',15),
    ('gi25_general_all_around','canonical_gi_wag_general_2025_plus_v4_2026_01','ALL','ALL','COMPETITION','all_around_composition','{"GENERAL":{"apparatusCount":4,"components":["VAULT","UNEVEN_BARS","BALANCE_BEAM","FLOOR_EXERCISE"]},"rankingRequiresAllComponents":true}',15),
    ('gi25_general_routine_lengths','canonical_gi_wag_general_2025_plus_v4_2026_01','ALL','ALL','COMPETITION','routine_lengths','{"INTRO":{"floorSeconds":60},"GENERAL_1":{"beamSeconds":60,"floorSeconds":60},"GENERAL_2":{"beamSeconds":60,"floorSeconds":60},"GENERAL_3":{"beamSeconds":60,"floorSeconds":60},"GENERAL_4":{"beamSeconds":60,"floorSeconds":60},"GENERAL_5":{"beamSeconds":60,"floorSeconds":60},"GENERAL_6":{"beamSeconds":90,"floorSeconds":90},"GENERAL_7":{"beamSeconds":90,"floorSeconds":90},"GENERAL_8":{"beamSeconds":90,"floorSeconds":90},"GENERAL_9":{"beamSeconds":90,"floorSeconds":90},"GENERAL_10":{"beamSeconds":90,"floorSeconds":90},"INTERMEDIATE_TEAMS":{"beamSeconds":90,"floorSeconds":90},"ADVANCED_TEAMS":{"beamSeconds":90,"floorSeconds":90}}',14),
    ('gi25_plus_age_basis','canonical_gi_wag_plus_2025_plus_v4_2026_02','ALL','ALL','ELIGIBILITY','age_basis','{"ageDeterminedOn":"JANUARY_1_OF_COMPETITION_YEAR","minimumTurningAge":7,"mustCompeteWithinAgeGroup":true,"insufficientNumbersMayReduceCategories":true,"clubAndCoachResponsibleForCorrectAgeCategoryAndLevel":true}',6),
    ('gi25_plus_age_groups','canonical_gi_wag_plus_2025_plus_v4_2026_02','ALL','ALL','ELIGIBILITY','competition_age_groups','{"PLUS_1":["U8","O8"],"PLUS_2":["U9","O9"],"PLUS_3":["U10","O10"],"PLUS_4":["U11","O11"],"PLUS_5":["U12","O12"],"PLUS_6":["U13","U14","O14"],"PLUS_7":["U14","O14"],"PLUS_1_TEAMS":["OPEN"],"PLUS_2_3_TEAMS":["OPEN"],"PLUS_4_5_TEAMS":["OPEN"],"PLUS_6_7_TEAMS":["OPEN"]}',13),
    ('gi25_plus_team_scoring','canonical_gi_wag_plus_2025_plus_v4_2026_02','ALL','ALL','COMPETITION','team_composition_and_scoring','{"teamsPerClubLimit":null,"teamSize":{"minimum":3,"maximum":5},"allFiveMayPerformEachApparatus":true,"countingScoresPerApparatus":3,"apparatusTotalsForFinalTeamScore":4}',11),
    ('gi25_plus_all_around','canonical_gi_wag_plus_2025_plus_v4_2026_02','ALL','ALL','COMPETITION','all_around_composition','{"PLUS_1":{"apparatusCount":4,"components":["VAULT","UNEVEN_BARS","BALANCE_BEAM","FLOOR_EXERCISE"],"physicalPreparation":false},"PLUS_2_TO_7":{"componentCount":5,"components":["VAULT","UNEVEN_BARS","BALANCE_BEAM","FLOOR_EXERCISE","PHYSICAL_PREPARATION"],"physicalPreparationScoreCountsForAllAround":true,"physicalPreparationChampionDeclared":false},"rankingRequiresAllComponents":true}',12),
    ('gi25_plus_routine_lengths','canonical_gi_wag_plus_2025_plus_v4_2026_02','ALL','ALL','COMPETITION','routine_lengths','{"PLUS_1_TO_7":{"beamSeconds":90,"floorSeconds":90},"vaultsPermitted":1}',15),
    ('gi25_plus_pp_2','canonical_gi_wag_plus_2025_plus_v4_2026_02','PHYSICAL_PREPARATION','PLUS_2','PRESCRIBED_ROUTINE','physical_preparation_routine','{"startValue":{"mode":"FIXED","total":13},"equipment":{"blockCm":60,"landingMats":[{"depthCm":20,"lengthM":2},{"depthCm":20}],"carpetHeightCm":5},"holdDefaultSeconds":2,"requirements":["JUMP_TO_BLOCK_40CM_HIGHER_LANDING_MECHANICS_DROP_OFF_HIGH_JUMP","RIGHT_LEG_HIP_MOBILITY_SEQUENCE","RIGHT_RELEVE_STORK_HOLD","RIGHT_HORIZONTAL_AIRPLANE_TO_T_HOLD","RIGHT_FORWARD_LUNGE_45_DEGREE_TRUNK_TURN","REPEAT_2_TO_5_LEFT_LEG","STRADDLE_PRESS_TO_HANDSTAND_HALF_PIROUETTE_TO_STRADDLE_HOLD","CONTROLLED_ROLL_DOWN_SHOULDER_LAT_MOBILITY_HOLD","DISH_ROLL_PRONE_GOAL_POST_THORACIC_SEQUENCE","SLOW_PRESS_UP_JUMP_THROUGH_PIKE_STAND","SPLIT_JUMP"],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',27),
    ('gi25_plus_pp_3','canonical_gi_wag_plus_2025_plus_v4_2026_02','PHYSICAL_PREPARATION','PLUS_3','PRESCRIBED_ROUTINE','physical_preparation_routine','{"startValue":{"mode":"FIXED","total":13},"equipment":{"blockCm":60,"landingMats":[{"depthCm":20,"lengthM":2},{"depthCm":20}],"carpetHeightCm":5},"holdDefaultSeconds":2,"requirements":["JUMP_TO_BLOCK_40CM_HIGHER_LANDING_MECHANICS_DROP_OFF_HIGH_JUMP","RIGHT_LEG_HIP_MOBILITY_SEQUENCE","RIGHT_RELEVE_STORK_HOLD","RIGHT_HORIZONTAL_AIRPLANE_TO_T_HOLD","RIGHT_FORWARD_LUNGE_45_DEGREE_TRUNK_TURN","REPEAT_2_TO_5_LEFT_LEG","STRADDLE_PRESS_TO_HANDSTAND_HALF_PIROUETTE_TO_STRADDLE_HOLD","CONTROLLED_ROLL_DOWN_SHOULDER_LAT_MOBILITY_HOLD","DISH_ROLL_PRONE_GOAL_POST_THORACIC_SEQUENCE","SLOW_PRESS_UP_JUMP_THROUGH_PIKE_STAND","SPLIT_JUMP"],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',27),
    ('gi25_plus_pp_4','canonical_gi_wag_plus_2025_plus_v4_2026_02','PHYSICAL_PREPARATION','PLUS_4','PRESCRIBED_ROUTINE','physical_preparation_routine','{"startValue":{"mode":"FIXED","total":13},"equipment":{"blockCm":60,"landingMats":[{"depthCm":20,"lengthM":2},{"depthCm":20}],"carpetHeightCm":5},"holdDefaultSeconds":2,"requirements":["JUMP_TO_BLOCK_40CM_HIGHER_LANDING_MECHANICS_DROP_OFF_HIGH_JUMP","RIGHT_LEG_HIP_MOBILITY_SEQUENCE","RIGHT_RELEVE_STORK_HOLD","RIGHT_HORIZONTAL_AIRPLANE_TO_T_HOLD","RIGHT_FORWARD_LUNGE_45_DEGREE_TRUNK_TURN","REPEAT_2_TO_5_LEFT_LEG","STRADDLE_PRESS_TO_HANDSTAND_HALF_PIROUETTE_TO_STRADDLE_HOLD","CONTROLLED_ROLL_DOWN_SHOULDER_LAT_MOBILITY_HOLD","DISH_ROLL_PRONE_GOAL_POST_THORACIC_SEQUENCE","SLOW_PRESS_UP_JUMP_THROUGH_PIKE_STAND","SPLIT_JUMP"],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',27),
    ('gi25_plus_pp_5','canonical_gi_wag_plus_2025_plus_v4_2026_02','PHYSICAL_PREPARATION','PLUS_5','PRESCRIBED_ROUTINE','physical_preparation_routine','{"startValue":{"mode":"FIXED","total":13},"equipment":{"blockCm":60,"landingMat":{"depthCm":20,"lengthM":2},"carpetHeightCm":5,"longJumpTargetM":1,"targetStartsCmFromBlock":50},"holdDefaultSeconds":2,"requirements":["JUMP_TO_60CM_BLOCK_DROP_OFF_LONG_JUMP_TO_1M_LINE_LANDING_MECHANICS","RIGHT_STRAIGHT_LEG_HIP_MOBILITY_SEQUENCE","RIGHT_RELEVE_STORK_HOLD","RIGHT_HORIZONTAL_AIRPLANE_WITH_45_DEGREE_ROTATION_BOTH_SIDES","RIGHT_FORWARD_LUNGE_TWO_QUARTER_TURNS","REPEAT_2_TO_5_LEFT_LEG","STRADDLE_HOLD","PRESS_TO_HANDSTAND_FULL_PIROUETTE_TO_STRADDLE_HOLD","SHOULDER_LAT_MOBILITY_HANDS_TO_FLOOR_HOLD","DISH_ROLL_PRONE_THORACIC_HOLD_5_SECONDS","TWO_SLOW_PRESS_UPS_JUMP_THROUGH_PIKE_STAND","SPLIT_JUMP"],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',28),
    ('gi25_plus_pp_6','canonical_gi_wag_plus_2025_plus_v4_2026_02','PHYSICAL_PREPARATION','PLUS_6','PRESCRIBED_ROUTINE','physical_preparation_routine','{"startValue":{"mode":"FIXED","total":13},"equipment":{"blockCm":60,"landingMat":{"depthCm":20,"lengthM":2},"carpetHeightCm":5,"longJumpTargetM":1,"targetStartsCmFromBlock":50},"holdDefaultSeconds":2,"requirements":["JUMP_TO_60CM_BLOCK_DROP_OFF_LONG_JUMP_TO_1M_LINE_LANDING_MECHANICS","RIGHT_STRAIGHT_LEG_HIP_MOBILITY_SEQUENCE","RIGHT_RELEVE_STORK_HOLD","RIGHT_HORIZONTAL_AIRPLANE_WITH_45_DEGREE_ROTATION_BOTH_SIDES","RIGHT_FORWARD_LUNGE_TWO_QUARTER_TURNS","REPEAT_2_TO_5_LEFT_LEG","STRADDLE_HOLD","PRESS_TO_HANDSTAND_FULL_PIROUETTE_TO_STRADDLE_HOLD","SHOULDER_LAT_MOBILITY_HANDS_TO_FLOOR_HOLD","DISH_ROLL_PRONE_THORACIC_HOLD_5_SECONDS","TWO_SLOW_PRESS_UPS_JUMP_THROUGH_PIKE_STAND","SPLIT_JUMP"],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',28),
    ('gi25_plus_pp_7','canonical_gi_wag_plus_2025_plus_v4_2026_02','PHYSICAL_PREPARATION','PLUS_7','PRESCRIBED_ROUTINE','physical_preparation_routine','{"startValue":{"mode":"FIXED","total":13},"equipment":{"blockCm":60,"landingMat":{"depthCm":20,"lengthM":2},"carpetHeightCm":5,"longJumpTargetM":1,"targetStartsCmFromBlock":50},"holdDefaultSeconds":2,"requirements":["JUMP_TO_60CM_BLOCK_DROP_OFF_LONG_JUMP_TO_1M_LINE_LANDING_MECHANICS","RIGHT_STRAIGHT_LEG_HIP_MOBILITY_SEQUENCE","RIGHT_RELEVE_STORK_HOLD","RIGHT_HORIZONTAL_AIRPLANE_WITH_45_DEGREE_ROTATION_BOTH_SIDES","RIGHT_FORWARD_LUNGE_TWO_QUARTER_TURNS","REPEAT_2_TO_5_LEFT_LEG","STRADDLE_HOLD","PRESS_TO_HANDSTAND_FULL_PIROUETTE_TO_STRADDLE_HOLD","SHOULDER_LAT_MOBILITY_HANDS_TO_FLOOR_HOLD","DISH_ROLL_PRONE_THORACIC_HOLD_5_SECONDS","TWO_SLOW_PRESS_UPS_JUMP_THROUGH_PIKE_STAND","SPLIT_JUMP"],"requirementDeductions":{"attemptedNotAchieved":{"deduction":0.5,"type":"NEUTRAL"},"notAttempted":{"deduction":1.5,"from":"START_VALUE"},"partNotAttempted":{"deduction":1,"from":"START_VALUE"}}}',28)
)
INSERT INTO "FigApparatusRule" ("id","packageId","apparatus","levelCode","ruleType","ruleKey","valueJson","sourcePage","verificationStatus")
SELECT "id","packageId","apparatus","levelCode","ruleType","ruleKey","valueJson","sourcePage",'VERIFIED' FROM "rules"
WHERE EXISTS (SELECT 1 FROM "RulesetPackage" p WHERE p."id"="rules"."packageId")
AND NOT EXISTS (SELECT 1 FROM "FigApparatusRule" e WHERE e."packageId"="rules"."packageId" AND e."apparatus"="rules"."apparatus" AND e."levelCode"="rules"."levelCode" AND e."ruleKey"="rules"."ruleKey");
