import {archiveGymnast,setGymnastLifecycleStatus} from "@/app/actions/core-coaching";
import {notFound} from "next/navigation";
import {AppShell} from "@/app/components/app-shell";
import {OverviewWidgets,type OverviewWidget} from "@/app/components/overview-widgets";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {gymnastScopeWhere} from "@/app/lib/coaching-scope";
import {assignGymnastProgramme,clearGymnastProgramme} from "@/app/actions/programmes";
import {assignGymnastRuleset,clearGymnastRuleset} from "@/app/actions/rulesets";
import {getGymnastRulesContext,rulesByApparatus} from "@/app/lib/rulesets/context";
import {readOverviewLayout} from "@/app/lib/widget-layout";
import {logServerTiming,startServerTiming} from "@/app/lib/server-performance";
import {setGymnastTrainingPriority,clearGymnastTrainingPriority} from "@/app/actions/training-priority";
import {PendingSubmitButton} from "@/app/components/pending-submit-button";
import Link from "next/link";
export const dynamic="force-dynamic";
const date=(d:Date)=>new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",year:"numeric"}).format(d);
const apparatus:Record<string,string>={VAULT:"Vault",BARS:"Uneven Bars",UNEVEN_BARS:"Uneven Bars",BEAM:"Balance Beam",BALANCE_BEAM:"Balance Beam",FLOOR:"Floor Exercise",FLOOR_EXERCISE:"Floor Exercise"};
export default async function GymnastOverview({params}:{params:Promise<{id:string}>}){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)notFound();const {id}=await params;
 const baseStartedAt=startServerTiming();
 const gymnast=await prisma.gymnast.findFirst({where:{id,...gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)},include:{groups:{include:{trainingGroup:true},orderBy:{joinedAt:"asc"}},programmeAssignments:{include:{programme:true,stage:true}},rulesetAssignments:{include:{program:true,level:true}},_count:{select:{trainingEvidence:{where:{session:{organisationId:c.organisation.id}}},testingResults:{where:{session:{organisationId:c.organisation.id}}},trainingAttendance:{where:{session:{organisationId:c.organisation.id},status:{not:"NOT_RECORDED"}}}}}}});
 if(!gymnast)notFound();
 logServerTiming("page.gymnast.base",baseStartedAt);
 const primary=gymnast.groups.find(x=>x.isPrimary),programmeContext=gymnast.programmeAssignments[0],rulesetContext=gymnast.rulesetAssignments[0];
 const canManage=c.access.canManageProgrammesAndMethodology;const programmeOutcomes=programmeContext?.stageId?await prisma.programmeStageOutcome.findMany({where:{organisationId:c.organisation.id,stageId:programmeContext.stageId,status:"ACTIVE"},select:{id:true,title:true,category:true,apparatus:true,emphasis:true,successEvidence:true},orderBy:{orderIndex:"asc"},take:12}):[];
 const contextStartedAt=startServerTiming();
 const [canonicalRules,recentEvidence,recentTests,routines,competitionEntries,preference,programmes,rulesets,currentPriority,priorityHistory,currentGoals,currentCulture]=await Promise.all([
  rulesetContext?getGymnastRulesContext(gymnast.id,c.organisation.id):Promise.resolve(null),
  prisma.trainingEvidence.findMany({where:{gymnastId:gymnast.id,session:{organisationId:c.organisation.id}},select:{id:true,outcome:true,recordedAt:true,block:{select:{title:true,apparatus:true}}},orderBy:{recordedAt:"desc"},take:5}),
  prisma.testingResult.findMany({where:{gymnastId:gymnast.id,session:{organisationId:c.organisation.id}},select:{id:true,numberValue:true,recordedAt:true,metric:{select:{name:true,unit:true}}},orderBy:{recordedAt:"desc"},take:5}),
  prisma.gymnastRoutine.findMany({where:{gymnastId:gymnast.id,status:"ACTIVE"},select:{id:true,apparatus:true,name:true},orderBy:{updatedAt:"desc"}}),
  prisma.competitionEntry.findMany({where:{gymnastId:gymnast.id,event:{organisationId:c.organisation.id}},select:{id:true,event:{select:{id:true,name:true,eventDate:true}}},orderBy:{updatedAt:"desc"},take:6}),
  prisma.membershipPresentationPreference.findUnique({where:{membershipId:c.membership.id}}),
  canManage?prisma.coachingProgramme.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},select:{id:true,name:true,stages:{where:{status:"ACTIVE"},select:{id:true,name:true},orderBy:{orderIndex:"asc"}}},orderBy:{name:"asc"}}):Promise.resolve([]),
  canManage?prisma.organisationRulesetAssignment.findMany({where:{organisationId:c.organisation.id},select:{programId:true,program:{select:{name:true,levels:{where:{status:"ACTIVE"},select:{id:true,name:true},orderBy:{orderIndex:"asc"}}}}}}):Promise.resolve([]),
  prisma.gymnastTrainingPriority.findFirst({where:{organisationId:c.organisation.id,gymnastId:gymnast.id,endedAt:null},orderBy:{startedAt:"desc"}}),
  prisma.gymnastTrainingPriority.findMany({where:{organisationId:c.organisation.id,gymnastId:gymnast.id},orderBy:{startedAt:"desc"},take:8}),
  prisma.gymnastGoal.findMany({where:{organisationId:c.organisation.id,gymnastId:gymnast.id,status:{in:["ACTIVE","PAUSED"]}},select:{id:true,title:true,status:true},orderBy:{createdAt:"desc"},take:6}),
  prisma.cultureAchievement.findMany({where:{organisationId:c.organisation.id,gymnastId:gymnast.id,endedAt:null,definition:{status:"ACTIVE"}},select:{id:true,definition:{select:{name:true,badgeLabel:true}}},orderBy:{awardedAt:"desc"},take:8})
 ]);
 logServerTiming("page.gymnast.context",contextStartedAt,{parallelQueries:12});
 const evidenceCount=gymnast._count.trainingEvidence,testCount=gymnast._count.testingResults,attendanceCount=gymnast._count.trainingAttendance;
 const apparatusContexts=rulesByApparatus(canonicalRules),sharedRuleCount=canonicalRules?.rules.filter(r=>r.apparatus==="ALL").length??0;
 const nextCompetition=[...competitionEntries].filter(x=>x.event.eventDate>=new Date()).sort((a,b)=>a.event.eventDate.getTime()-b.event.eventDate.getTime())[0]??null;
 const latestCompetition=[...competitionEntries].sort((a,b)=>b.event.eventDate.getTime()-a.event.eventDate.getTime())[0]??null;
 const priorityLabel:Record<string,string>={PRIMARY:"Primary",SECONDARY:"Secondary",EXPLORATORY:"Exploratory"};
 const card="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm";
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page">
  <a href={gymnast.groups.length?"/groups/"+(primary??gymnast.groups[0]).trainingGroupId:"/groups"} className="workspace-back">← {gymnast.groups.length?(primary??gymnast.groups[0]).trainingGroup.name:"My Groups"}</a>
  <div className="workspace-hero gymnast-hero"><div><p className="workspace-kicker">Gymnast overview</p><h1>{gymnast.name}</h1><p className="workspace-meta">{primary?"Primary group · "+primary.trainingGroup.name:gymnast.groups.length?"No primary group":"Currently unassigned" }</p></div>{programmeOutcomes.length>0&&<div className="mt-4 flex flex-wrap gap-2">{programmeOutcomes.slice(0,6).map(o=><span key={o.id} className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{o.title} · {o.emphasis.toLowerCase()}</span>)}</div>}<div className="workspace-actions"><a href={"/analysis?gymnast="+gymnast.id} className="workspace-button">Analysis</a><a href={"/gymnasts/"+gymnast.id+"/goals"} className="workspace-button">Goals</a><a href={"/gymnasts/"+gymnast.id+"/routines"} className="workspace-button workspace-button-primary">Routines</a></div></div>
  {(()=>{const small=(label:string,value:string|number,href:string)=><a href={href} className="overview-data-card"><p>{label}</p><strong>{value}</strong></a>,latestEvidence=recentEvidence[0],latestTest=recentTests[0];const widgets:OverviewWidget[]=[
   {id:"FOCUS",title:"Current focus",category:"Coaching",default:true,defaultSize:"L",small:small("Current focus",currentPriority?.focus??"No current priority","#training-priority"),medium:<a href="#training-priority" className="overview-data-card"><p>Current focus</p><strong>{currentPriority?.focus??"No current priority"}</strong><div>{currentPriority&&<><span>{priorityLabel[currentPriority.priority]??currentPriority.priority} priority</span><span>Coach-set · {date(currentPriority.startedAt)}</span></>}</div></a>},
   {id:"TRAINING",title:"Training",category:"Training",default:true,small:small("Training",evidenceCount+" records","/analysis?gymnast="+gymnast.id),medium:<a href={"/analysis?gymnast="+gymnast.id} className="overview-data-card"><p>Training</p><strong>{evidenceCount} evidence records</strong><div>{recentEvidence.slice(0,4).map(e=><span key={e.id}>{apparatus[e.block.apparatus??""]??e.block.title} · {e.outcome}</span>)}</div></a>},
   {id:"COMPETITION",title:"Competition",category:"Competition",default:true,small:small("Competition",nextCompetition?.event.name??latestCompetition?.event.name??"None","/competitions"),medium:<a href={nextCompetition?"/competitions/"+nextCompetition.event.id:latestCompetition?"/competitions/"+latestCompetition.event.id:"/competitions"} className="overview-data-card"><p>Competition</p><strong>{nextCompetition?.event.name??latestCompetition?.event.name??"No competition record"}</strong><div>{nextCompetition&&<span>Next · {date(nextCompetition.event.eventDate)}</span>}{!nextCompetition&&latestCompetition&&<span>Latest · {date(latestCompetition.event.eventDate)}</span>}</div></a>},
   {id:"DEVELOPMENT",title:"Development snapshot",category:"Evidence",default:true,small:small("Development",evidenceCount+testCount+" records","/analysis?gymnast="+gymnast.id),medium:<a href={"/analysis?gymnast="+gymnast.id} className="overview-data-card"><p>Development snapshot</p><strong>{evidenceCount+testCount} evidence records</strong><div><span>{evidenceCount} training · {testCount} testing</span><span>{routines.length} active routines</span></div></a>},
   {id:"ATHLETE_CONTEXT",title:"Athlete context",category:"Context",default:true,small:small("Athlete context",primary?.trainingGroup.name??"Unassigned","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Athlete context</p><strong>{primary?.trainingGroup.name??"No primary group"}</strong><div><span>{programmeContext?programmeContext.programme.name+(programmeContext.stage?" · "+programmeContext.stage.name:""):"No individual programme"}</span><span>{rulesetContext?rulesetContext.program.name+(rulesetContext.level?" · "+rulesetContext.level.name:""):"No ruleset assigned"}</span></div></a>},
   {id:"ATTENTION",title:"Worth your attention",category:"Evidence",default:true,small:small("Worth your attention",!recentEvidence.length&&!recentTests.length?"Limited evidence":"Review evidence","/analysis?gymnast="+gymnast.id),medium:<a href={"/analysis?gymnast="+gymnast.id} className="overview-data-card"><p>Worth your attention</p><strong>{!recentEvidence.length&&!recentTests.length?"Limited evidence":!recentTests.length?"Not recently assessed":"Evidence available"}</strong><div><span>{latestEvidence?"Training · "+date(latestEvidence.recordedAt):"No recent training evidence"}</span><span>{latestTest?"Testing · "+date(latestTest.recordedAt):"Not recently assessed"}</span></div></a>},
   {id:"ACTIVITY",title:"Recent activity",category:"Evidence",default:true,small:small("Recent activity",recentEvidence.length+recentTests.length,"/analysis?gymnast="+gymnast.id),medium:<a href={"/analysis?gymnast="+gymnast.id} className="overview-data-card"><p>Recent activity</p><strong>{recentEvidence.length+recentTests.length?"Evidence captured":"No recent evidence"}</strong><div>{recentEvidence.slice(0,2).map(e=><span key={e.id}>Training · {e.outcome} · {date(e.recordedAt)}</span>)}{recentTests.slice(0,2).map(t=><span key={t.id}>Testing · {t.metric.name} · {date(t.recordedAt)}</span>)}</div></a>},
   {id:"GOALS",title:"Goals",category:"Coaching",default:true,small:small("Goals",currentGoals.length?currentGoals.length+" current":"No current goals","/gymnasts/"+gymnast.id+"/goals"),medium:<a href={"/gymnasts/"+gymnast.id+"/goals"} className="overview-data-card"><p>Goals</p><strong>{currentGoals.length?currentGoals.length+" current":"No current goals"}</strong><div>{currentGoals.slice(0,3).map(g=><span key={g.id}>{g.title}{g.status==="PAUSED"?" · paused":""}</span>)}</div></a>},
   {id:"CULTURE",title:"Culture",category:"Context",default:true,small:small("Culture",currentCulture.length?currentCulture.length+" current":"No current recognition","/culture?gymnast="+gymnast.id),medium:<a href={"/culture?gymnast="+gymnast.id} className="overview-data-card"><p>Culture</p><strong>{currentCulture.length?currentCulture.length+" current":"No current recognition"}</strong><div>{currentCulture.slice(0,4).map(x=><span key={x.id}>{x.definition.badgeLabel??x.definition.name}</span>)}</div></a>},
   {id:"NEXT",title:"Next session",category:"Schedule",default:false,small:small("Next session",primary?.trainingGroup.name??"No primary group","/planning"),medium:<Link href="/planning" className="overview-data-card"><p>Next session</p><strong>{primary?.trainingGroup.name??"No primary group"}</strong><div><span>Open Planning</span></div></Link>},
   {id:"SCHEDULE",title:"Schedule",category:"Schedule",default:false,small:small("Schedule",gymnast.groups.length+" groups","/calendar"),medium:<a href="/calendar" className="overview-data-card"><p>Schedule</p><strong>{gymnast.groups.length} group{gymnast.groups.length===1?"":"s"}</strong><div>{gymnast.groups.slice(0,4).map(g=><span key={g.trainingGroupId}>{g.trainingGroup.name}</span>)}</div></a>},
   {id:"TESTING",title:"Testing",category:"Evidence",default:false,small:small("Testing",testCount,"/testing/results?gymnast="+gymnast.id),medium:<a href={"/testing/results?gymnast="+gymnast.id} className="overview-data-card"><p>Testing</p><strong>{testCount} results</strong><div>{recentTests.slice(0,3).map(t=><span key={t.id}>{t.metric.name} · {t.numberValue}{t.metric.unit?" "+t.metric.unit:""}</span>)}</div></a>},
   {id:"ROUTINES",title:"Routines",category:"Technical",default:false,small:small("Routines",routines.length,"/gymnasts/"+gymnast.id+"/routines"),medium:<a href={"/gymnasts/"+gymnast.id+"/routines"} className="overview-data-card"><p>Routines</p><strong>{routines.length} active</strong><div>{routines.slice(0,4).map(r=><span key={r.id}>{apparatus[r.apparatus]??r.apparatus} · {r.name}</span>)}</div></a>},
   {id:"VAULT",title:"Vault",category:"Technical",default:false,small:small("Vault",routines.filter(r=>r.apparatus==="VAULT").length,"/gymnasts/"+gymnast.id+"/routines"),medium:<a href={"/gymnasts/"+gymnast.id+"/routines"} className="overview-data-card"><p>Vault</p><strong>{routines.filter(r=>r.apparatus==="VAULT").length?"Active vault routine":"No active vault routine"}</strong></a>},
   {id:"ROUTINE_EVIDENCE",title:"Routine evidence",category:"Technical",default:false,small:small("Routine evidence",evidenceCount,"/analysis?gymnast="+gymnast.id),medium:<a href={"/analysis?gymnast="+gymnast.id} className="overview-data-card"><p>Routine evidence</p><strong>{evidenceCount} training records</strong></a>},
   {id:"COMPETITION_HISTORY",title:"Competition history",category:"Competition",default:false,small:small("Competition history",competitionEntries.length,"/competitions"),medium:<Link href="/competitions" className="overview-data-card"><p>Competition history</p><strong>{competitionEntries.length} entries</strong><div>{competitionEntries.slice(0,3).map(e=><span key={e.id}>{e.event.name} · {date(e.event.eventDate)}</span>)}</div></Link>},
   {id:"PATHWAY",title:"Programme / pathway",category:"Context",default:false,small:small("Programme / pathway",programmeContext?.programme.name??"Group context","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Programme / pathway</p><strong>{programmeContext?.programme.name??"Uses group context"}</strong>{programmeContext?.stage&&<div><span>{programmeContext.stage.name}</span></div>}</a>},
   {id:"RULESET",title:"Ruleset",category:"Context",default:false,small:small("Ruleset",rulesetContext?.program.name??"Not assigned","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Ruleset</p><strong>{rulesetContext?.program.name??"Not assigned"}</strong><div>{rulesetContext?.level&&<span>{rulesetContext.level.name}</span>}{canonicalRules&&<span>{canonicalRules.rules.length} verified rules</span>}</div></a>},
   {id:"ATTENDANCE",title:"Attendance",category:"Training",default:false,small:small("Attendance",attendanceCount,"/training"),medium:<Link href="/training" className="overview-data-card"><p>Attendance</p><strong>{attendanceCount} recorded sessions</strong></Link>},
   {id:"VOLUME",title:"Training volume",category:"Training",default:false,small:small("Training volume",evidenceCount+" evidence","/analysis?gymnast="+gymnast.id),medium:<a href={"/analysis?gymnast="+gymnast.id} className="overview-data-card"><p>Training volume</p><strong>{evidenceCount} evidence records</strong><div><span>Across recorded training history</span></div></a>},
   {id:"COACH_TEAM",title:"Coach team",category:"Coaching",default:false,small:small("Coach team",gymnast.groups.length+" group links","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Coach team</p><strong>{gymnast.groups.length} group context{gymnast.groups.length===1?"":"s"}</strong></a>},
   {id:"EVIDENCE_COVERAGE",title:"Evidence coverage",category:"Evidence",default:false,small:small("Evidence coverage",evidenceCount+testCount,"/analysis?gymnast="+gymnast.id),medium:<a href={"/analysis?gymnast="+gymnast.id} className="overview-data-card"><p>Evidence coverage</p><strong>{evidenceCount+testCount?"Evidence available":"Limited evidence"}</strong><div><span>{evidenceCount} training · {testCount} testing</span></div></a>}
  ];return <div className="mt-7"><OverviewWidgets surface="GYMNAST" initialLayout={readOverviewLayout(preference,"GYMNAST")} widgets={widgets}/></div>})()}
  <details id="manage-gymnast" className="management-panel mt-8"><summary>Manage gymnast</summary>
  <div className="mt-6 grid gap-5 lg:grid-cols-2">
   <article className={card}><h2 className="font-semibold">Programme context</h2><p className="mt-2 text-sm text-[var(--muted)]">{programmeContext?programmeContext.programme.name+(programmeContext.stage?" · "+programmeContext.stage.name:""):"Uses group context unless an individual pathway is assigned"}</p>{c.access.canManageProgrammesAndMethodology&&<div className="mt-4 flex flex-wrap gap-2"><form action={assignGymnastProgramme} className="flex flex-wrap gap-2"><input type="hidden" name="gymnastId" value={gymnast.id}/><select name="programmeId" required className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">Programme…</option>{programmes.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="stageId" className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">No stage</option>{programmes.flatMap(p=>p.stages.map(s=><option key={s.id} value={s.id}>{p.name} · {s.name}</option>))}</select><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Assign individual pathway</button></form>{programmeContext&&<form action={clearGymnastProgramme}><input type="hidden" name="gymnastId" value={gymnast.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Use group context</button></form>}</div>}</article>
   <article><h2 className="font-semibold">Ruleset</h2><p className="mt-2 text-sm text-[var(--muted)]">{rulesetContext?rulesetContext.program.name+(rulesetContext.level?" · "+rulesetContext.level.name:""):"Not yet assigned"}</p>{canonicalRules&&<div className="mt-4 rounded-xl border border-[var(--border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold">Verified canonical context</p><p className="mt-1 text-xs text-[var(--muted)]">{canonicalRules.package.name} · {canonicalRules.package.versionLabel}</p></div><span className="rounded-full border border-[var(--border)] px-3 py-1 text-xs font-semibold">{canonicalRules.rules.length} verified rules</span></div><div className="mt-3 flex flex-wrap gap-2">{sharedRuleCount>0&&<span className="rounded-full border border-[var(--border)] px-2 py-1 text-xs">Shared · {sharedRuleCount}</span>}{apparatusContexts.map(x=><span key={x.apparatus} className="rounded-full border border-[var(--border)] px-2 py-1 text-xs">{x.label} · {x.specificRuleCount}</span>)}</div></div>}{rulesetContext&&!canonicalRules&&<p className="mt-4 rounded-xl border border-dashed border-[var(--border)] p-3 text-sm text-[var(--muted)]">This assignment does not yet resolve to a verified canonical rules package.</p>}{c.access.canManageProgrammesAndMethodology&&<div className="mt-4 flex flex-wrap gap-2"><form action={assignGymnastRuleset} className="flex flex-wrap gap-2"><input type="hidden" name="gymnastId" value={gymnast.id}/><select name="rulesetAssignment" required className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">Ruleset and level…</option>{rulesets.map(r=><optgroup key={r.programId} label={r.program.name}>{r.program.levels.length?r.program.levels.map(l=><option key={l.id} value={r.programId+":"+l.id}>{l.name}</option>):<option value={r.programId+":"}>No level</option>}</optgroup>)}</select><PendingSubmitButton pendingLabel="Assigning…" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold disabled:opacity-60">Assign ruleset</PendingSubmitButton></form>{rulesetContext&&<form action={clearGymnastRuleset}><input type="hidden" name="gymnastId" value={gymnast.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Clear</button></form>}</div>}</article>
  </div>
  <article id="training-priority" className={"mt-5 "+card}><p className="workspace-kicker">Training Priority</p><h2 className="mt-1 font-semibold">Coach-set current focus</h2><p className="mt-2 text-sm text-[var(--muted)]">Priority describes coaching intent. It is separate from evidence, Athlete State and readiness, and Viaform does not infer it automatically.</p>{currentPriority?<div className="mt-4 rounded-xl border border-[var(--border)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{currentPriority.focus}</strong><span className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{priorityLabel[currentPriority.priority]??currentPriority.priority}</span></div>{currentPriority.rationale&&<p className="mt-2 text-sm">{currentPriority.rationale}</p>}<p className="mt-2 text-xs text-[var(--muted)]">Since {date(currentPriority.startedAt)}</p></div>:<p className="mt-4 text-sm text-[var(--muted)]">No current priority.</p>}<form action={setGymnastTrainingPriority} className="mt-4 grid gap-2 md:grid-cols-[160px_1fr]"><input type="hidden" name="gymnastId" value={gymnast.id}/><select name="priority" required className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="PRIMARY">Primary</option><option value="SECONDARY">Secondary</option><option value="EXPLORATORY">Exploratory</option></select><input name="focus" required placeholder="Current coaching focus" className="rounded-lg border border-[var(--border)] px-3 py-2"/><textarea name="rationale" placeholder="Coach rationale / context (optional)" className="rounded-lg border border-[var(--border)] px-3 py-2 md:col-span-2"/><button className="workspace-button md:col-span-2 md:w-fit">Set priority</button></form>{currentPriority&&<form action={clearGymnastTrainingPriority} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="gymnastId" value={gymnast.id}/><input name="reason" placeholder="Why this priority ended (optional)" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm"/><button className="text-sm text-[var(--muted)]">No current priority</button></form>}{priorityHistory.length>0&&<details className="mt-4 border-t border-[var(--border)] pt-3"><summary className="cursor-pointer text-sm font-semibold">Priority history</summary><div className="mt-3 grid gap-2">{priorityHistory.map(p=><div key={p.id} className="rounded-lg border border-[var(--border)] p-3 text-sm"><strong>{p.focus??"Priority"}</strong><span className="ml-2 text-xs text-[var(--muted)]">{priorityLabel[p.priority]??p.priority} · {date(p.startedAt)}{p.endedAt?" → "+date(p.endedAt):" · current"}</span>{p.endReason&&<p className="mt-1 text-xs text-[var(--muted)]">{p.endReason.replaceAll("_"," ").toLowerCase()}</p>}</div>)}</div></details>}</article>
  <article className={"mt-5 "+card}><h2 className="font-semibold">Groups</h2><div className="mt-4 flex flex-wrap gap-2">{gymnast.groups.length?gymnast.groups.map(g=><a key={g.trainingGroupId} href={"/groups/"+g.trainingGroupId} className="rounded-full border border-[var(--border)] px-3 py-2 text-sm font-medium">{g.trainingGroup.name}{g.isPrimary?" · primary":""}</a>):<span className="text-sm text-[var(--muted)]">No group memberships yet.</span>}</div></article>
   {c.access.canManagePeopleAndRoles&&<article className={"mt-5 "+card}><h2 className="font-semibold">Lifecycle</h2><p className="mt-2 text-sm text-[var(--muted)]">Inactive and transferred gymnasts leave active coaching surfaces while their history is preserved. Archive is for longer-term record retention.</p><div className="mt-3 flex flex-wrap gap-2"><form action={setGymnastLifecycleStatus}><input type="hidden" name="gymnastId" value={gymnast.id}/><input type="hidden" name="status" value="INACTIVE"/><button className="workspace-button">Mark inactive</button></form><form action={setGymnastLifecycleStatus}><input type="hidden" name="gymnastId" value={gymnast.id}/><input type="hidden" name="status" value="TRANSFERRED"/><button className="workspace-button">Mark transferred</button></form></div><form action={archiveGymnast} className="mt-3"><input type="hidden" name="gymnastId" value={gymnast.id}/><button className="workspace-button">Archive gymnast</button></form></article>}
  </details>
 </section></AppShell>;
}
