import {notFound} from "next/navigation";
import {AppShell} from "@/app/components/app-shell";
import {OverviewWidgets,type OverviewWidget} from "@/app/components/overview-widgets";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {gymnastScopeWhere} from "@/app/lib/coaching-scope";
import {assignGymnastProgramme,clearGymnastProgramme} from "@/app/actions/programmes";
import {assignGymnastRuleset,clearGymnastRuleset} from "@/app/actions/rulesets";
import {getGymnastRulesContext,rulesByApparatus} from "@/app/lib/rulesets/context";
import {readOverviewLayout} from "@/app/lib/widget-layout";
export const dynamic="force-dynamic";
const date=(d:Date)=>new Intl.DateTimeFormat("en-IE",{day:"numeric",month:"short",year:"numeric"}).format(d);
const apparatus:Record<string,string>={VAULT:"Vault",BARS:"Uneven Bars",UNEVEN_BARS:"Uneven Bars",BEAM:"Balance Beam",BALANCE_BEAM:"Balance Beam",FLOOR:"Floor Exercise",FLOOR_EXERCISE:"Floor Exercise"};
export default async function GymnastOverview({params}:{params:Promise<{id:string}>}){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)notFound();const {id}=await params;
 const gymnast=await prisma.gymnast.findFirst({where:{id,...gymnastScopeWhere(c.organisation.id,c.membership.id,c.access)},include:{groups:{include:{trainingGroup:true},orderBy:{joinedAt:"asc"}},programmeAssignments:{include:{programme:true,stage:true}},rulesetAssignments:{include:{program:true,level:true}}}});
 if(!gymnast)notFound();
 const primary=gymnast.groups.find(x=>x.isPrimary),programmeContext=gymnast.programmeAssignments[0],rulesetContext=gymnast.rulesetAssignments[0];
 const canonicalRules=rulesetContext?await getGymnastRulesContext(gymnast.id,c.organisation.id):null,apparatusContexts=rulesByApparatus(canonicalRules),sharedRuleCount=canonicalRules?.rules.filter(r=>r.apparatus==="ALL").length??0;
 const [recentEvidence,recentTests,routines,competitionEntries,evidenceCount,testCount,preference,attendanceCount]=await Promise.all([
  prisma.trainingEvidence.findMany({where:{gymnastId:gymnast.id,session:{organisationId:c.organisation.id}},include:{session:{select:{id:true,title:true,sessionDate:true}},block:{select:{title:true,apparatus:true}}},orderBy:{recordedAt:"desc"},take:5}),
  prisma.testingResult.findMany({where:{gymnastId:gymnast.id,session:{organisationId:c.organisation.id}},include:{metric:true,session:true},orderBy:{recordedAt:"desc"},take:5}),
  prisma.gymnastRoutine.findMany({where:{gymnastId:gymnast.id,status:"ACTIVE"},include:{_count:{select:{elements:true,vaults:true,customItems:true}}},orderBy:{updatedAt:"desc"}}),
  prisma.competitionEntry.findMany({where:{gymnastId:gymnast.id,event:{organisationId:c.organisation.id}},include:{event:true,apparatusPlans:{include:{performance:true}}},orderBy:{updatedAt:"desc"},take:6}),
  prisma.trainingEvidence.count({where:{gymnastId:gymnast.id,session:{organisationId:c.organisation.id}}}),
  prisma.testingResult.count({where:{gymnastId:gymnast.id,session:{organisationId:c.organisation.id}}}),
  prisma.membershipPresentationPreference.findUnique({where:{membershipId:c.membership.id}}),
  prisma.trainingAttendance.count({where:{gymnastId:gymnast.id,session:{organisationId:c.organisation.id},status:{not:"NOT_RECORDED"}}})
 ]);
 const programmes=c.access.canManageProgrammesAndMethodology?await prisma.coachingProgramme.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},include:{stages:{where:{status:"ACTIVE"},orderBy:{orderIndex:"asc"}}},orderBy:{name:"asc"}}):[];
 const rulesets=c.access.canManageProgrammesAndMethodology?await prisma.organisationRulesetAssignment.findMany({where:{organisationId:c.organisation.id},include:{program:{include:{levels:{where:{status:"ACTIVE"},orderBy:{orderIndex:"asc"}}}}}}):[];
 const nextCompetition=[...competitionEntries].filter(x=>x.event.eventDate>=new Date()).sort((a,b)=>a.event.eventDate.getTime()-b.event.eventDate.getTime())[0]??null;
 const latestCompetition=[...competitionEntries].sort((a,b)=>b.event.eventDate.getTime()-a.event.eventDate.getTime())[0]??null;
 const card="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm";
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page">
  <a href={gymnast.groups.length?"/groups/"+(primary??gymnast.groups[0]).trainingGroupId:"/groups"} className="workspace-back">← {gymnast.groups.length?(primary??gymnast.groups[0]).trainingGroup.name:"My Groups"}</a>
  <div className="workspace-hero gymnast-hero"><div><p className="workspace-kicker">Gymnast overview</p><h1>{gymnast.name}</h1><p className="workspace-meta">{primary?"Primary group · "+primary.trainingGroup.name:gymnast.groups.length?"No primary group":"Currently unassigned" }</p></div><div className="workspace-actions"><a href={"/progress?gymnast="+gymnast.id} className="workspace-button">Progress</a><a href={"/gymnasts/"+gymnast.id+"/routines"} className="workspace-button workspace-button-primary">Routines</a></div></div>
  {(()=>{const small=(label:string,value:string|number,href:string)=><a href={href} className="overview-data-card"><p>{label}</p><strong>{value}</strong></a>,latestEvidence=recentEvidence[0],latestTest=recentTests[0];const widgets:OverviewWidget[]=[
   {id:"FOCUS",title:"Current focus",category:"Coaching",default:true,defaultSize:"L",small:small("Current focus",latestEvidence?apparatus[latestEvidence.block.apparatus??""]??latestEvidence.block.title:"No recent evidence","/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Current focus</p><strong>{latestEvidence?apparatus[latestEvidence.block.apparatus??""]??latestEvidence.block.title:"No recent evidence"}</strong><div>{latestEvidence&&<span>{latestEvidence.outcome} · {date(latestEvidence.recordedAt)}</span>}</div></a>},
   {id:"TRAINING",title:"Training",category:"Training",default:true,small:small("Training",evidenceCount+" records","/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Training</p><strong>{evidenceCount} evidence records</strong><div>{recentEvidence.slice(0,4).map(e=><span key={e.id}>{apparatus[e.block.apparatus??""]??e.block.title} · {e.outcome}</span>)}</div></a>},
   {id:"COMPETITION",title:"Competition",category:"Competition",default:true,small:small("Competition",nextCompetition?.event.name??latestCompetition?.event.name??"None","/competitions"),medium:<a href={nextCompetition?"/competitions/"+nextCompetition.event.id:latestCompetition?"/competitions/"+latestCompetition.event.id:"/competitions"} className="overview-data-card"><p>Competition</p><strong>{nextCompetition?.event.name??latestCompetition?.event.name??"No competition record"}</strong><div>{nextCompetition&&<span>Next · {date(nextCompetition.event.eventDate)}</span>}{!nextCompetition&&latestCompetition&&<span>Latest · {date(latestCompetition.event.eventDate)}</span>}</div></a>},
   {id:"DEVELOPMENT",title:"Development snapshot",category:"Evidence",default:true,small:small("Development",evidenceCount+testCount+" records","/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Development snapshot</p><strong>{evidenceCount+testCount} evidence records</strong><div><span>{evidenceCount} training · {testCount} testing</span><span>{routines.length} active routines</span></div></a>},
   {id:"ATHLETE_CONTEXT",title:"Athlete context",category:"Context",default:true,small:small("Athlete context",primary?.trainingGroup.name??"Unassigned","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Athlete context</p><strong>{primary?.trainingGroup.name??"No primary group"}</strong><div><span>{programmeContext?programmeContext.programme.name+(programmeContext.stage?" · "+programmeContext.stage.name:""):"No individual programme"}</span><span>{rulesetContext?rulesetContext.program.name+(rulesetContext.level?" · "+rulesetContext.level.name:""):"No ruleset assigned"}</span></div></a>},
   {id:"ATTENTION",title:"Worth your attention",category:"Evidence",default:true,small:small("Worth your attention",!recentEvidence.length&&!recentTests.length?"Limited evidence":"Review evidence","/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Worth your attention</p><strong>{!recentEvidence.length&&!recentTests.length?"Limited evidence":!recentTests.length?"Not recently assessed":"Evidence available"}</strong><div><span>{latestEvidence?"Training · "+date(latestEvidence.recordedAt):"No recent training evidence"}</span><span>{latestTest?"Testing · "+date(latestTest.recordedAt):"Not recently assessed"}</span></div></a>},
   {id:"ACTIVITY",title:"Recent activity",category:"Evidence",default:true,small:small("Recent activity",recentEvidence.length+recentTests.length,"/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Recent activity</p><strong>{recentEvidence.length+recentTests.length?"Evidence captured":"No recent evidence"}</strong><div>{recentEvidence.slice(0,2).map(e=><span key={e.id}>Training · {e.outcome} · {date(e.recordedAt)}</span>)}{recentTests.slice(0,2).map(t=><span key={t.id}>Testing · {t.metric.name} · {date(t.recordedAt)}</span>)}</div></a>},
   {id:"GOALS",title:"Goals",category:"Coaching",default:true,small:small("Goals","No goals recorded","/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Goals</p><strong>No goals recorded</strong></a>},
   {id:"NEXT",title:"Next session",category:"Schedule",default:false,small:small("Next session",primary?.trainingGroup.name??"No primary group","/planning"),medium:<a href="/planning" className="overview-data-card"><p>Next session</p><strong>{primary?.trainingGroup.name??"No primary group"}</strong><div><span>Open Planning</span></div></a>},
   {id:"SCHEDULE",title:"Schedule",category:"Schedule",default:false,small:small("Schedule",gymnast.groups.length+" groups","/calendar"),medium:<a href="/calendar" className="overview-data-card"><p>Schedule</p><strong>{gymnast.groups.length} group{gymnast.groups.length===1?"":"s"}</strong><div>{gymnast.groups.slice(0,4).map(g=><span key={g.trainingGroupId}>{g.trainingGroup.name}</span>)}</div></a>},
   {id:"TESTING",title:"Testing",category:"Evidence",default:false,small:small("Testing",testCount,"/testing"),medium:<a href="/testing" className="overview-data-card"><p>Testing</p><strong>{testCount} results</strong><div>{recentTests.slice(0,3).map(t=><span key={t.id}>{t.metric.name} · {t.numberValue}{t.metric.unit?" "+t.metric.unit:""}</span>)}</div></a>},
   {id:"ROUTINES",title:"Routines",category:"Technical",default:false,small:small("Routines",routines.length,"/gymnasts/"+gymnast.id+"/routines"),medium:<a href={"/gymnasts/"+gymnast.id+"/routines"} className="overview-data-card"><p>Routines</p><strong>{routines.length} active</strong><div>{routines.slice(0,4).map(r=><span key={r.id}>{apparatus[r.apparatus]??r.apparatus} · {r.name}</span>)}</div></a>},
   {id:"VAULT",title:"Vault",category:"Technical",default:false,small:small("Vault",routines.filter(r=>r.apparatus==="VAULT").length,"/gymnasts/"+gymnast.id+"/routines"),medium:<a href={"/gymnasts/"+gymnast.id+"/routines"} className="overview-data-card"><p>Vault</p><strong>{routines.filter(r=>r.apparatus==="VAULT").length?"Active vault routine":"No active vault routine"}</strong></a>},
   {id:"ROUTINE_EVIDENCE",title:"Routine evidence",category:"Technical",default:false,small:small("Routine evidence",evidenceCount,"/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Routine evidence</p><strong>{evidenceCount} training records</strong></a>},
   {id:"COMPETITION_HISTORY",title:"Competition history",category:"Competition",default:false,small:small("Competition history",competitionEntries.length,"/competitions"),medium:<a href="/competitions" className="overview-data-card"><p>Competition history</p><strong>{competitionEntries.length} entries</strong><div>{competitionEntries.slice(0,3).map(e=><span key={e.id}>{e.event.name} · {date(e.event.eventDate)}</span>)}</div></a>},
   {id:"PATHWAY",title:"Programme / pathway",category:"Context",default:false,small:small("Programme / pathway",programmeContext?.programme.name??"Group context","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Programme / pathway</p><strong>{programmeContext?.programme.name??"Uses group context"}</strong>{programmeContext?.stage&&<div><span>{programmeContext.stage.name}</span></div>}</a>},
   {id:"RULESET",title:"Ruleset",category:"Context",default:false,small:small("Ruleset",rulesetContext?.program.name??"Not assigned","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Ruleset</p><strong>{rulesetContext?.program.name??"Not assigned"}</strong><div>{rulesetContext?.level&&<span>{rulesetContext.level.name}</span>}{canonicalRules&&<span>{canonicalRules.rules.length} verified rules</span>}</div></a>},
   {id:"ATTENDANCE",title:"Attendance",category:"Training",default:false,small:small("Attendance",attendanceCount,"/training"),medium:<a href="/training" className="overview-data-card"><p>Attendance</p><strong>{attendanceCount} recorded sessions</strong></a>},
   {id:"VOLUME",title:"Training volume",category:"Training",default:false,small:small("Training volume",evidenceCount+" evidence","/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Training volume</p><strong>{evidenceCount} evidence records</strong><div><span>Across recorded training history</span></div></a>},
   {id:"COACH_TEAM",title:"Coach team",category:"Coaching",default:false,small:small("Coach team",gymnast.groups.length+" group links","#manage-gymnast"),medium:<a href="#manage-gymnast" className="overview-data-card"><p>Coach team</p><strong>{gymnast.groups.length} group context{gymnast.groups.length===1?"":"s"}</strong></a>},
   {id:"EVIDENCE_COVERAGE",title:"Evidence coverage",category:"Evidence",default:false,small:small("Evidence coverage",evidenceCount+testCount,"/progress?gymnast="+gymnast.id),medium:<a href={"/progress?gymnast="+gymnast.id} className="overview-data-card"><p>Evidence coverage</p><strong>{evidenceCount+testCount?"Evidence available":"Limited evidence"}</strong><div><span>{evidenceCount} training · {testCount} testing</span></div></a>}
  ];return <div className="mt-7"><OverviewWidgets surface="GYMNAST" initialLayout={readOverviewLayout(preference,"GYMNAST")} widgets={widgets}/></div>})()}
  <details id="manage-gymnast" className="management-panel mt-8"><summary>Manage gymnast</summary>
  <div className="mt-6 grid gap-5 lg:grid-cols-2">
   <article className={card}><h2 className="font-semibold">Programme context</h2><p className="mt-2 text-sm text-[var(--muted)]">{programmeContext?programmeContext.programme.name+(programmeContext.stage?" · "+programmeContext.stage.name:""):"Uses group context unless an individual pathway is assigned"}</p>{c.access.canManageProgrammesAndMethodology&&<div className="mt-4 flex flex-wrap gap-2"><form action={assignGymnastProgramme} className="flex flex-wrap gap-2"><input type="hidden" name="gymnastId" value={gymnast.id}/><select name="programmeId" required className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">Programme…</option>{programmes.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="stageId" className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">No stage</option>{programmes.flatMap(p=>p.stages.map(s=><option key={s.id} value={s.id}>{p.name} · {s.name}</option>))}</select><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Assign individual pathway</button></form>{programmeContext&&<form action={clearGymnastProgramme}><input type="hidden" name="gymnastId" value={gymnast.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Use group context</button></form>}</div>}</article>
   <article><h2 className="font-semibold">Ruleset</h2><p className="mt-2 text-sm text-[var(--muted)]">{rulesetContext?rulesetContext.program.name+(rulesetContext.level?" · "+rulesetContext.level.name:""):"Not yet assigned"}</p>{canonicalRules&&<div className="mt-4 rounded-xl border border-[var(--border)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold">Verified canonical context</p><p className="mt-1 text-xs text-[var(--muted)]">{canonicalRules.package.name} · {canonicalRules.package.versionLabel}</p></div><span className="rounded-full border border-[var(--border)] px-3 py-1 text-xs font-semibold">{canonicalRules.rules.length} verified rules</span></div><div className="mt-3 flex flex-wrap gap-2">{sharedRuleCount>0&&<span className="rounded-full border border-[var(--border)] px-2 py-1 text-xs">Shared · {sharedRuleCount}</span>}{apparatusContexts.map(x=><span key={x.apparatus} className="rounded-full border border-[var(--border)] px-2 py-1 text-xs">{x.label} · {x.specificRuleCount}</span>)}</div></div>}{rulesetContext&&!canonicalRules&&<p className="mt-4 rounded-xl border border-dashed border-[var(--border)] p-3 text-sm text-[var(--muted)]">This assignment does not yet resolve to a verified canonical rules package.</p>}{c.access.canManageProgrammesAndMethodology&&<div className="mt-4 flex flex-wrap gap-2"><form action={assignGymnastRuleset} className="flex flex-wrap gap-2"><input type="hidden" name="gymnastId" value={gymnast.id}/><select name="rulesetAssignment" required className="rounded-lg border border-[var(--border)] px-3 py-2"><option value="">Ruleset and level…</option>{rulesets.map(r=><optgroup key={r.programId} label={r.program.name}>{r.program.levels.length?r.program.levels.map(l=><option key={l.id} value={r.programId+":"+l.id}>{l.name}</option>):<option value={r.programId+":"}>No level</option>}</optgroup>)}</select><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Assign ruleset</button></form>{rulesetContext&&<form action={clearGymnastRuleset}><input type="hidden" name="gymnastId" value={gymnast.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Clear</button></form>}</div>}</article>
  </div>
  <article className={"mt-5 "+card}><h2 className="font-semibold">Groups</h2><div className="mt-4 flex flex-wrap gap-2">{gymnast.groups.length?gymnast.groups.map(g=><a key={g.trainingGroupId} href={"/groups/"+g.trainingGroupId} className="rounded-full border border-[var(--border)] px-3 py-2 text-sm font-medium">{g.trainingGroup.name}{g.isPrimary?" · primary":""}</a>):<span className="text-sm text-[var(--muted)]">No group memberships yet.</span>}</div></article>
  </details>
 </section></AppShell>;
}