import { notFound } from "next/navigation";
import { AppShell } from "@/app/components/app-shell";
import { acknowledgeCollaborationNote, createCollaborationNote, resolveCollaborationNote } from "@/app/actions/collaboration";
import { requireAuthContext } from "@/app/lib/auth";
import { groupScopeWhere, gymnastScopeWhere } from "@/app/lib/coaching-scope";
import { prisma } from "@/app/lib/prisma";

export const dynamic="force-dynamic";
const roleLabels:Record<string,string>={HEAD_COACH:"Head Coach",COMPETITIVE_COACH:"Competitive Coach",RECREATIONAL_COACH:"Recreational Coach",PROGRAMME_LEAD:"Programme Lead",SPECIALIST_COACH:"Specialist Coach",CHOREOGRAPHER:"Choreographer",JUDGE:"Judge"};
const roles=(raw:string|null)=>{try{const x=JSON.parse(raw??"[]");return Array.isArray(x)?x.map(String):[]}catch{return []}};
const when=(d:Date)=>new Intl.DateTimeFormat("en-IE",{dateStyle:"medium",timeStyle:"short"}).format(d);

export default async function CollaborationPage(){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)notFound();
 const [members,gymnasts,groups,notes]=await Promise.all([
  prisma.organisationMembership.findMany({where:{organisationId:c.organisation.id,isActive:true,id:{not:c.membership.id}},include:{user:true},orderBy:{user:{displayName:"asc"}}}),
  prisma.gymnast.findMany({where:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access),select:{id:true,name:true},orderBy:{name:"asc"}}),
  prisma.trainingGroup.findMany({where:groupScopeWhere(c.organisation.id,c.membership.id,c.access),select:{id:true,name:true},orderBy:{name:"asc"}}),
  prisma.coachCollaborationNote.findMany({where:{organisationId:c.organisation.id,...(c.access.canViewAllCoachingData?{}:{OR:[{authorMembershipId:c.membership.id},{recipientMembershipId:c.membership.id}]})},include:{author:{include:{user:true}},recipient:{include:{user:true}},resolvedBy:{include:{user:true}},gymnast:true,trainingGroup:true},orderBy:{createdAt:"desc"},take:80})
 ]);
 const incoming=notes.filter(n=>n.recipientMembershipId===c.membership.id&&n.status==="OPEN"),outgoing=notes.filter(n=>n.authorMembershipId===c.membership.id&&n.status==="OPEN"),resolved=notes.filter(n=>n.status==="RESOLVED");
 const Card=({note}:{note:(typeof notes)[number]})=>{const incomingToMe=note.recipientMembershipId===c.membership.id,authorRoles=roles(note.authorRoleSnapshot).map(r=>roleLabels[r]??r);return <article className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{incomingToMe?"From "+note.author.user.displayName:"To "+note.recipient.user.displayName}</p><p className="mt-1 text-xs text-[var(--muted)]">{authorRoles.length?authorRoles.join(" · ")+" · ":""}{when(note.createdAt)}</p></div><div className="flex gap-2"><span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] font-semibold">{note.status}</span>{note.priority==="IMPORTANT"&&<span className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px] font-semibold">IMPORTANT</span>}</div></div>{(note.gymnast||note.trainingGroup)&&<p className="mt-3 text-xs font-semibold text-[var(--muted)]">{note.gymnast?"Gymnast · "+note.gymnast.name:"Group · "+note.trainingGroup?.name}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6">{note.message}</p>{note.acknowledgedAt&&note.status==="OPEN"&&<p className="mt-2 text-xs text-[var(--muted)]">Acknowledged {when(note.acknowledgedAt)}</p>}{note.status==="RESOLVED"&&<p className="mt-2 text-xs text-[var(--muted)]">Resolved{note.resolvedBy?" by "+note.resolvedBy.user.displayName:""}{note.resolvedAt?" · "+when(note.resolvedAt):""}</p>}<div className="mt-3 flex gap-2">{incomingToMe&&note.status==="OPEN"&&!note.acknowledgedAt&&<form action={acknowledgeCollaborationNote}><input type="hidden" name="noteId" value={note.id}/><button className="workspace-button">Acknowledge</button></form>}{note.status==="OPEN"&&(incomingToMe||note.authorMembershipId===c.membership.id)&&<form action={resolveCollaborationNote}><input type="hidden" name="noteId" value={note.id}/><button className="workspace-button">Resolve</button></form>}</div></article>};
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><a href="/more" className="workspace-back">← More</a><div className="workspace-hero"><div><p className="workspace-kicker">Club collaboration</p><h1>Coaching coordination</h1><p className="workspace-meta">Durable notes attached to the work — not a club-wide chat feed.</p></div><div className="workspace-actions"><a href="/handoffs" className="workspace-button">Coach handoffs</a></div></div>
 <details className="mt-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><summary className="cursor-pointer font-semibold">+ Send collaboration note</summary><form action={createCollaborationNote} className="mt-4 grid gap-3"><div className="grid gap-3 md:grid-cols-2"><select name="recipientMembershipId" required className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="">Coach…</option>{members.map(m=><option key={m.id} value={m.id}>{m.user.displayName}</option>)}</select><select name="priority" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="NORMAL">Normal</option><option value="IMPORTANT">Important</option></select></div><div className="grid gap-3 md:grid-cols-2"><select name="gymnastId" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="">No gymnast context</option>{gymnasts.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select name="trainingGroupId" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="">No group context</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><textarea name="message" required maxLength={4000} placeholder="Coaching context, question, observation or action that should stay attached to the work" className="min-h-28 rounded-xl border border-[var(--border)] px-3 py-3"/><button className="workspace-button workspace-button-primary w-fit">Send note</button></form></details>
 <div className="mt-8 grid gap-5 xl:grid-cols-2"><section><div className="section-heading"><h2>Needs your attention</h2><span>{incoming.length}</span></div><div className="mt-3 grid gap-3">{incoming.map(n=><Card key={n.id} note={n}/>)}{!incoming.length&&<p className="rounded-xl border border-dashed border-[var(--border)] p-5 text-sm text-[var(--muted)]">No open collaboration notes waiting for you.</p>}</div></section><section><div className="section-heading"><h2>Sent by you</h2><span>{outgoing.length}</span></div><div className="mt-3 grid gap-3">{outgoing.map(n=><Card key={n.id} note={n}/>)}{!outgoing.length&&<p className="rounded-xl border border-dashed border-[var(--border)] p-5 text-sm text-[var(--muted)]">No open notes sent by you.</p>}</div></section></div>
 <section className="mt-8"><div className="section-heading"><h2>Recently resolved</h2><span>{resolved.length}</span></div><div className="mt-3 grid gap-3 lg:grid-cols-2">{resolved.slice(0,20).map(n=><Card key={n.id} note={n}/>)}{!resolved.length&&<p className="text-sm text-[var(--muted)]">No resolved collaboration notes yet.</p>}</div></section>
 </section></AppShell>;
}
