import {AppShell} from "@/app/components/app-shell";
import {setPresentationTheme} from "@/app/actions/preferences";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
export const dynamic="force-dynamic";
const themes=[
 {id:"REFINED",name:"Refined",detail:"Quiet, clear and neutral. Keeps the coaching information visually dominant.",swatches:["#142b3a","#ffffff","#f5f7f8"]},
 {id:"BOLD",name:"Bold",detail:"A stronger Viaform identity with a confident pink accent while keeping content surfaces clear.",swatches:["#c42d70","#fff7fb","#251827"]},
 {id:"FOCUS",name:"Focus",detail:"Reduced visual contrast around navigation for long planning, routine and review sessions.",swatches:["#334155","#f8fafc","#e2e8f0"]},
] as const;
export default async function AppearancePage(){const c=await requireAuthContext();const p=await prisma.membershipPresentationPreference.findUnique({where:{membershipId:c.membership.id}});const selected=p?.theme??"REFINED";return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section><a href="/more" className="text-sm font-semibold text-[var(--muted)]">← More</a><p className="mt-5 text-sm font-semibold text-[var(--muted)]">Presentation</p><h1 className="mt-2 text-3xl font-semibold">Your Viaform</h1><p className="mt-3 max-w-3xl leading-7 text-[var(--muted)]">Choose how Viaform is presented to you. Theme choices affect presentation only; coaching records, evidence and access do not change.</p><div className="mt-8 grid gap-4 lg:grid-cols-3">{themes.map(t=><form action={setPresentationTheme} key={t.id} className={"rounded-2xl border bg-[var(--surface)] p-5 shadow-sm "+(selected===t.id?"border-[var(--accent)] ring-2 ring-[var(--accent-soft)]":"border-[var(--border)]")}><input type="hidden" name="theme" value={t.id}/><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{t.name}</h2>{selected===t.id&&<span className="rounded-full bg-[var(--accent-soft)] px-3 py-1 text-xs font-semibold">Current</span>}</div><div className="mt-4 flex gap-2">{t.swatches.map(x=><span key={x} className="h-8 w-8 rounded-full border border-black/10" style={{background:x}}/>)}</div><p className="mt-4 min-h-16 text-sm leading-6 text-[var(--muted)]">{t.detail}</p><button className="mt-4 rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-semibold">{selected===t.id?"Keep theme":"Use "+t.name}</button></form>)}</div><article className="mt-6 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Overview layout</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Home widget order, visibility and width are already saved to this Viaform membership. Use <strong>Arrange overview</strong> on Home to change them.</p><a href="/dashboard" className="mt-4 inline-block text-sm font-semibold">Open Home →</a></article></section></AppShell>}