import Link from "next/link";
import {AppShell} from "@/app/components/app-shell";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {gymnastScopeWhere} from "@/app/lib/coaching-scope";
import {logServerTiming} from "@/app/lib/server-performance";
export const dynamic="force-dynamic";
const fmt=(d:Date|null)=>d?d.toLocaleDateString("en-IE",{day:"numeric",month:"short",year:"numeric"}):"No dated evidence yet";
export default async function SkillLibrary({searchParams}:{searchParams:Promise<{q?:string;mode?:string;skill?:string;gymnast?:string}>}){
 const started=Date.now(),c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return null;
 const p=await searchParams,q=(p.q??"").trim().slice(0,80),mode=p.mode==="gymnasts"?"gymnasts":"skills",scope=gymnastScopeWhere(c.organisation.id,c.membership.id,c.access);
 const historicalOrganisationIds=(p.skill||p.gymnast||(mode==="gymnasts"&&q.length>=2))?(await prisma.historicalOrganisationAccess.findMany({where:{userId:c.loginUser.id,revokedAt:null,organisation:{status:"ARCHIVED"}},select:{organisationId:true},take:100})).map(x=>x.organisationId):[];
 const accessibleGymnastWhere={OR:[scope,...(historicalOrganisationIds.length?[{organisationId:{in:historicalOrganisationIds},status:"ARCHIVED"}]:[])]};
 const skills=mode==="skills"&&!p.skill&&!p.gymnast&&q.length>=2?await prisma.viaformSkill.findMany({where:{discipline:"WAG",status:"ACTIVE",OR:[{name:{contains:q}},{aliases:{contains:q}},{canonicalKey:{contains:q}}]},select:{id:true,name:true,apparatus:true,provenance:true},orderBy:{name:"asc"},take:20}):[];
 const gymnasts=mode==="gymnasts"&&!p.skill&&!p.gymnast&&q.length>=2?await prisma.gymnast.findMany({where:{AND:[accessibleGymnastWhere,{name:{contains:q}}]},select:{id:true,name:true,organisation:{select:{name:true,status:true}}},orderBy:{name:"asc"},take:20}):[];
 const selectedSkill=p.skill?await prisma.viaformSkill.findFirst({where:{id:p.skill,status:"ACTIVE"},select:{id:true,name:true,apparatus:true,gymnastSkills:{where:{status:"ACTIVE",gymnast:accessibleGymnastWhere},select:{latestEvidenceAt:true,gymnast:{select:{id:true,name:true}}},orderBy:{latestEvidenceAt:"desc"},take:100}}}):null;
 const gymnast=p.gymnast?await prisma.gymnast.findFirst({where:{AND:[accessibleGymnastWhere,{id:p.gymnast}]},select:{id:true,name:true,skillLibrary:{where:{status:"ACTIVE"},select:{id:true,latestEvidenceAt:true,skill:{select:{id:true,name:true,apparatus:true}}},orderBy:{latestEvidenceAt:"desc"},take:200}}}):null;
 logServerTiming("skills.library",started,{mode:p.skill?"skill-detail":p.gymnast?"gymnast-detail":mode,queried:q.length>=2});
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><Link href="/more" className="workspace-back">← More</Link><div className="workspace-hero"><div><p className="workspace-kicker">Skill Library</p><h1>Skill Library</h1><p className="workspace-meta">Search a skill to see accessible gymnasts, or search a gymnast to explore their longitudinal skills. Detailed evidence stays on demand.</p></div></div>
 <div className="mt-5 flex gap-2"><Link className={"workspace-button "+(mode==="skills"?"workspace-button-primary":"")} href="/skills?mode=skills">Search skills</Link><Link className={"workspace-button "+(mode==="gymnasts"?"workspace-button-primary":"")} href="/skills?mode=gymnasts">Search gymnasts</Link></div>
 {!p.skill&&!p.gymnast&&<form className="mt-4 flex max-w-2xl gap-2"><input type="hidden" name="mode" value={mode}/><input name="q" defaultValue={q} minLength={2} maxLength={80} placeholder={mode==="skills"?"Search canonical skills…":"Search accessible gymnasts…"} className="min-w-0 flex-1 rounded-lg border border-[var(--border)] px-3 py-2"/><button className="workspace-button workspace-button-primary">Search</button></form>}
 {mode==="skills"&&q.length>=2&&!p.skill&&!p.gymnast&&<section className="mt-7"><div className="section-heading"><h2>Skills</h2><span>{skills.length}</span></div><div className="mt-3 grid gap-2">{skills.map(s=><Link key={s.id} href={"/skills?skill="+encodeURIComponent(s.id)} className="workspace-row"><div><strong>{s.name}</strong><span>{s.apparatus.replaceAll("_"," ").toLowerCase()} · {s.provenance}</span></div><b>→</b></Link>)}{!skills.length&&<div className="empty-state">No matching canonical skills.</div>}</div></section>}
 {mode==="gymnasts"&&q.length>=2&&!p.skill&&!p.gymnast&&<section className="mt-7"><div className="section-heading"><h2>Gymnasts</h2><span>{gymnasts.length}</span></div><div className="mt-3 grid gap-2">{gymnasts.map(g=><Link key={g.id} href={"/skills?gymnast="+encodeURIComponent(g.id)} className="workspace-row"><div><strong>{g.name}</strong><span>{g.organisation.status==="ARCHIVED"?g.organisation.name+" · historical":"Current organisation"} · Open skill library</span></div><b>→</b></Link>)}{!gymnasts.length&&<div className="empty-state">No matching accessible gymnasts.</div>}</div></section>}
 {selectedSkill&&<section className="mt-7"><div className="section-heading"><h2>{selectedSkill.name}</h2><span>{selectedSkill.gymnastSkills.length} gymnasts</span></div><p className="mt-1 text-sm text-[var(--muted)]">{selectedSkill.apparatus.replaceAll("_"," ").toLowerCase()} · up to 100 accessible relationships</p><div className="mt-3 grid gap-2">{selectedSkill.gymnastSkills.map(x=><Link key={x.gymnast.id} href={"/skills?gymnast="+encodeURIComponent(x.gymnast.id)} className="workspace-row"><div><strong>{x.gymnast.name}</strong><span>{fmt(x.latestEvidenceAt)}</span></div><b>→</b></Link>)}{!selectedSkill.gymnastSkills.length&&<div className="empty-state">No accessible gymnasts linked yet.</div>}</div></section>}
 {gymnast&&<section className="mt-7"><div className="section-heading"><h2>{gymnast.name}</h2><span>{gymnast.skillLibrary.length} skills</span></div><p className="mt-1 text-sm text-[var(--muted)]">Skill relationships are durable; detailed evidence remains in its original source.</p><div className="mt-3 grid gap-2">{gymnast.skillLibrary.map(x=><Link key={x.id} href={"/skills?skill="+encodeURIComponent(x.skill.id)} className="workspace-row"><div><strong>{x.skill.name}</strong><span>{x.skill.apparatus.replaceAll("_"," ").toLowerCase()} · {fmt(x.latestEvidenceAt)}</span></div><b>→</b></Link>)}{!gymnast.skillLibrary.length&&<div className="empty-state">No canonical skills linked yet.</div>}</div></section>}
 {!q&&!selectedSkill&&!gymnast&&<div className="empty-state mt-7">Search to begin. Viaform does not load the club-wide skill graph on page open.</div>}</section></AppShell>;
}