import { AppShell } from "@/app/components/app-shell";
import { requireAuthContext } from "@/app/lib/auth";
import { groupScopeWhere } from "@/app/lib/coaching-scope";
import { prisma } from "@/app/lib/prisma";
export const dynamic="force-dynamic";
const fmt=(d:Date)=>new Intl.DateTimeFormat("en-IE",{dateStyle:"medium"}).format(d);
export default async function UpdatesPage(){
 const c=await requireAuthContext(),now=new Date(),week=new Date(Date.now()+7*86400000),fortnight=new Date(Date.now()+14*86400000);
 const canReview=c.access.isHeadCoach||c.access.coachingRoles.includes("PROGRAMME_LEAD");
 const [incoming,outgoing,reviews,sessions,competitions]=await Promise.all([
  c.access.canUseCoachingWorkspace?prisma.coachHandoff.findMany({where:{organisationId:c.organisation.id,toMembershipId:c.membership.id,status:"ACTIVE"},include:{fromMembership:{include:{user:true}},trainingGroup:true},orderBy:{endsAt:"asc"},take:12}):Promise.resolve([]),
  c.access.canUseCoachingWorkspace?prisma.coachHandoff.findMany({where:{organisationId:c.organisation.id,fromMembershipId:c.membership.id,status:"ACTIVE"},include:{toMembership:{include:{user:true}}},orderBy:{endsAt:"asc"},take:12}):Promise.resolve([]),
  canReview?prisma.methodologyRecord.findMany({where:{organisationId:c.organisation.id,status:"IN_REVIEW"},include:{createdBy:{include:{user:true}}},orderBy:{updatedAt:"asc"},take:12}):Promise.resolve([]),
  c.access.canUseCoachingWorkspace?prisma.trainingSession.findMany({where:{organisationId:c.organisation.id,sessionDate:{gte:now,lte:week},trainingGroup:groupScopeWhere(c.organisation.id,c.membership.id,c.access)},include:{trainingGroup:true},orderBy:[{sessionDate:"asc"},{startTime:"asc"}],take:20}):Promise.resolve([]),
  c.access.canUseCoachingWorkspace?prisma.competitionEvent.findMany({where:{organisationId:c.organisation.id,eventDate:{gte:now,lte:fortnight},status:{in:["PLANNED","IN_PROGRESS"]}},orderBy:{eventDate:"asc"},take:12}):Promise.resolve([])
 ]);
 const attention=incoming.length+reviews.length;
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><a href="/more" className="workspace-back">← More</a><div className="workspace-hero"><div><p className="workspace-kicker">Updates</p><h1>Operational digest</h1><p className="workspace-meta">{attention} need attention · {sessions.length} sessions · {competitions.length} competitions</p></div></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[var(--border)] p-4"><p className="text-xs font-semibold text-[var(--muted)]">Needs attention</p><p className="mt-1 text-2xl font-semibold">{attention}</p></div><div className="rounded-2xl border border-[var(--border)] p-4"><p className="text-xs font-semibold text-[var(--muted)]">Sessions · next 7 days</p><p className="mt-1 text-2xl font-semibold">{sessions.length}</p></div><div className="rounded-2xl border border-[var(--border)] p-4"><p className="text-xs font-semibold text-[var(--muted)]">Competitions · next 14 days</p><p className="mt-1 text-2xl font-semibold">{competitions.length}</p></div></div>
  <div className="mt-8 grid gap-5 lg:grid-cols-2">
   <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-lg font-semibold">Attention</h2><div className="mt-4 grid gap-3">{incoming.map(h=><a key={h.id} href="/handoffs" className="rounded-xl border border-[var(--border)] p-3 text-sm"><strong>Cover handoff from {h.fromMembership.user.displayName}</strong><span className="mt-1 block text-[var(--muted)]">{h.title}{h.endsAt?" · until "+fmt(h.endsAt):" · open-ended"}</span></a>)}{reviews.map(r=><a key={r.id} href="/methodology" className="rounded-xl border border-[var(--border)] p-3 text-sm"><strong>Methodology awaiting review</strong><span className="mt-1 block text-[var(--muted)]">{r.title} · {r.createdBy.user.displayName}</span></a>)}{!attention&&<p className="text-sm text-[var(--muted)]">Nothing currently needs your attention.</p>}</div></article>
   <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-lg font-semibold">Your active handoffs</h2><div className="mt-4 grid gap-3">{outgoing.map(h=><a key={h.id} href="/handoffs" className="rounded-xl border border-[var(--border)] p-3 text-sm"><strong>{h.title}</strong><span className="mt-1 block text-[var(--muted)]">Cover: {h.toMembership.user.displayName}{h.endsAt?" · until "+fmt(h.endsAt):""}</span></a>)}{!outgoing.length&&<p className="text-sm text-[var(--muted)]">No active handoffs you created.</p>}</div></article>
   <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-lg font-semibold">Next 7 days</h2><div className="mt-4 grid gap-3">{sessions.map(s=><a key={s.id} href={s.status==="LIVE"||s.status==="COMPLETED"?"/training/"+s.id:"/planning/"+s.id} className="rounded-xl border border-[var(--border)] p-3 text-sm"><strong>{s.trainingGroup.name} · {s.title}</strong><span className="mt-1 block text-[var(--muted)]">{fmt(s.sessionDate)} · {s.startTime}–{s.endTime} · {s.status}</span></a>)}{!sessions.length&&<p className="text-sm text-[var(--muted)]">No visible planned sessions in the next 7 days.</p>}</div></article>
   <article className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-lg font-semibold">Competition horizon</h2><div className="mt-4 grid gap-3">{competitions.map(e=><a key={e.id} href={"/competitions/"+e.id} className="rounded-xl border border-[var(--border)] p-3 text-sm"><strong>{e.name}</strong><span className="mt-1 block text-[var(--muted)]">{fmt(e.eventDate)} · {e.eventType==="CONTROL"?"Control competition":"External competition"} · {e.status}</span></a>)}{!competitions.length&&<p className="text-sm text-[var(--muted)]">No active competitions in the next 14 days.</p>}</div></article>
  </div>
 </section></AppShell>;
}