import { AppShell } from "@/app/components/app-shell";
import { approveMethodologyRecord, archiveMethodologyRecord, createMethodologyRecord, returnMethodologyToDraft, submitMethodologyForReview, updateMethodologyRecord } from "@/app/actions/methodology";
import { requireAuthContext } from "@/app/lib/auth";
import { prisma } from "@/app/lib/prisma";

export const dynamic="force-dynamic";
const provenanceLabel:Record<string,string>={COACH_METHODOLOGY:"Coach methodology",CLUB_PROGRAMME:"Club programme",TRUSTED_CONTRIBUTOR:"Trusted contributor",SPECIALIST:"Specialist",GYMNAST_SPECIFIC_COACH_DECISION:"Gymnast-specific coach decision"};
export default async function MethodologyPage(){
 const c=await requireAuthContext();
 const [records,programmes]=await Promise.all([
  prisma.methodologyRecord.findMany({where:{organisationId:c.organisation.id,status:{not:"ARCHIVED"}},include:{createdBy:{include:{user:true}},approvedBy:{include:{user:true}},programme:true},orderBy:{updatedAt:"desc"}}),
  prisma.coachingProgramme.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},orderBy:{name:"asc"}})
 ]);
 const canPropose=c.access.canUseCoachingWorkspace,canReview=c.access.isHeadCoach||c.access.coachingRoles.includes("PROGRAMME_LEAD");
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section>
  <a href="/more" className="text-sm font-semibold text-[var(--muted)]">← More</a><p className="mt-5 text-sm font-semibold text-[var(--muted)]">Methodology</p><h1 className="mt-2 text-3xl font-semibold">Club coaching methodology</h1>
  <p className="mt-3 max-w-3xl leading-7 text-[var(--muted)]">Preserve coaching approaches with their source, boundaries and uncertainty. Ruleset facts remain in the canonical rules layer; methodology does not override them. Multiple approaches can coexist without Viaform choosing a winner.</p>
  {canPropose&&<details className="mt-7 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><summary className="cursor-pointer font-semibold">+ Propose methodology</summary><form action={createMethodologyRecord} className="mt-4 grid gap-3">
   <div className="grid gap-3 md:grid-cols-3"><input name="title" required placeholder="Methodology title" className="rounded-xl border border-[var(--border)] px-3 py-3"/><select name="scopeType" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="GLOBAL">Global</option><option value="APPARATUS">Apparatus</option><option value="PROGRAMME">Programme</option><option value="ROUTINE_CONTEXT">Routine context</option><option value="MOVEMENT_FAMILY">Movement family</option></select><input name="scopeRef" placeholder="Scope reference / label" className="rounded-xl border border-[var(--border)] px-3 py-3"/></div>
   <div className="grid gap-3 md:grid-cols-3"><input name="apparatus" placeholder="Apparatus (optional)" className="rounded-xl border border-[var(--border)] px-3 py-3"/><select name="provenance" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="COACH_METHODOLOGY">Coach methodology</option><option value="CLUB_PROGRAMME">Club programme</option><option value="TRUSTED_CONTRIBUTOR">Trusted contributor</option><option value="SPECIALIST">Specialist</option><option value="GYMNAST_SPECIFIC_COACH_DECISION">Gymnast-specific coach decision</option></select><select name="programmeId" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="">No programme link</option>{programmes.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
   <input name="contributorName" placeholder="Contributor / source name (when relevant)" className="rounded-xl border border-[var(--border)] px-3 py-3"/>
   <textarea name="technicalObjective" placeholder="Technical objective" className="min-h-20 rounded-xl border border-[var(--border)] px-3 py-3"/><textarea name="technicalBoundaries" placeholder="Technical boundaries / when this applies" className="min-h-20 rounded-xl border border-[var(--border)] px-3 py-3"/><textarea name="defaultApproach" placeholder="Default coaching approach" className="min-h-24 rounded-xl border border-[var(--border)] px-3 py-3"/><textarea name="alternativeApproaches" placeholder="Alternative approaches worth preserving" className="min-h-20 rounded-xl border border-[var(--border)] px-3 py-3"/><textarea name="uncertainty" placeholder="Uncertainty / open questions" className="min-h-20 rounded-xl border border-[var(--border)] px-3 py-3"/>
   <div className="grid gap-3 md:grid-cols-2"><input name="sourceNote" placeholder="Source note" className="rounded-xl border border-[var(--border)] px-3 py-3"/><input name="sourceUrl" type="url" placeholder="Source URL (optional)" className="rounded-xl border border-[var(--border)] px-3 py-3"/></div><button className="w-fit rounded-xl bg-[var(--foreground)] px-4 py-3 text-sm font-semibold text-white">Save draft</button>
  </form></details>}
  <div className="mt-8 grid gap-4">{records.map(r=><article key={r.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{r.title}</h2><p className="mt-1 text-xs text-[var(--muted)]">{provenanceLabel[r.provenance]??r.provenance} · {r.scopeType}{r.apparatus?" · "+r.apparatus:""}{r.programme?" · "+r.programme.name:""} · proposed by {r.createdBy.user.displayName}</p></div><span className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{r.status.replaceAll("_"," ")}</span></div>
   {r.technicalObjective&&<p className="mt-4 text-sm"><strong>Objective:</strong> {r.technicalObjective}</p>}{r.defaultApproach&&<p className="mt-2 text-sm leading-6">{r.defaultApproach}</p>}{r.alternativeApproaches&&<p className="mt-2 text-sm text-[var(--muted)]"><strong>Alternative approaches:</strong> {r.alternativeApproaches}</p>}{r.technicalBoundaries&&<p className="mt-2 text-sm text-[var(--muted)]"><strong>Boundaries:</strong> {r.technicalBoundaries}</p>}{r.uncertainty&&<p className="mt-2 text-sm text-[var(--muted)]"><strong>Open question:</strong> {r.uncertainty}</p>}
   {r.status!=="APPROVED"&&(r.createdByMembershipId===c.membership.id||canReview)&&<details className="mt-4 border-t border-[var(--border)] pt-4"><summary className="cursor-pointer text-sm font-semibold">Edit working record</summary><form action={updateMethodologyRecord} className="mt-3 grid gap-2"><input type="hidden" name="recordId" value={r.id}/><textarea name="technicalObjective" defaultValue={r.technicalObjective??""} placeholder="Technical objective" className="rounded-lg border border-[var(--border)] px-3 py-2"/><textarea name="technicalBoundaries" defaultValue={r.technicalBoundaries??""} placeholder="Technical boundaries" className="rounded-lg border border-[var(--border)] px-3 py-2"/><textarea name="defaultApproach" defaultValue={r.defaultApproach??""} placeholder="Default approach" className="rounded-lg border border-[var(--border)] px-3 py-2"/><textarea name="alternativeApproaches" defaultValue={r.alternativeApproaches??""} placeholder="Alternative approaches" className="rounded-lg border border-[var(--border)] px-3 py-2"/><textarea name="uncertainty" defaultValue={r.uncertainty??""} placeholder="Uncertainty" className="rounded-lg border border-[var(--border)] px-3 py-2"/><input name="sourceNote" defaultValue={r.sourceNote??""} placeholder="Source note" className="rounded-lg border border-[var(--border)] px-3 py-2"/><input name="sourceUrl" defaultValue={r.sourceUrl??""} placeholder="Source URL" className="rounded-lg border border-[var(--border)] px-3 py-2"/><button className="w-fit rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Save working record</button></form></details>}
   <div className="mt-4 flex flex-wrap gap-2">{r.status==="DRAFT"&&r.createdByMembershipId===c.membership.id&&<form action={submitMethodologyForReview}><input type="hidden" name="recordId" value={r.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Submit for review</button></form>}{r.status==="IN_REVIEW"&&canReview&&<form action={returnMethodologyToDraft}><input type="hidden" name="recordId" value={r.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Return to draft</button></form>}{r.status==="IN_REVIEW"&&c.access.isHeadCoach&&<form action={approveMethodologyRecord}><input type="hidden" name="recordId" value={r.id}/><button className="rounded-lg bg-[var(--foreground)] px-3 py-2 text-sm font-semibold text-white">Approve club methodology</button></form>}{(c.access.isHeadCoach||r.createdByMembershipId===c.membership.id)&&<form action={archiveMethodologyRecord}><input type="hidden" name="recordId" value={r.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Archive</button></form>}</div>
   {r.approvedBy&&<p className="mt-3 text-xs text-[var(--muted)]">Approved by {r.approvedBy.user.displayName}{r.approvedAt?" · "+r.approvedAt.toLocaleDateString("en-IE"):""}</p>}
  </article>)}{!records.length&&<p className="rounded-2xl border border-dashed border-[var(--border)] p-6 text-sm text-[var(--muted)]">No club methodology records yet.</p>}</div>
 </section></AppShell>;
}
