import {AppShell} from "@/app/components/app-shell";
import {createImportBatch,registerImportSource,stageImportCandidate,reviewImportCandidate,executeApprovedImportCandidate} from "@/app/actions/imports";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {redirect} from "next/navigation";
export const dynamic="force-dynamic";
const day=(d:Date)=>d.toISOString().slice(0,10);
export default async function Imports(){
 const c=await requireAuthContext();if(!c.access.canManagePeopleAndRoles)redirect("/more");
 const historical=await prisma.historicalOrganisationAccess.findMany({where:{userId:c.loginUser.id,revokedAt:null,organisation:{status:"ARCHIVED"}},include:{organisation:true},orderBy:{organisation:{name:"asc"}}});
 const organisationIds=[c.organisation.id,...historical.map(h=>h.organisationId)];
 const batches=await prisma.importBatch.findMany({where:{organisationId:{in:organisationIds}},include:{organisation:{select:{name:true,status:true}},sources:{orderBy:{createdAt:"asc"}},candidates:{orderBy:{createdAt:"asc"}},recordLinks:{where:{rolledBackAt:null},select:{candidateId:true,createdAt:true}},_count:{select:{recordLinks:true}}},orderBy:{createdAt:"desc"},take:30});
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page">
  <a href="/more" className="workspace-back">← More</a>
  <div className="workspace-hero"><div><p className="workspace-kicker">Organisation · Import</p><h1>Import workspace</h1><p className="workspace-meta">Discover, classify and review historical material before anything is written into Viaform records.</p></div></div>
  <section className="mt-8 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Start an import batch</h2><p className="mt-1 text-sm text-[var(--muted)]">Use one stable key for the same source set so a migration can be resumed without creating a second batch.</p><form action={createImportBatch} className="mt-4 grid gap-2 md:grid-cols-5"><select name="organisationId" defaultValue={c.organisation.id}><option value={c.organisation.id}>{c.organisation.name} · current</option>{historical.map(h=><option key={h.id} value={h.organisationId}>{h.organisation.name} · archived history</option>)}</select><input name="name" required placeholder="e.g. Longford · Ruby pilot"/><select name="sourceKind" required defaultValue="MIXED_FILES"><option value="MIXED_FILES">Mixed files</option><option value="GOOGLE_DRIVE">Google Drive</option><option value="LOCAL_ARCHIVE">Local archive / ZIP</option><option value="SPREADSHEET">Spreadsheet</option><option value="DOCUMENTS">Documents</option></select><input name="idempotencyKey" required placeholder="Stable source key"/><button className="workspace-button workspace-button-primary">Create batch</button></form></section>
  <div className="mt-8 grid gap-5">{batches.map(b=><article key={b.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="workspace-kicker">{b.status.replaceAll("_"," ")}</p><h2 className="text-xl font-semibold">{b.name}</h2><p className="mt-1 text-sm text-[var(--muted)]">{b.organisation.name} · {b.organisation.status.toLowerCase()} · {b.sourceKind.replaceAll("_"," ")} · started {day(b.startedAt)} · key {b.idempotencyKey}</p></div><div className="text-sm text-[var(--muted)]">{b.sources.length} sources · {b.candidates.length} candidates · {b._count.recordLinks} imported links</div></div>
   <details className="mt-5 border-t border-[var(--border)] pt-4"><summary className="cursor-pointer font-semibold">+ Register source</summary><form action={registerImportSource} className="mt-3 grid gap-2 md:grid-cols-4"><input type="hidden" name="batchId" value={b.id}/><input name="name" required placeholder="File or folder name"/><input name="sourceKey" required placeholder="Stable source key"/><select name="sourceType" defaultValue="FILE"><option value="FILE">File</option><option value="FOLDER">Folder</option><option value="WORKBOOK">Workbook</option><option value="DOCUMENT">Document</option><option value="PDF">PDF</option></select><input name="externalRef" placeholder="Source reference / path"/><button className="workspace-button">Register source</button></form></details>
   <details className="mt-4 border-t border-[var(--border)] pt-4"><summary className="cursor-pointer font-semibold">+ Stage candidate</summary><form action={stageImportCandidate} className="mt-3 grid gap-2"><input type="hidden" name="batchId" value={b.id}/><div className="grid gap-2 md:grid-cols-3"><select name="sourceId"><option value="">Batch-level / no single source</option>{b.sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="candidateKey" required placeholder="Stable candidate key"/><input name="sourceEntityKey" placeholder="Source identity key (optional)"/></div><div className="grid gap-2 md:grid-cols-3"><select name="entityType" defaultValue="GYMNAST"><option>GYMNAST</option><option>TRAINING_PLAN</option><option>TRAINING_EVIDENCE</option><option>TESTING_RESULT</option><option>COMPETITION_RESULT</option><option>ROUTINE</option><option>PROGRAMME</option><option>METHODOLOGY</option><option>OPERATIONS</option><option>TEMPLATE</option><option>REFERENCE</option></select><select name="dataRole" defaultValue="INDIVIDUAL_EVIDENCE"><option>INDIVIDUAL_EVIDENCE</option><option>CLUB_PROGRAMME</option><option>CLUB_METHODOLOGY</option><option>GOVERNING_BODY_REFERENCE</option><option>OPERATIONS_ADMIN</option><option>COMMUNICATIONS</option><option>TEMPLATE</option><option>ARCHIVE_REFERENCE</option></select><select name="visibility" defaultValue="INTERNAL"><option>INTERNAL</option><option>COACH</option><option>GYMNAST</option><option>HISTORICAL_ONLY</option></select></div><div className="grid gap-2 md:grid-cols-2"><select name="importTreatment" defaultValue="STAGE"><option>STAGE</option><option>LINK_ONLY</option><option>REFERENCE_ONLY</option><option>SKIP</option></select><select name="proposedAction" defaultValue="REVIEW"><option>REVIEW</option><option>CREATE</option><option>UPDATE</option><option>LINK</option><option>SKIP</option></select></div><textarea name="payload" required placeholder="Extracted source value / summary"/><textarea name="interpretation" placeholder="Interpretation, ambiguity or mapping note"/><button className="workspace-button workspace-button-primary">Stage for review</button></form></details>
   <section className="mt-5"><h3 className="text-sm font-semibold">Review queue</h3><div className="mt-2 grid gap-2">{b.candidates.map(x=>{const links=b.recordLinks.filter(link=>link.candidateId===x.id);const importedAt=links.length?links.reduce((latest,link)=>link.createdAt>latest?link.createdAt:latest,links[0].createdAt):null;return <div key={x.id} className="rounded-xl border border-[var(--border)] p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong>{x.entityType.replaceAll("_"," ")}</strong><p className="text-xs text-[var(--muted)]">{x.dataRole.replaceAll("_"," ")} · {x.importTreatment.replaceAll("_"," ")} → {x.proposedAction.replaceAll("_"," ")} · {importedAt?"IMPORTED":x.reviewStatus}</p>{importedAt&&<p className="mt-1 text-xs font-medium">Imported {day(importedAt)} · {links.length} record link{links.length===1?"":"s"}</p>}</div><form action={reviewImportCandidate} className="flex flex-wrap gap-1"><input type="hidden" name="candidateId" value={x.id}/>{["APPROVED","HOLD","REJECTED"].map(s=><button key={s} name="reviewStatus" value={s} className="workspace-button">{s==="HOLD"?"Hold":s[0]+s.slice(1).toLowerCase()}</button>)}</form>{!importedAt&&x.reviewStatus==="APPROVED"&&x.importTreatment==="STAGE"&&x.proposedAction==="CREATE"&&<form action={executeApprovedImportCandidate}><input type="hidden" name="candidateId" value={x.id}/><button className="workspace-button workspace-button-primary">Import approved</button></form>}</div><p className="mt-2 text-sm whitespace-pre-wrap">{(()=>{try{const p=JSON.parse(x.payloadJson);return p.raw??x.payloadJson}catch{return x.payloadJson}})()}</p>{x.sourceEntityKey&&<p className="mt-2 text-xs text-[var(--muted)]">Source identity: {x.sourceEntityKey}</p>}</div>})}{!b.candidates.length&&<div className="empty-state">Nothing staged yet. Discovery and review happen before import.</div>}</div></section>
  </article>)}{!batches.length&&<div className="empty-state">No import batches yet.</div>}</div>
 </section></AppShell>;
}
