-- Phase 3A: organisation-owned coaching programmes and stages.
-- Structure only; no programme, ruleset, level, QA or demo data is inserted.
CREATE TABLE "CoachingProgramme" ("id" TEXT NOT NULL PRIMARY KEY,"organisationId" TEXT NOT NULL,"name" TEXT NOT NULL,"programmeType" TEXT NOT NULL,"discipline" TEXT NOT NULL DEFAULT 'GENERAL',"description" TEXT,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "CoachingProgramme_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "CoachingProgramme_organisationId_name_key" ON "CoachingProgramme"("organisationId","name");
CREATE INDEX "CoachingProgramme_organisationId_programmeType_status_idx" ON "CoachingProgramme"("organisationId","programmeType","status");
CREATE TABLE "ProgrammeStage" ("id" TEXT NOT NULL PRIMARY KEY,"programmeId" TEXT NOT NULL,"name" TEXT NOT NULL,"orderIndex" INTEGER NOT NULL DEFAULT 0,"description" TEXT,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "ProgrammeStage_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "CoachingProgramme" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "ProgrammeStage_programmeId_name_key" ON "ProgrammeStage"("programmeId","name");
CREATE INDEX "ProgrammeStage_programmeId_orderIndex_status_idx" ON "ProgrammeStage"("programmeId","orderIndex","status");
CREATE TABLE "TrainingGroupProgrammeAssignment" ("trainingGroupId" TEXT NOT NULL PRIMARY KEY,"programmeId" TEXT NOT NULL,"stageId" TEXT,"assignedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TrainingGroupProgrammeAssignment_trainingGroupId_fkey" FOREIGN KEY ("trainingGroupId") REFERENCES "TrainingGroup" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "TrainingGroupProgrammeAssignment_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "CoachingProgramme" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "TrainingGroupProgrammeAssignment_stageId_fkey" FOREIGN KEY ("stageId") REFERENCES "ProgrammeStage" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX "TrainingGroupProgrammeAssignment_programmeId_stageId_idx" ON "TrainingGroupProgrammeAssignment"("programmeId","stageId");
CREATE TABLE "GymnastProgrammeAssignment" ("gymnastId" TEXT NOT NULL PRIMARY KEY,"programmeId" TEXT NOT NULL,"stageId" TEXT,"assignedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GymnastProgrammeAssignment_gymnastId_fkey" FOREIGN KEY ("gymnastId") REFERENCES "Gymnast" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "GymnastProgrammeAssignment_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "CoachingProgramme" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "GymnastProgrammeAssignment_stageId_fkey" FOREIGN KEY ("stageId") REFERENCES "ProgrammeStage" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX "GymnastProgrammeAssignment_programmeId_stageId_idx" ON "GymnastProgrammeAssignment"("programmeId","stageId");
