import { AppShell } from "@/app/components/app-shell";
import { addGymnastToGroup,createGroup,createGymnast,deleteGroup,deleteGymnast,removeGymnastFromGroup,renameGroup,setPrimaryGroup,updateGymnast,assignCoachToGroup,removeCoachFromGroup } from "@/app/actions/core-coaching";
import { requireAuthContext } from "@/app/lib/auth";
import { prisma } from "@/app/lib/prisma";
import { groupScopeWhere, gymnastScopeWhere } from "@/app/lib/coaching-scope";
export const dynamic="force-dynamic";
const dateValue=(d:Date|null)=>d?d.toISOString().slice(0,10):"";

export default async function GroupsPage(){
 const c=await requireAuthContext();
 if(!c.access.canUseCoachingWorkspace)return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><p>Coaching workspace access is not assigned to this account.</p></AppShell>;
 const scope=groupScopeWhere(c.organisation.id,c.membership.id,c.access),gymnastScope=gymnastScopeWhere(c.organisation.id,c.membership.id,c.access);
 const [groups,gymnasts,coaches]=await Promise.all([
  prisma.trainingGroup.findMany({where:scope,include:{memberships:{include:{gymnast:true},orderBy:{joinedAt:"asc"}},coachAssignments:{include:{membership:{include:{user:true}}},orderBy:{assignedAt:"asc"}}},orderBy:{name:"asc"}}),
  prisma.gymnast.findMany({where:gymnastScope,include:{groups:{include:{trainingGroup:true},orderBy:{joinedAt:"asc"}}},orderBy:{name:"asc"}}),
  prisma.organisationMembership.findMany({where:{organisationId:c.organisation.id,isActive:true},include:{user:true},orderBy:{joinedAt:"asc"}})
 ]);
 const canManage=c.access.canManagePeopleAndRoles,assigned=new Set(groups.flatMap(g=>g.memberships.map(m=>m.gymnastId)));
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section>
  <p className="text-sm font-semibold text-[var(--muted)]">My Groups</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">Your coaching groups</h1><p className="mt-3 max-w-2xl leading-7 text-[var(--muted)]">Manage the real club roster. Gymnasts keep one identity even when they train across multiple groups.</p></div><p className="text-sm text-[var(--muted)]">{groups.length} groups · {gymnasts.length} gymnasts</p></div>
  {canManage&&<div className="mt-8 grid gap-4 lg:grid-cols-2"><form action={createGroup} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Create group</h2><div className="mt-4 flex gap-2"><input name="name" required placeholder="Group name" className="min-w-0 flex-1 rounded-xl border border-[var(--border)] px-4 py-3"/><button className="rounded-xl bg-[var(--foreground)] px-4 py-3 font-semibold text-white">Create</button></div></form><form action={createGymnast} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Add gymnast</h2><div className="mt-4 grid gap-2 sm:grid-cols-3"><input name="name" required placeholder="Name" className="rounded-xl border border-[var(--border)] px-3 py-3"/><input name="dateOfBirth" type="date" className="rounded-xl border border-[var(--border)] px-3 py-3"/><select name="groupId" className="rounded-xl border border-[var(--border)] px-3 py-3"><option value="">Unassigned</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><button className="mt-3 rounded-xl bg-[var(--foreground)] px-4 py-3 font-semibold text-white">Add gymnast</button></form></div>}
  <div className="mt-8 grid gap-4">{groups.length===0?<div className="rounded-2xl border border-dashed border-[var(--border)] p-8 text-center"><h2 className="text-lg font-semibold">No groups yet</h2><p className="mt-2 text-sm text-[var(--muted)]">Create the first real coaching group when you are ready.</p></div>:groups.map(g=><details key={g.id} open className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{g.name}</h2><span className="text-sm text-[var(--muted)]">{g.memberships.length} gymnasts</span></div></summary>
   <div className="mt-3 text-sm text-[var(--muted)]">{g.coachAssignments.length?g.coachAssignments.map(a=>a.membership.user.displayName).join(" · "):"No coaches assigned"}</div>{canManage&&<div className="mt-4 flex flex-wrap gap-2 border-t border-[var(--border)] pt-4"><form action={renameGroup} className="flex gap-2"><input type="hidden" name="groupId" value={g.id}/><input name="name" defaultValue={g.name} className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm"/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Rename</button></form><form action={deleteGroup}><input type="hidden" name="groupId" value={g.id}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Delete group</button></form><form action={addGymnastToGroup} className="flex gap-2"><input type="hidden" name="groupId" value={g.id}/><select name="gymnastId" required className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm"><option value="">Add gymnast…</option>{gymnasts.filter(x=>!g.memberships.some(m=>m.gymnastId===x.id)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Add</button></form><form action={assignCoachToGroup} className="flex gap-2"><input type="hidden" name="groupId" value={g.id}/><select name="membershipId" required className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm"><option value="">Assign coach…</option>{coaches.filter(x=>!g.coachAssignments.some(a=>a.membershipId===x.id)).map(x=><option key={x.id} value={x.id}>{x.user.displayName}</option>)}</select><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Assign</button></form>{g.coachAssignments.map(a=><form key={a.membershipId} action={removeCoachFromGroup}><input type="hidden" name="groupId" value={g.id}/><input type="hidden" name="membershipId" value={a.membershipId}/><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm">Remove {a.membership.user.displayName}</button></form>)}</div>}
   <div className="mt-4 grid gap-2">{g.memberships.length?g.memberships.map(m=><div key={m.gymnastId} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--border)] px-4 py-3"><span className="font-medium">{m.gymnast.name}{m.isPrimary&&<small className="ml-2 text-[var(--muted)]">Primary group</small>}</span>{canManage&&<div className="flex gap-2">{!m.isPrimary&&<form action={setPrimaryGroup}><input type="hidden" name="gymnastId" value={m.gymnastId}/><input type="hidden" name="groupId" value={g.id}/><button className="text-sm font-semibold">Make primary</button></form>}<form action={removeGymnastFromGroup}><input type="hidden" name="gymnastId" value={m.gymnastId}/><input type="hidden" name="groupId" value={g.id}/><button className="text-sm text-[var(--muted)]">Remove</button></form></div>}</div>):<p className="text-sm text-[var(--muted)]">No gymnasts assigned.</p>}</div>
  </details>)}</div>
  <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-[var(--muted)]">Gymnasts</p><h2 className="mt-1 text-2xl font-semibold">Club roster</h2></div><span className="text-sm text-[var(--muted)]">{gymnasts.length}</span></div><div className="mt-4 grid gap-3">{gymnasts.length?gymnasts.map(g=><details key={g.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><summary className="cursor-pointer list-none font-semibold">{g.name}<small className="ml-3 font-normal text-[var(--muted)]">{g.groups.length?g.groups.map(x=>x.trainingGroup.name).join(" · "):"Unassigned"}</small></summary>{canManage&&<div className="mt-4 border-t border-[var(--border)] pt-4"><form action={updateGymnast} className="grid gap-2 sm:grid-cols-[1fr_180px_auto]"><input type="hidden" name="gymnastId" value={g.id}/><input name="name" defaultValue={g.name} required className="rounded-lg border border-[var(--border)] px-3 py-2"/><input name="dateOfBirth" type="date" defaultValue={dateValue(g.dateOfBirth)} className="rounded-lg border border-[var(--border)] px-3 py-2"/><button className="rounded-lg border border-[var(--border)] px-3 py-2 font-semibold">Save</button></form><form action={deleteGymnast} className="mt-3"><input type="hidden" name="gymnastId" value={g.id}/><button className="text-sm text-[var(--muted)]">Delete gymnast</button></form></div>}</details>):<p className="rounded-2xl border border-dashed border-[var(--border)] p-6 text-sm text-[var(--muted)]">No gymnasts yet.</p>}</div></section>
  {gymnasts.some(g=>!assigned.has(g.id))&&<p className="mt-5 text-sm text-[var(--muted)]">{gymnasts.filter(g=>!assigned.has(g.id)).length} gymnast(s) currently unassigned.</p>}
 </section></AppShell>;
}
