import {AppShell} from "@/app/components/app-shell";
import {createGroup,createGymnast} from "@/app/actions/core-coaching";
import {requireAuthContext} from "@/app/lib/auth";
import {prisma} from "@/app/lib/prisma";
import {groupScopeWhere,gymnastScopeWhere} from "@/app/lib/coaching-scope";
export const dynamic="force-dynamic";
const days:Record<string,string>={MONDAY:"Mon",TUESDAY:"Tue",WEDNESDAY:"Wed",THURSDAY:"Thu",FRIDAY:"Fri",SATURDAY:"Sat",SUNDAY:"Sun"};
const hours=(slots:{startTime:string;endTime:string}[])=>slots.reduce((n,s)=>{const [sh,sm]=s.startTime.split(":").map(Number),[eh,em]=s.endTime.split(":").map(Number);return n+Math.max(0,(eh*60+em-sh*60-sm)/60)},0);
export default async function GroupsPage({searchParams}:{searchParams:Promise<{view?:string;q?:string;sort?:string}>}){
 const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><p>Coaching workspace access is not assigned.</p></AppShell>;
 const query=await searchParams,view=query.view==="all"&&c.access.canViewAllCoachingData?"all":query.view==="gymnasts"?"gymnasts":"mine",q=(query.q??"").trim().toLowerCase(),sort=query.sort==="hours"?"hours":"name";
 const mineScope=groupScopeWhere(c.organisation.id,c.membership.id,c.access),groupWhere=view==="all"?{organisationId:c.organisation.id,status:"ACTIVE"}:mineScope,canManage=c.access.canManagePeopleAndRoles;
 const [groups,gymnasts,groupOptions]=await Promise.all([
  view==="gymnasts"?Promise.resolve([]):prisma.trainingGroup.findMany({where:groupWhere,include:{memberships:{where:{gymnast:{status:"ACTIVE"}},include:{gymnast:{include:{programmeAssignments:{include:{programme:true,stage:true}},rulesetAssignments:{include:{program:true,level:true}}}}}},coachAssignments:{include:{membership:{include:{user:true}}}},programmeAssignments:{include:{programme:true,stage:true}},scheduleSlots:{orderBy:{orderIndex:"asc"}}},orderBy:{name:"asc"}}),
  view==="gymnasts"?prisma.gymnast.findMany({where:gymnastScopeWhere(c.organisation.id,c.membership.id,c.access),select:{id:true,name:true,groups:{where:{trainingGroup:{status:"ACTIVE"}},select:{trainingGroup:{select:{name:true}}}},programmeAssignments:{select:{programme:{select:{name:true}},stage:{select:{name:true}}}},rulesetAssignments:{select:{level:{select:{name:true}}}}},orderBy:{name:"asc"}}):Promise.resolve([]),
  view==="gymnasts"&&canManage?prisma.trainingGroup.findMany({where:mineScope,select:{id:true,name:true},orderBy:{name:"asc"}}):Promise.resolve([])
 ]);
 const filteredGroups=groups.filter(g=>{if(!q)return true;const hay=[g.name,g.programmeAssignments[0]?.programme.name,g.programmeAssignments[0]?.stage?.name,...g.memberships.flatMap(m=>[m.gymnast.name,m.gymnast.programmeAssignments[0]?.programme.name,m.gymnast.rulesetAssignments[0]?.level?.name])].filter(Boolean).join(" ").toLowerCase();return hay.includes(q)}).sort((a,b)=>sort==="hours"?hours(b.scheduleSlots)-hours(a.scheduleSlots):a.name.localeCompare(b.name));
 const filteredGymnasts=gymnasts.filter(g=>!q||[g.name,...g.groups.map(x=>x.trainingGroup.name),g.programmeAssignments[0]?.programme.name,g.rulesetAssignments[0]?.level?.name].filter(Boolean).join(" ").toLowerCase().includes(q));
 const addGymnastGroups=view==="gymnasts"?groupOptions:groups,qs=query.q?"&q="+encodeURIComponent(query.q):"";
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page groups-workspace">
  <div className="workspace-hero"><div><p className="workspace-kicker">My Groups</p><h1>Groups</h1><p className="workspace-meta">{view==="gymnasts"?gymnasts.length+" gymnast"+(gymnasts.length===1?"":"s"):groups.length+" group"+(groups.length===1?"":"s")}</p></div>{canManage&&<div className="workspace-actions groups-hero-actions"><details><summary className="workspace-button">+ Add gymnast</summary><form action={createGymnast}><input name="name" required placeholder="Name"/><input name="dateOfBirth" type="date"/><select name="groupId"><option value="">Unassigned</option>{addGymnastGroups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button>Add gymnast</button></form></details><details><summary className="workspace-button workspace-button-primary">+ Create group</summary><form action={createGroup}><input name="name" required placeholder="Group name"/><button>Create group</button></form></details></div>}</div>
  <form className="groups-workspace-search"><input type="hidden" name="view" value={view}/><input type="hidden" name="sort" value={sort}/><input name="q" defaultValue={query.q??""} placeholder="Search by name, group, programme or level…" aria-label="Search groups and gymnasts"/><button>Search</button></form>
  <div className="groups-workspace-nav"><nav className="workspace-tabs"><a className={view==="mine"?"active":""} href={"/groups?view=mine"+qs}>My groups</a>{c.access.canViewAllCoachingData&&<a className={view==="all"?"active":""} href={"/groups?view=all"+qs}>All groups</a>}<a className={view==="gymnasts"?"active":""} href={"/groups?view=gymnasts"+qs}>Gymnasts</a></nav>{view!=="gymnasts"&&<div className="groups-workspace-sort"><span>Sort</span><a className={sort==="name"?"active":""} href={"/groups?view="+view+"&sort=name"+qs}>Name</a><a className={sort==="hours"?"active":""} href={"/groups?view="+view+"&sort=hours"+qs}>Hours</a></div>}</div>
  <div className="groups-workspace-content">{view==="gymnasts"?<><div className="section-heading"><h2>Gymnasts</h2><span>{filteredGymnasts.length}</span></div><div className="gymnast-directory-grid mt-3">{filteredGymnasts.map(g=>{const programme=g.programmeAssignments[0],rules=g.rulesetAssignments[0];return <a key={g.id} href={"/gymnasts/"+g.id} className="gymnast-directory-card"><span className="gymnast-directory-avatar">{g.name.slice(0,1).toUpperCase()}</span><span><strong>{g.name}</strong><small>{[programme?.programme.name,programme?.stage?.name,rules?.level?.name].filter(Boolean).join(" · ")||g.groups.map(x=>x.trainingGroup.name).join(" · ")||"Unassigned"}</small></span><b>›</b></a>})}{!filteredGymnasts.length&&<div className="empty-state">No gymnasts found</div>}</div></>:<><div className="section-heading"><h2>{view==="mine"?"My groups":"All groups"}</h2><span>{filteredGroups.length}</span></div><div className="groups-directory-list mt-3">{filteredGroups.map(g=>{const programme=g.programmeAssignments[0],h=hours(g.scheduleSlots),youCoach=g.coachAssignments.some(a=>a.membershipId===c.membership.id),names=g.memberships.map(m=>m.gymnast.name);return <a key={g.id} href={"/groups/"+g.id} className="groups-directory-card"><div className="groups-directory-card-main"><div className="groups-directory-card-title"><strong>{g.name}</strong><b className="groups-directory-chevron">›</b></div><small>{[programme?.programme.name,programme?.stage?.name,g.scheduleSlots.map(s=>days[s.dayOfWeek]+" "+s.startTime+"–"+s.endTime).join(" · ")].filter(Boolean).join(" · ")||"Schedule not set"}</small><div className="groups-directory-gymnasts">{names.slice(0,6).map(name=><span key={name}>{name}</span>)}{names.length>6&&<span>+{names.length-6} more</span>}{!names.length&&<span>No gymnasts assigned</span>}</div></div><div className="groups-directory-card-footer"><span><strong>{g.memberships.length}</strong> gymnast{g.memberships.length===1?"":"s"}</span><span><strong>{h.toFixed(1)}</strong> hrs/week</span>{youCoach&&<span className="groups-directory-coach">You coach</span>}</div></a>})}{!filteredGroups.length&&<div className="empty-state">No groups found</div>}</div></>}</div>
 </section></AppShell>
}