import {AppShell} from "@/app/components/app-shell";
import {OverviewWidgets,type OverviewWidget} from "@/app/components/overview-widgets";
import {requireAuthContext} from "@/app/lib/auth";import {groupScopeWhere} from "@/app/lib/coaching-scope";import {prisma} from "@/app/lib/prisma";import {readOverviewLayout} from "@/app/lib/widget-layout";
export const dynamic="force-dynamic";const day=(d:Date)=>new Intl.DateTimeFormat("en-IE",{weekday:"short",day:"numeric",month:"short"}).format(d);const card="overview-data-card";
export default async function Dashboard(){const c=await requireAuthContext();if(!c.access.canUseCoachingWorkspace)return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><div className="workspace-hero"><div><p className="workspace-kicker">Home</p><h1>Club operations</h1></div><div className="workspace-actions"><a href="/more" className="workspace-button">More</a></div></div></section></AppShell>;
 const now=new Date(),week=new Date(Date.now()+7*86400000),fortnight=new Date(Date.now()+14*86400000),scope=groupScopeWhere(c.organisation.id,c.membership.id,c.access);
 const [groups,sessions,evidence,handoffs,competitions,reviews,tests,preference,leadership,facilities]=await Promise.all([
 prisma.trainingGroup.findMany({where:scope,include:{_count:{select:{memberships:true}}},orderBy:{name:"asc"},take:12}),
 prisma.trainingSession.findMany({where:{organisationId:c.organisation.id,sessionDate:{gte:now,lte:week},trainingGroup:scope},include:{trainingGroup:true,blocks:{orderBy:{orderIndex:"asc"}},rotationAssignments:{include:{rotationGroup:true,trainingSpace:true},orderBy:{orderIndex:"asc"}}},orderBy:[{sessionDate:"asc"},{startTime:"asc"}],take:10}),
 prisma.trainingEvidence.findMany({where:{gymnast:{groups:{some:{trainingGroup:scope}}}},include:{gymnast:true},orderBy:{recordedAt:"desc"},take:8}),
 prisma.coachHandoff.findMany({where:{organisationId:c.organisation.id,toMembershipId:c.membership.id,status:"ACTIVE"},include:{fromMembership:{include:{user:true}}},orderBy:{endsAt:"asc"},take:6}),
 prisma.competitionEvent.findMany({where:{organisationId:c.organisation.id,eventDate:{gte:now,lte:fortnight},status:{in:["PLANNED","IN_PROGRESS"]}},orderBy:{eventDate:"asc"},take:6}),
 c.access.isHeadCoach||c.access.coachingRoles.includes("PROGRAMME_LEAD")?prisma.methodologyRecord.findMany({where:{organisationId:c.organisation.id,status:"IN_REVIEW"},orderBy:{updatedAt:"asc"},take:6}):Promise.resolve([]),
 prisma.testingSession.findMany({where:{organisationId:c.organisation.id,trainingGroup:scope},include:{trainingGroup:true,results:{select:{id:true}}},orderBy:{testedAt:"desc"},take:5}),
 prisma.membershipPresentationPreference.findUnique({where:{membershipId:c.membership.id}}),
 c.access.coachingRoles.includes("PROGRAMME_LEAD")?prisma.programmeLeadAssignment.findMany({where:{organisationId:c.organisation.id,membershipId:c.membership.id},include:{programme:true}}):Promise.resolve([]),
 c.access.canConfigureFacilities?prisma.facilityLocation.count({where:{organisationId:c.organisation.id,status:"ACTIVE"}}):Promise.resolve(0)
 ]);
 const next=sessions[0],attention=handoffs.length+reviews.length,small=(label:string,value:string|number,href:string)=><a href={href} className={card}><p>{label}</p><strong>{value}</strong></a>;
 const widgets:OverviewWidget[]=[
 {id:"CALENDAR",title:"Calendar",category:"Schedule",default:true,defaultSize:"M",small:small("Calendar",sessions.length+" this week","/calendar"),medium:<a href="/calendar" className={card}><p>Calendar</p><strong>{sessions.length} this week</strong><div>{sessions.slice(0,3).map(s=><span key={s.id}>{day(s.sessionDate)} · {s.trainingGroup.name}</span>)}{!sessions.length&&<span>No sessions</span>}</div></a>,large:<a href="/calendar" className={card}><p>Calendar</p><strong>{sessions.length} sessions this week</strong><div>{sessions.slice(0,6).map(s=><span key={s.id}>{day(s.sessionDate)} · {s.startTime} · {s.trainingGroup.name}</span>)}</div></a>},
 {id:"ROTATIONS",title:"Rotations",category:"Training",default:true,small:small("Rotations",next?.rotationAssignments.length??0,"/training"),medium:<a href="/training" className={card}><p>Rotations</p><strong>{next?next.trainingGroup.name:"No upcoming session"}</strong><div>{next?.rotationAssignments.slice(0,3).map(r=><span key={r.id}>{r.rotationGroup.name}{r.trainingSpace?" · "+r.trainingSpace.name:""}</span>)??<span>No rotations</span>}</div></a>},
 {id:"TRAINING_PLAN",title:"Current training plan",category:"Training",default:true,defaultSize:"L",small:small("Current training plan",next?.title??"No plan","/planning"),medium:<a href={next?"/planning/"+next.id:"/planning"} className={card}><p>Current training plan</p><strong>{next?.title??"No session planned"}</strong>{next&&<div><span>{next.trainingGroup.name} · {day(next.sessionDate)}</span><span>{next.blocks.length} blocks</span></div>}</a>,large:<a href={next?"/planning/"+next.id:"/planning"} className={card}><p>Current training plan</p><strong>{next?.title??"No session planned"}</strong>{next&&<div><span>{next.trainingGroup.name} · {day(next.sessionDate)} · {next.startTime}–{next.endTime}</span>{next.sessionIntent&&<span>{next.sessionIntent}</span>}<span>{next.blocks.slice(0,4).map(b=>b.title).join(" · ")||"No blocks yet"}</span></div>}</a>},
 {id:"GROUPS",title:"Groups",category:"People",default:true,small:small("Groups",groups.length,"/groups"),medium:<a href="/groups" className={card}><p>Groups</p><strong>{groups.length}</strong><div>{groups.slice(0,4).map(g=><span key={g.id}>{g.name} · {g._count.memberships}</span>)}</div></a>},
 {id:"EVIDENCE",title:"Evidence",category:"Evidence",default:true,small:small("Evidence",evidence.length?evidence[0].outcome:"No recent evidence","/progress"),medium:<a href="/progress" className={card}><p>Evidence</p><strong>{evidence.length?"Recent evidence":"No recent evidence"}</strong><div>{evidence.slice(0,4).map(x=><span key={x.id}>{x.gymnast.name} · {x.outcome}</span>)}</div></a>},
 {id:"ATTENTION",title:"Worth your attention",category:"Evidence",default:true,small:small("Worth your attention",attention,"/updates"),medium:<a href="/updates" className={card}><p>Worth your attention</p><strong>{attention}</strong><div><span>{handoffs.length} handoff{handoffs.length===1?"":"s"}</span><span>{reviews.length} review{reviews.length===1?"":"s"}</span></div></a>},
 {id:"NEXT",title:"Next session",category:"Schedule",default:false,small:small("Next session",next?.trainingGroup.name??"None","/planning"),medium:<a href={next?"/planning/"+next.id:"/planning"} className={card}><p>Next session</p><strong>{next?.title??"No session planned"}</strong>{next&&<div><span>{day(next.sessionDate)} · {next.startTime}</span></div>}</a>},
 {id:"WEEK",title:"This week",category:"Schedule",default:false,small:small("This week",sessions.length+" sessions","/calendar"),medium:<a href="/calendar" className={card}><p>This week</p><strong>{sessions.length} sessions</strong><div>{sessions.slice(0,4).map(s=><span key={s.id}>{day(s.sessionDate)} · {s.trainingGroup.name}</span>)}</div></a>},
 {id:"COMPETITIONS",title:"Upcoming competitions",category:"Competition",default:false,small:small("Competitions",competitions.length,"/competitions"),medium:<a href="/competitions" className={card}><p>Upcoming competitions</p><strong>{competitions.length||"None"}</strong><div>{competitions.slice(0,3).map(e=><span key={e.id}>{e.name} · {day(e.eventDate)}</span>)}</div></a>},
 {id:"TESTING",title:"Testing",category:"Evidence",default:false,small:small("Testing",tests.length?tests[0].trainingGroup.name:"No testing","/testing"),medium:<a href="/testing" className={card}><p>Testing</p><strong>{tests.length?"Recent testing":"No testing sessions"}</strong><div>{tests.slice(0,3).map(t=><span key={t.id}>{t.trainingGroup.name} · {day(t.testedAt)} · {t.results.length} results</span>)}</div></a>},
 {id:"ACTIVITY",title:"Recent activity",category:"Evidence",default:false,small:small("Recent activity",evidence.length+" records","/progress"),medium:<a href="/progress" className={card}><p>Recent activity</p><strong>{evidence.length?"Evidence captured":"No recent activity"}</strong><div>{evidence.slice(0,3).map(x=><span key={x.id}>{x.gymnast.name} · {x.outcome}</span>)}</div></a>},
 {id:"HANDOFFS",title:"Coach handoffs",category:"Coaching",default:false,small:small("Coach handoffs",handoffs.length,"/handoffs"),medium:<a href="/handoffs" className={card}><p>Coach handoffs</p><strong>{handoffs.length||"None active"}</strong><div>{handoffs.slice(0,3).map(h=><span key={h.id}>{h.title} · {h.fromMembership.user.displayName}</span>)}</div></a>},
 {id:"PROGRAMMES",title:"Programme responsibilities",category:"Coaching",default:false,small:small("Programme responsibilities",leadership.length,"/programmes"),medium:<a href="/programmes" className={card}><p>Programme responsibilities</p><strong>{leadership.length}</strong><div>{leadership.map(x=><span key={x.id}>{x.programme.name}</span>)}</div></a>},
 {id:"FACILITIES",title:"Facilities",category:"Organisation",default:false,small:small("Facilities",facilities,"/facilities"),medium:<a href="/facilities" className={card}><p>Facilities</p><strong>{facilities}</strong><div><span>Active locations</span></div></a>}
 ];
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><div className="workspace-hero home-hero"><div><p className="workspace-kicker">Home</p><h1>{c.user.displayName.split(" ")[0]}</h1><p className="workspace-meta">{next?next.trainingGroup.name+" · "+day(next.sessionDate)+" · "+next.startTime:"No upcoming session"}</p></div><div className="workspace-actions"><a href="/planning" className="workspace-button">Review plan</a><a href="/training" className="workspace-button workspace-button-primary">Open training</a></div></div><div className="mt-7"><OverviewWidgets surface="HOME" initialLayout={readOverviewLayout(preference,"HOME")} widgets={widgets}/></div></section></AppShell>;
}