import {AppShell} from "@/app/components/app-shell";
import {OverviewWidgets} from "@/app/components/overview-widgets";
import {requireAuthContext} from "@/app/lib/auth";
import {groupScopeWhere} from "@/app/lib/coaching-scope";
import {prisma} from "@/app/lib/prisma";
export const dynamic="force-dynamic";
const day=(d:Date)=>new Intl.DateTimeFormat("en-IE",{weekday:"short",day:"numeric",month:"short"}).format(d);
export default async function Dashboard(){
 const c=await requireAuthContext();
 if(!c.access.canUseCoachingWorkspace)return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><div className="workspace-hero"><p className="workspace-kicker">Home</p><h1>Club operations</h1><div className="workspace-actions"><a href="/more" className="workspace-button">Open More</a></div></div></section></AppShell>;
 const now=new Date(),week=new Date(Date.now()+7*86400000),fortnight=new Date(Date.now()+14*86400000),scope=groupScopeWhere(c.organisation.id,c.membership.id,c.access);
 const [groups,sessions,evidence,handoffs,competitions,reviews,preference]=await Promise.all([
  prisma.trainingGroup.findMany({where:scope,include:{_count:{select:{memberships:true}}},orderBy:{name:"asc"},take:8}),
  prisma.trainingSession.findMany({where:{organisationId:c.organisation.id,sessionDate:{gte:now,lte:week},trainingGroup:scope},include:{trainingGroup:true},orderBy:[{sessionDate:"asc"},{startTime:"asc"}],take:8}),
  prisma.trainingEvidence.findMany({where:{gymnast:{groups:{some:{trainingGroup:scope}}}},include:{gymnast:true},orderBy:{recordedAt:"desc"},take:6}),
  prisma.coachHandoff.findMany({where:{organisationId:c.organisation.id,toMembershipId:c.membership.id,status:"ACTIVE"},include:{fromMembership:{include:{user:true}}},orderBy:{endsAt:"asc"},take:6}),
  prisma.competitionEvent.findMany({where:{organisationId:c.organisation.id,eventDate:{gte:now,lte:fortnight},status:{in:["PLANNED","IN_PROGRESS"]}},orderBy:{eventDate:"asc"},take:6}),
  c.access.isHeadCoach||c.access.coachingRoles.includes("PROGRAMME_LEAD")?prisma.methodologyRecord.findMany({where:{organisationId:c.organisation.id,status:"IN_REVIEW"},orderBy:{updatedAt:"asc"},take:6}):Promise.resolve([]),
  prisma.membershipPresentationPreference.findUnique({where:{membershipId:c.membership.id}})
 ]);
 const parse=(value:string|undefined)=>{try{const x=JSON.parse(value??"[]");return Array.isArray(x)?x.filter((v):v is string=>typeof v==="string"):[]}catch{return[]}};
 const initialLayout=preference?{order:parse(preference.homeWidgetOrder),hidden:parse(preference.homeWidgetHidden),wide:parse(preference.homeWidgetWide)}:null;
 const card="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm";
 const widgets=[
  {id:"NEXT",title:"Next training",wide:true,content:<article className={card}><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Next training</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">{sessions[0]?.title||"No session planned"}</h2>{sessions[0]&&<p className="mt-2 text-sm text-[var(--muted)]">{sessions[0].trainingGroup.name} · {day(sessions[0].sessionDate)} · {sessions[0].startTime}–{sessions[0].endTime}</p>}</div><a href={sessions[0]?"/planning/"+sessions[0].id:"/planning"} className="text-sm font-semibold">{sessions[0]?"Open session":"Open planning"} →</a></div></article>},
  {id:"GROUPS",title:"My groups",content:<a href="/groups" className={card+" block h-full"}><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">My groups</p><h2 className="mt-2 text-3xl font-semibold">{groups.length}</h2><div className="mt-3 grid gap-2">{groups.slice(0,4).map(g=><span key={g.id} className="text-sm">{g.name} <small className="text-[var(--muted)]">· {g._count.memberships}</small></span>)}</div></a>},
  {id:"EVIDENCE",title:"Recent evidence",content:<a href="/progress" className={card+" block h-full"}><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Recent evidence</p><div className="mt-3 grid gap-2">{evidence.slice(0,4).map(x=><span key={x.id} className="text-sm"><strong>{x.gymnast.name}</strong> · {x.outcome}</span>)}{!evidence.length&&<span className="text-sm text-[var(--muted)]">No recent evidence</span>}</div></a>},
  {id:"ATTENTION",title:"Worth your attention",content:<a href="/updates" className={card+" block h-full"}><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Worth your attention</p><h2 className="mt-2 text-3xl font-semibold">{handoffs.length+reviews.length}</h2><p className="mt-2 text-sm text-[var(--muted)]">{handoffs.length} handoff{handoffs.length===1?"":"s"} · {reviews.length} review{reviews.length===1?"":"s"}</p></a>},
  {id:"WEEK",title:"Coming up",content:<a href="/calendar" className={card+" block h-full"}><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Coming up</p><div className="mt-3 grid gap-2">{sessions.slice(0,4).map(s=><span key={s.id} className="text-sm"><strong>{day(s.sessionDate)}</strong> · {s.trainingGroup.name}</span>)}{!sessions.length&&<span className="text-sm text-[var(--muted)]">No sessions</span>}</div></a>},
  {id:"COMPETITIONS",title:"Competitions",content:<a href="/competitions" className={card+" block h-full"}><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Competitions</p><div className="mt-3 grid gap-2">{competitions.slice(0,3).map(e=><span key={e.id} className="text-sm"><strong>{e.name}</strong> · {day(e.eventDate)}</span>)}{!competitions.length&&<span className="text-sm text-[var(--muted)]">No upcoming competitions</span>}</div></a>}
 ];
 return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section className="workspace-page"><div className="workspace-hero home-hero"><div><p className="workspace-kicker">Home</p><h1>{c.user.displayName.split(" ")[0]}</h1><p className="workspace-meta">{sessions[0]?sessions[0].trainingGroup.name+" · "+day(sessions[0].sessionDate)+" · "+sessions[0].startTime:"No upcoming session"}</p></div><div className="workspace-actions"><a href="/planning" className="workspace-button">Review plan</a><a href="/training" className="workspace-button workspace-button-primary">Open training</a></div></div><div className="mt-7"><OverviewWidgets initialLayout={initialLayout} widgets={widgets}/></div></section></AppShell>;
}