import { notFound } from "next/navigation";
import { AppShell } from "@/app/components/app-shell";
import { assignProgrammeLead, removeProgrammeLead } from "@/app/actions/methodology";
import { requireAuthContext } from "@/app/lib/auth";
import { prisma } from "@/app/lib/prisma";
export const dynamic="force-dynamic";
const roles=(v:string)=>{try{const x=JSON.parse(v);return Array.isArray(x)?x:[]}catch{return []}};
export default async function ProgrammeLeadsPage(){const c=await requireAuthContext();if(!c.access.canManageProgrammesAndMethodology)notFound();const [programmes,members]=await Promise.all([
 prisma.coachingProgramme.findMany({where:{organisationId:c.organisation.id,status:"ACTIVE"},include:{leads:{include:{membership:{include:{user:true}}}}},orderBy:{name:"asc"}}),
 prisma.organisationMembership.findMany({where:{organisationId:c.organisation.id,isActive:true},include:{user:true},orderBy:{joinedAt:"asc"}})
]);const eligible=members.filter(m=>{const r=roles(m.coachingRoles);return r.includes("PROGRAMME_LEAD")||r.includes("HEAD_COACH")});return <AppShell organisationName={c.organisation.name} displayName={c.user.displayName} access={c.access}><section><a href="/more" className="text-sm font-semibold text-[var(--muted)]">← More</a><p className="mt-5 text-sm font-semibold text-[var(--muted)]">Programme leadership</p><h1 className="mt-2 text-3xl font-semibold">Programme leads</h1><p className="mt-3 max-w-2xl leading-7 text-[var(--muted)]">Assign explicit leadership to club programmes. Staff must hold Programme Lead or Head Coach as a coaching role before they can be assigned here.</p><div className="mt-8 grid gap-4">{programmes.map(p=><article key={p.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="text-lg font-semibold">{p.name}</h2><div className="mt-3 flex flex-wrap gap-2">{p.leads.map(l=><form key={l.id} action={removeProgrammeLead}><input type="hidden" name="assignmentId" value={l.id}/><button className="rounded-full border border-[var(--border)] px-3 py-2 text-sm">{l.membership.user.displayName} ×</button></form>)}{!p.leads.length&&<span className="text-sm text-[var(--muted)]">No programme lead assigned.</span>}</div><form action={assignProgrammeLead} className="mt-4 flex flex-wrap gap-2 border-t border-[var(--border)] pt-4"><input type="hidden" name="programmeId" value={p.id}/><select name="membershipId" required className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm"><option value="">Assign lead…</option>{eligible.filter(m=>!p.leads.some(l=>l.membershipId===m.id)).map(m=><option key={m.id} value={m.id}>{m.user.displayName}</option>)}</select><button className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold">Assign</button></form></article>)}</div></section></AppShell>};
